*******************************************************************************
*! __parameters_write v1.0.0  04Feb2026
*! Write wbopendata parameters to YAML file
*! Called by _update_wbopendata - not intended for direct use
*******************************************************************************

program define __parameters_write
    version 14.0

    * Parse arguments - all values passed explicitly by caller
    syntax , TOTAL(string) NUMBER_INDICATORS(string) ///
        DT_UPDATE(string) DT_LASTCHECK(string) ///
        CTRYMETADATA(string) ///
        DT_CTRYLASTUPDATE(string) DT_CTRYLASTCHECK(string) DT_CTRYUPDATE(string) ///
        SRCCOUNTS(string) SRCNAMES(string) ///
        TOPCOUNTS(string) TOPNAMES(string)

    * srccounts: semicolon-delimited "code=count" pairs e.g. "01=127;02=781;..."
    * srcnames:  semicolon-delimited "code=name" pairs  e.g. "01=Doing Business;02=World Development Indicators;..."
    * topcounts/topnames: same format for topics

    *---------------------------------------------------------------------------
    * Resolve output path
    *---------------------------------------------------------------------------
    _wbopendata_get_yaml_path, type(parameters)
    local yaml_path = r(path)

    *---------------------------------------------------------------------------
    * Write YAML to tempfile first, then copy to destination
    *---------------------------------------------------------------------------
    tempfile out2
    tempname out

    file open `out' using `out2', write text replace

    * Header
    file write `out' "# wbopendata parameters" _n
    file write `out' "# Auto-generated by _update_wbopendata.ado" _n
    file write `out' "# Do not edit manually" _n
    file write `out' "" _n

    * Metadata section
    file write `out' "_metadata:" _n
    file write `out' "  version: 1.0.0" _n
    file write `out' `"  generated_at: '`dt_lastcheck''"' _n
    file write `out' "" _n

    * Indicator counts
    file write `out' `"total: `total'"' _n
    file write `out' `"number_indicators: `number_indicators'"' _n
    file write `out' "" _n

    * Timestamps
    file write `out' `"dt_update: '`dt_update''"' _n
    file write `out' `"dt_lastcheck: '`dt_lastcheck''"' _n
    file write `out' "" _n

    * Country metadata
    file write `out' `"ctrymetadata: `ctrymetadata'"' _n
    file write `out' `"dt_ctrylastupdate: '`dt_ctrylastupdate''"' _n
    file write `out' `"dt_ctrylastcheck: '`dt_ctrylastcheck''"' _n
    file write `out' `"dt_ctryupdate: '`dt_ctryupdate''"' _n
    file write `out' "" _n

    *---------------------------------------------------------------------------
    * Write sources section
    *---------------------------------------------------------------------------
    file write `out' "sources:" _n

    * Parse srccounts (semicolon-delimited "code=count" pairs)
    local src_remaining = "`srccounts'"
    while ("`src_remaining'" != "") {
        local semi_pos = strpos("`src_remaining'", ";")
        if (`semi_pos' > 0) {
            local src_pair = substr("`src_remaining'", 1, `semi_pos' - 1)
            local src_remaining = substr("`src_remaining'", `semi_pos' + 1, .)
        }
        else {
            local src_pair = "`src_remaining'"
            local src_remaining ""
        }

        * Extract code and count from "code=count"
        local eq_pos = strpos("`src_pair'", "=")
        if (`eq_pos' > 0) {
            local s_code = substr("`src_pair'", 1, `eq_pos' - 1)
            local s_count = substr("`src_pair'", `eq_pos' + 1, .)

            * Look up name from srcnames
            local s_name = ""
            local nm_remaining = "`srcnames'"
            while ("`nm_remaining'" != "") {
                local nm_semi = strpos("`nm_remaining'", ";")
                if (`nm_semi' > 0) {
                    local nm_pair = substr("`nm_remaining'", 1, `nm_semi' - 1)
                    local nm_remaining = substr("`nm_remaining'", `nm_semi' + 1, .)
                }
                else {
                    local nm_pair = "`nm_remaining'"
                    local nm_remaining ""
                }
                local nm_eq = strpos("`nm_pair'", "=")
                if (`nm_eq' > 0) {
                    local nm_code = substr("`nm_pair'", 1, `nm_eq' - 1)
                    if ("`nm_code'" == "`s_code'") {
                        local s_name = substr("`nm_pair'", `nm_eq' + 1, .)
                        local nm_remaining ""
                    }
                }
            }

            * Write source entry
            file write `out' `"  '`s_code'':"' _n
            file write `out' `"    count: `s_count'"' _n
            file write `out' `"    name: '`s_name''"' _n
        }
    }

    file write `out' "" _n

    *---------------------------------------------------------------------------
    * Write topics section
    *---------------------------------------------------------------------------
    file write `out' "topics:" _n

    * Parse topcounts (semicolon-delimited "code=count" pairs)
    local top_remaining = "`topcounts'"
    while ("`top_remaining'" != "") {
        local semi_pos = strpos("`top_remaining'", ";")
        if (`semi_pos' > 0) {
            local top_pair = substr("`top_remaining'", 1, `semi_pos' - 1)
            local top_remaining = substr("`top_remaining'", `semi_pos' + 1, .)
        }
        else {
            local top_pair = "`top_remaining'"
            local top_remaining ""
        }

        * Extract code and count from "code=count"
        local eq_pos = strpos("`top_pair'", "=")
        if (`eq_pos' > 0) {
            local t_code = substr("`top_pair'", 1, `eq_pos' - 1)
            local t_count = substr("`top_pair'", `eq_pos' + 1, .)

            * Look up name from topnames
            local t_name = ""
            local nm_remaining = "`topnames'"
            while ("`nm_remaining'" != "") {
                local nm_semi = strpos("`nm_remaining'", ";")
                if (`nm_semi' > 0) {
                    local nm_pair = substr("`nm_remaining'", 1, `nm_semi' - 1)
                    local nm_remaining = substr("`nm_remaining'", `nm_semi' + 1, .)
                }
                else {
                    local nm_pair = "`nm_remaining'"
                    local nm_remaining ""
                }
                local nm_eq = strpos("`nm_pair'", "=")
                if (`nm_eq' > 0) {
                    local nm_code = substr("`nm_pair'", 1, `nm_eq' - 1)
                    if ("`nm_code'" == "`t_code'") {
                        local t_name = substr("`nm_pair'", `nm_eq' + 1, .)
                        local nm_remaining ""
                    }
                }
            }

            * Write topic entry
            file write `out' `"  '`t_code'':"' _n
            file write `out' `"    count: `t_count'"' _n
            file write `out' `"    name: '`t_name''"' _n
        }
    }

    file close `out'

    *---------------------------------------------------------------------------
    * Copy to destination
    *---------------------------------------------------------------------------
    copy `out2' "`yaml_path'", replace

end
