*******************************************************************************
*! __wbod_search_aliases v1.0.0  25Apr2026
*! Populates source/topic alias and name lookup locals in the caller's scope.
*!
*! Used by __wbopendata_search and __wbopendata_search_cache to avoid
*! duplicating the 165-line lookup table across both backends.
*!
*! Returns (via c_local in caller's scope):
*!   - src_alias_<id>   short 6-char alias (e.g., src_alias_2 = "WDI")
*!   - src_name_<id>    full source name   (e.g., src_name_2  = "World Development Indicators")
*!   - topic_name_<id>  topic display name (e.g., topic_name_3 = "Economy & Growth")
*!
*! Source ID lookups assume integer-normalised IDs (no leading zeros).
*! Callers must apply real() / reassign before lookup; see __wbod_get_source_name v1.0.1.
*******************************************************************************

program define __wbod_search_aliases
    version 14

    *---------------------------------------------------------------------------
    * Source alias lookup (6-char max for table column)
    *---------------------------------------------------------------------------
    c_local src_alias_1   "DoingB"
    c_local src_alias_2   "WDI"
    c_local src_alias_3   "WGI"
    c_local src_alias_5   "SubMal"
    c_local src_alias_6   "IDS"
    c_local src_alias_11  "AfrDev"
    c_local src_alias_12  "EdStat"
    c_local src_alias_13  "EntSrv"
    c_local src_alias_14  "Gender"
    c_local src_alias_15  "GEM"
    c_local src_alias_16  "HNP"
    c_local src_alias_18  "IDA"
    c_local src_alias_19  "MDGs"
    c_local src_alias_20  "QPSD"
    c_local src_alias_22  "QEDSS"
    c_local src_alias_23  "QEDSG"
    c_local src_alias_25  "Jobs"
    c_local src_alias_27  "GEP"
    c_local src_alias_28  "Findex"
    c_local src_alias_29  "ASPIRE"
    c_local src_alias_30  "ExpDB"
    c_local src_alias_31  "CPIA"
    c_local src_alias_32  "FinDev"
    c_local src_alias_33  "G20FI"
    c_local src_alias_34  "GPE"
    c_local src_alias_35  "SE4All"
    c_local src_alias_37  "LAC"
    c_local src_alias_38  "SubPov"
    c_local src_alias_39  "HNPWQ"
    c_local src_alias_40  "PopEst"
    c_local src_alias_41  "CPSIN"
    c_local src_alias_43  "AdjNS"
    c_local src_alias_45  "INDO"
    c_local src_alias_46  "SDGs"
    c_local src_alias_50  "SubPop"
    c_local src_alias_54  "JEDH"
    c_local src_alias_57  "WDIArc"
    c_local src_alias_58  "UHC"
    c_local src_alias_59  "WltAcc"
    c_local src_alias_60  "EcFit"
    c_local src_alias_61  "PPPQ"
    c_local src_alias_62  "ICP11"
    c_local src_alias_63  "HCI"
    c_local src_alias_64  "WWBI"
    c_local src_alias_65  "HEFP"
    c_local src_alias_66  "LPI"
    c_local src_alias_67  "PEF11"
    c_local src_alias_68  "PEF16"
    c_local src_alias_69  "GFCPS"
    c_local src_alias_70  "EcFt2"
    c_local src_alias_71  "ICP05"
    c_local src_alias_73  "GFCPI"
    c_local src_alias_75  "ESG"
    c_local src_alias_76  "RPWS"
    c_local src_alias_77  "RPWR"
    c_local src_alias_78  "ICP17"
    c_local src_alias_79  "PEFGR"
    c_local src_alias_80  "GDLD"
    c_local src_alias_81  "IDSDS"
    c_local src_alias_82  "GPP"
    c_local src_alias_83  "SPI"
    c_local src_alias_84  "EdPol"
    c_local src_alias_85  "PEFSN"
    c_local src_alias_86  "JOIN"
    c_local src_alias_87  "CCDR"
    c_local src_alias_88  "FPN"
    c_local src_alias_89  "ID4D"
    c_local src_alias_90  "ICP21"
    c_local src_alias_91  "PEFCR"
    c_local src_alias_92  "DDH"
    c_local src_alias_93  "FPNA"

    *---------------------------------------------------------------------------
    * Source full names (for legend)
    *---------------------------------------------------------------------------
    c_local src_name_1   "Doing Business"
    c_local src_name_2   "World Development Indicators"
    c_local src_name_3   "Worldwide Governance Indicators"
    c_local src_name_5   "Subnational Malnutrition Database"
    c_local src_name_6   "International Debt Statistics"
    c_local src_name_11  "Africa Development Indicators"
    c_local src_name_12  "Education Statistics"
    c_local src_name_13  "Enterprise Surveys"
    c_local src_name_14  "Gender Statistics"
    c_local src_name_15  "Global Economic Monitor"
    c_local src_name_16  "Health Nutrition and Population"
    c_local src_name_18  "IDA Results Measurement System"
    c_local src_name_19  "Millennium Development Goals"
    c_local src_name_20  "Quarterly Public Sector Debt"
    c_local src_name_22  "QEDS SDDS"
    c_local src_name_23  "QEDS GDDS"
    c_local src_name_25  "Jobs"
    c_local src_name_27  "Global Economic Prospects"
    c_local src_name_28  "Global Findex"
    c_local src_name_29  "ASPIRE"
    c_local src_name_30  "Exporter Dynamics Database"
    c_local src_name_31  "Country Policy & Institutional Assessment"
    c_local src_name_32  "Global Financial Development"
    c_local src_name_33  "G20 Financial Inclusion"
    c_local src_name_34  "Global Partnership for Education"
    c_local src_name_35  "Sustainable Energy for All"
    c_local src_name_37  "LAC Equity Lab"
    c_local src_name_38  "Subnational Poverty"
    c_local src_name_39  "HNP by Wealth Quintile"
    c_local src_name_40  "Population Estimates & Projections"
    c_local src_name_41  "India Country Partnership Strategy"
    c_local src_name_43  "Adjusted Net Savings"
    c_local src_name_45  "Indonesia Database for Policy & Economic Research"
    c_local src_name_46  "Sustainable Development Goals"
    c_local src_name_50  "Subnational Population"
    c_local src_name_54  "Joint External Debt Hub"
    c_local src_name_57  "WDI Database Archives"
    c_local src_name_58  "Universal Health Coverage"
    c_local src_name_59  "Wealth Accounts"
    c_local src_name_60  "Economic Fitness"
    c_local src_name_61  "PPPs Regulatory Quality"
    c_local src_name_62  "ICP 2011"
    c_local src_name_63  "Human Capital Index"
    c_local src_name_64  "Worldwide Bureaucracy Indicators"
    c_local src_name_65  "Health Equity & Financial Protection"
    c_local src_name_66  "Logistics Performance Index"
    c_local src_name_67  "PEFA 2011"
    c_local src_name_68  "PEFA 2016"
    c_local src_name_69  "Global Financial Inclusion & Consumer Protection"
    c_local src_name_70  "Economic Fitness 2"
    c_local src_name_71  "ICP 2005"
    c_local src_name_73  "Global Financial Inclusion Survey (Internal)"
    c_local src_name_75  "ESG Data"
    c_local src_name_76  "Remittance Prices Worldwide (Sending)"
    c_local src_name_77  "Remittance Prices Worldwide (Receiving)"
    c_local src_name_78  "ICP 2017"
    c_local src_name_79  "PEFA GRPFM"
    c_local src_name_80  "Gender Disaggregated Labor Database"
    c_local src_name_81  "International Debt Statistics: DSSI"
    c_local src_name_82  "Global Public Procurement"
    c_local src_name_83  "Statistical Performance Indicators"
    c_local src_name_84  "Education Policy"
    c_local src_name_85  "PEFA 2021 SNG"
    c_local src_name_86  "Global Jobs Indicators Database"
    c_local src_name_87  "Country Climate and Development Report"
    c_local src_name_88  "Food Prices for Nutrition"
    c_local src_name_89  "ID4D Data"
    c_local src_name_90  "ICP 2021"
    c_local src_name_91  "PEFA CRPFM"
    c_local src_name_92  "Disability Data Hub"
    c_local src_name_93  "FPN Datahub Archive"

    *---------------------------------------------------------------------------
    * Topic name lookup (for legend)
    *---------------------------------------------------------------------------
    c_local topic_name_1  "Agric & Rural Dev"
    c_local topic_name_2  "Aid Effectiveness"
    c_local topic_name_3  "Economy & Growth"
    c_local topic_name_4  "Education"
    c_local topic_name_5  "Energy & Mining"
    c_local topic_name_6  "Environment"
    c_local topic_name_7  "Financial Sector"
    c_local topic_name_8  "Health"
    c_local topic_name_9  "Infrastructure"
    c_local topic_name_10 "Social Protection & Labor"
    c_local topic_name_11 "Poverty"
    c_local topic_name_12 "Private Sector"
    c_local topic_name_13 "Public Sector"
    c_local topic_name_14 "Science & Technology"
    c_local topic_name_15 "Social Development"
    c_local topic_name_16 "Urban Development"
    c_local topic_name_17 "Gender"
    c_local topic_name_18 "MDGs"
    c_local topic_name_19 "Climate Change"
    c_local topic_name_20 "External Debt"
    c_local topic_name_21 "Trade"
end
