*! _adminregionname < : >                 by João Pedro Azevedo
*                 auto generated and updated using _update_countrymetadata.ado 
  
  program define _adminregionname 
  
  
         gen adminregionname = ""  
         replace adminregionname = "South Asia"  if countrycode == "AFG"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "AGO"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "ALB"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "ARM"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "ASM"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "AZE"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "BDI"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "BEN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "BFA"  
         replace adminregionname = "South Asia"  if countrycode == "BGD"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "BGR"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "BIH"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "BLR"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "BLZ"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "BOL"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "BRA"  
         replace adminregionname = "South Asia"  if countrycode == "BTN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "BWA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "CAF"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "CHN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "CIV"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "CMR"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "COD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "COG"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "COL"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "COM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "CPV"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "CRI"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "CUB"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "DJI"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "DMA"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "DOM"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "DZA"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "ECU"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "EGY"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "ERI"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "ETH"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "FJI"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "FSM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "GAB"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "GEO"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "GHA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "GIN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "GMB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "GNB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "GNQ"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "GRD"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "GTM"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "GUY"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "HND"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "HTI"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "IDN"  
         replace adminregionname = "South Asia"  if countrycode == "IND"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "IRN"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "IRQ"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "JAM"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "JOR"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "KAZ"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "KEN"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "KGZ"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "KHM"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "KIR"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "LAO"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "LBN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "LBR"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "LBY"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "LCA"  
         replace adminregionname = "South Asia"  if countrycode == "LKA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "LSO"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "MAR"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "MDA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "MDG"  
         replace adminregionname = "South Asia"  if countrycode == "MDV"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "MEX"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "MHL"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "MKD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "MLI"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "MMR"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "MNE"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "MNG"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "MOZ"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "MRT"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "MUS"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "MWI"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "MYS"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "NAM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "NER"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "NGA"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "NIC"  
         replace adminregionname = "South Asia"  if countrycode == "NPL"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "NRU"  
         replace adminregionname = "South Asia"  if countrycode == "PAK"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "PER"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "PHL"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "PNG"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "PRK"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "PRY"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "PSE"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "ROU"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "RUS"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "RWA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "SDN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "SEN"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "SLB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "SLE"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "SLV"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "SOM"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "SRB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "SSD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "STP"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "SUR"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "SWZ"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "SYR"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "TCD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "TGO"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "THA"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "TJK"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "TKM"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "TLS"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "TON"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "TUN"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "TUR"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "TUV"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "TZA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high in"  if countrycode == "UGA"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "UKR"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "UZB"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "VCT"  
         replace adminregionname = "Latin America and Caribbean (exclud"  if countrycode == "VEN"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "VNM"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "VUT"  
         replace adminregionname = "East Asia and Pacific (excluding hi"  if countrycode == "WSM"  
         replace adminregionname = "Europe and Central Asia (excluding"  if countrycode == "XKX"  
         replace adminregionname = "Middle East and North Africa (exclu"  if countrycode == "YEM"  
  
  
  end 
