*! _countryname < : >                 by João Pedro Azevedo
*                 auto generated and updated using _update_countrymetadata.ado 
  
  program define _countryname 
  
  
         gen countryname = ""  
         replace countryname = "Aruba"  if countrycode == "ABW"  
         replace countryname = "Afghanistan"  if countrycode == "AFG"  
         replace countryname = "Africa"  if countrycode == "AFR"  
         replace countryname = "Angola"  if countrycode == "AGO"  
         replace countryname = "Albania"  if countrycode == "ALB"  
         replace countryname = "Andorra"  if countrycode == "AND"  
         replace countryname = "Andean Region"  if countrycode == "ANR"  
         replace countryname = "Arab World"  if countrycode == "ARB"  
         replace countryname = "United Arab Emirates"  if countrycode == "ARE"  
         replace countryname = "Argentina"  if countrycode == "ARG"  
         replace countryname = "Armenia"  if countrycode == "ARM"  
         replace countryname = "American Samoa"  if countrycode == "ASM"  
         replace countryname = "Antigua and Barbuda"  if countrycode == "ATG"  
         replace countryname = "Australia"  if countrycode == "AUS"  
         replace countryname = "Austria"  if countrycode == "AUT"  
         replace countryname = "Azerbaijan"  if countrycode == "AZE"  
         replace countryname = "Burundi"  if countrycode == "BDI"  
         replace countryname = "East Asia and Pacific (IBRD-only countries)"  if countrycode == "BEA"  
         replace countryname = "Europe and Central Asia (IBRD-only countries)"  if countrycode == "BEC"  
         replace countryname = "Belgium"  if countrycode == "BEL"  
         replace countryname = "Benin"  if countrycode == "BEN"  
         replace countryname = "Burkina Faso"  if countrycode == "BFA"  
         replace countryname = "Bangladesh"  if countrycode == "BGD"  
         replace countryname = "Bulgaria"  if countrycode == "BGR"  
         replace countryname = "IBRD countries classified as high income"  if countrycode == "BHI"  
         replace countryname = "Bahrain"  if countrycode == "BHR"  
         replace countryname = "Bahamas, The"  if countrycode == "BHS"  
         replace countryname = "Bosnia and Herzegovina"  if countrycode == "BIH"  
         replace countryname = "Latin America and the Caribbean (IBRD-only countries)"  if countrycode == "BLA"  
         replace countryname = "Belarus"  if countrycode == "BLR"  
         replace countryname = "Belize"  if countrycode == "BLZ"  
         replace countryname = "Middle East and North Africa (IBRD-only countries)"  if countrycode == "BMN"  
         replace countryname = "Bermuda"  if countrycode == "BMU"  
         replace countryname = "Bolivia"  if countrycode == "BOL"  
         replace countryname = "Brazil"  if countrycode == "BRA"  
         replace countryname = "Barbados"  if countrycode == "BRB"  
         replace countryname = "Brunei Darussalam"  if countrycode == "BRN"  
         replace countryname = "Sub-Saharan Africa (IBRD-only countries)"  if countrycode == "BSS"  
         replace countryname = "Bhutan"  if countrycode == "BTN"  
         replace countryname = "Botswana"  if countrycode == "BWA"  
         replace countryname = "Sub-Saharan Africa (IFC classification)"  if countrycode == "CAA"  
         replace countryname = "Central African Republic"  if countrycode == "CAF"  
         replace countryname = "Canada"  if countrycode == "CAN"  
         replace countryname = "East Asia and the Pacific (IFC classification)"  if countrycode == "CEA"  
         replace countryname = "Central Europe and the Baltics"  if countrycode == "CEB"  
         replace countryname = "Europe and Central Asia (IFC classification)"  if countrycode == "CEU"  
         replace countryname = "Switzerland"  if countrycode == "CHE"  
         replace countryname = "Channel Islands"  if countrycode == "CHI"  
         replace countryname = "Chile"  if countrycode == "CHL"  
         replace countryname = "China"  if countrycode == "CHN"  
         replace countryname = "Cote d'Ivoire"  if countrycode == "CIV"  
         replace countryname = "Latin America and the Caribbean (IFC classification)"  if countrycode == "CLA"  
         replace countryname = "Middle East and North Africa (IFC classification)"  if countrycode == "CME"  
         replace countryname = "Cameroon"  if countrycode == "CMR"  
         replace countryname = "Congo, Dem Rep"  if countrycode == "COD"  
         replace countryname = "Congo, Rep"  if countrycode == "COG"  
         replace countryname = "Colombia"  if countrycode == "COL"  
         replace countryname = "Comoros"  if countrycode == "COM"  
         replace countryname = "Cabo Verde"  if countrycode == "CPV"  
         replace countryname = "Costa Rica"  if countrycode == "CRI"  
         replace countryname = "South Asia (IFC classification)"  if countrycode == "CSA"  
         replace countryname = "Caribbean small states"  if countrycode == "CSS"  
         replace countryname = "Cuba"  if countrycode == "CUB"  
         replace countryname = "Curacao"  if countrycode == "CUW"  
         replace countryname = "Cayman Islands"  if countrycode == "CYM"  
         replace countryname = "Cyprus"  if countrycode == "CYP"  
         replace countryname = "Czech Republic"  if countrycode == "CZE"  
         replace countryname = "East Asia and Pacific (IDA-eligible countries)"  if countrycode == "DEA"  
         replace countryname = "Europe and Central Asia (IDA-eligible countries)"  if countrycode == "DEC"  
         replace countryname = "Germany"  if countrycode == "DEU"  
         replace countryname = "IDA countries classified as Fragile Situations"  if countrycode == "DFS"  
         replace countryname = "Djibouti"  if countrycode == "DJI"  
         replace countryname = "Latin America and the Caribbean (IDA-eligible countries)"  if countrycode == "DLA"  
         replace countryname = "Dominica"  if countrycode == "DMA"  
         replace countryname = "Middle East and North Africa (IDA-eligible countries)"  if countrycode == "DMN"  
         replace countryname = "IDA countries not classified as Fragile Situations"  if countrycode == "DNF"  
         replace countryname = "Denmark"  if countrycode == "DNK"  
         replace countryname = "IDA countries in Sub-Saharan Africa not classified as fragile situations"  if countrycode == "DNS"  
         replace countryname = "Dominican Republic"  if countrycode == "DOM"  
         replace countryname = "South Asia (IDA-eligible countries)"  if countrycode == "DSA"  
         replace countryname = "IDA countries in Sub-Saharan Africa classified as fragile situations"  if countrycode == "DSF"  
         replace countryname = "Sub-Saharan Africa (IDA-eligible countries)"  if countrycode == "DSS"  
         replace countryname = "IDA total, excluding Sub-Saharan Africa"  if countrycode == "DXS"  
         replace countryname = "Algeria"  if countrycode == "DZA"  
         replace countryname = "East Asia and Pacific (excluding high income)"  if countrycode == "EAP"  
         replace countryname = "Early-demographic dividend"  if countrycode == "EAR"  
         replace countryname = "East Asia and Pacific"  if countrycode == "EAS"  
         replace countryname = "Europe and Central Asia (excluding high income)"  if countrycode == "ECA"  
         replace countryname = "Europe and Central Asia"  if countrycode == "ECS"  
         replace countryname = "Ecuador"  if countrycode == "ECU"  
         replace countryname = "Egypt, Arab Rep"  if countrycode == "EGY"  
         replace countryname = "Euro area"  if countrycode == "EMU"  
         replace countryname = "Eritrea"  if countrycode == "ERI"  
         replace countryname = "Spain"  if countrycode == "ESP"  
         replace countryname = "Estonia"  if countrycode == "EST"  
         replace countryname = "Ethiopia"  if countrycode == "ETH"  
         replace countryname = "European Union"  if countrycode == "EUU"  
         replace countryname = "Fragile and conflict affected situations"  if countrycode == "FCS"  
         replace countryname = "Finland"  if countrycode == "FIN"  
         replace countryname = "Fiji"  if countrycode == "FJI"  
         replace countryname = "France"  if countrycode == "FRA"  
         replace countryname = "Faroe Islands"  if countrycode == "FRO"  
         replace countryname = "Micronesia, Fed Sts"  if countrycode == "FSM"  
         replace countryname = "IDA countries classified as fragile situations, excluding Sub-Saharan Africa"  if countrycode == "FXS"  
         replace countryname = "Gabon"  if countrycode == "GAB"  
         replace countryname = "United Kingdom"  if countrycode == "GBR"  
         replace countryname = "Georgia"  if countrycode == "GEO"  
         replace countryname = "Ghana"  if countrycode == "GHA"  
         replace countryname = "Gibraltar"  if countrycode == "GIB"  
         replace countryname = "Guinea"  if countrycode == "GIN"  
         replace countryname = "Gambia, The"  if countrycode == "GMB"  
         replace countryname = "Guinea-Bissau"  if countrycode == "GNB"  
         replace countryname = "Equatorial Guinea"  if countrycode == "GNQ"  
         replace countryname = "Greece"  if countrycode == "GRC"  
         replace countryname = "Grenada"  if countrycode == "GRD"  
         replace countryname = "Greenland"  if countrycode == "GRL"  
         replace countryname = "Guatemala"  if countrycode == "GTM"  
         replace countryname = "Guam"  if countrycode == "GUM"  
         replace countryname = "Guyana"  if countrycode == "GUY"  
         replace countryname = "High income"  if countrycode == "HIC"  
         replace countryname = "Hong Kong SAR, China"  if countrycode == "HKG"  
         replace countryname = "Honduras"  if countrycode == "HND"  
         replace countryname = "Heavily indebted poor countries (HIPC)"  if countrycode == "HPC"  
         replace countryname = "Croatia"  if countrycode == "HRV"  
         replace countryname = "Haiti"  if countrycode == "HTI"  
         replace countryname = "Hungary"  if countrycode == "HUN"  
         replace countryname = "IBRD, including blend"  if countrycode == "IBB"  
         replace countryname = "IBRD only"  if countrycode == "IBD"  
         replace countryname = "IDA and IBRD total"  if countrycode == "IBT"  
         replace countryname = "IDA total"  if countrycode == "IDA"  
         replace countryname = "IDA blend"  if countrycode == "IDB"  
         replace countryname = "Indonesia"  if countrycode == "IDN"  
         replace countryname = "IDA only"  if countrycode == "IDX"  
         replace countryname = "Isle of Man"  if countrycode == "IMN"  
         replace countryname = "India"  if countrycode == "IND"  
         replace countryname = "Not classified"  if countrycode == "INX"  
         replace countryname = "Ireland"  if countrycode == "IRL"  
         replace countryname = "Iran, Islamic Rep"  if countrycode == "IRN"  
         replace countryname = "Iraq"  if countrycode == "IRQ"  
         replace countryname = "Iceland"  if countrycode == "ISL"  
         replace countryname = "Israel"  if countrycode == "ISR"  
         replace countryname = "Italy"  if countrycode == "ITA"  
         replace countryname = "Jamaica"  if countrycode == "JAM"  
         replace countryname = "Jordan"  if countrycode == "JOR"  
         replace countryname = "Japan"  if countrycode == "JPN"  
         replace countryname = "Kazakhstan"  if countrycode == "KAZ"  
         replace countryname = "Kenya"  if countrycode == "KEN"  
         replace countryname = "Kyrgyz Republic"  if countrycode == "KGZ"  
         replace countryname = "Cambodia"  if countrycode == "KHM"  
         replace countryname = "Kiribati"  if countrycode == "KIR"  
         replace countryname = "St Kitts and Nevis"  if countrycode == "KNA"  
         replace countryname = "Korea, Rep"  if countrycode == "KOR"  
         replace countryname = "Kuwait"  if countrycode == "KWT"  
         replace countryname = "Latin America and Caribbean (excluding high income)"  if countrycode == "LAC"  
         replace countryname = "Lao PDR"  if countrycode == "LAO"  
         replace countryname = "Lebanon"  if countrycode == "LBN"  
         replace countryname = "Liberia"  if countrycode == "LBR"  
         replace countryname = "Libya"  if countrycode == "LBY"  
         replace countryname = "St Lucia"  if countrycode == "LCA"  
         replace countryname = "Latin America and Caribbean"  if countrycode == "LCN"  
         replace countryname = "Latin America and the Caribbean"  if countrycode == "LCR"  
         replace countryname = "Least developed countries: UN classification"  if countrycode == "LDC"  
         replace countryname = "Low income"  if countrycode == "LIC"  
         replace countryname = "Liechtenstein"  if countrycode == "LIE"  
         replace countryname = "Sri Lanka"  if countrycode == "LKA"  
         replace countryname = "Lower middle income"  if countrycode == "LMC"  
         replace countryname = "Low and middle income"  if countrycode == "LMY"  
         replace countryname = "Lesotho"  if countrycode == "LSO"  
         replace countryname = "Late-demographic dividend"  if countrycode == "LTE"  
         replace countryname = "Lithuania"  if countrycode == "LTU"  
         replace countryname = "Luxembourg"  if countrycode == "LUX"  
         replace countryname = "Latvia"  if countrycode == "LVA"  
         replace countryname = "Macao SAR, China"  if countrycode == "MAC"  
         replace countryname = "St Martin (French part)"  if countrycode == "MAF"  
         replace countryname = "Morocco"  if countrycode == "MAR"  
         replace countryname = "Central America"  if countrycode == "MCA"  
         replace countryname = "Monaco"  if countrycode == "MCO"  
         replace countryname = "Moldova"  if countrycode == "MDA"  
         replace countryname = "Middle East (developing only)"  if countrycode == "MDE"  
         replace countryname = "Madagascar"  if countrycode == "MDG"  
         replace countryname = "Maldives"  if countrycode == "MDV"  
         replace countryname = "Middle East and North Africa"  if countrycode == "MEA"  
         replace countryname = "Mexico"  if countrycode == "MEX"  
         replace countryname = "Marshall Islands"  if countrycode == "MHL"  
         replace countryname = "Middle income"  if countrycode == "MIC"  
         replace countryname = "Macedonia, FYR"  if countrycode == "MKD"  
         replace countryname = "Mali"  if countrycode == "MLI"  
         replace countryname = "Malta"  if countrycode == "MLT"  
         replace countryname = "Myanmar"  if countrycode == "MMR"  
         replace countryname = "Middle East and North Africa (excluding high income)"  if countrycode == "MNA"  
         replace countryname = "Montenegro"  if countrycode == "MNE"  
         replace countryname = "Mongolia"  if countrycode == "MNG"  
         replace countryname = "Northern Mariana Islands"  if countrycode == "MNP"  
         replace countryname = "Mozambique"  if countrycode == "MOZ"  
         replace countryname = "Mauritania"  if countrycode == "MRT"  
         replace countryname = "Mauritius"  if countrycode == "MUS"  
         replace countryname = "Malawi"  if countrycode == "MWI"  
         replace countryname = "Malaysia"  if countrycode == "MYS"  
         replace countryname = "North America"  if countrycode == "NAC"  
         replace countryname = "North Africa"  if countrycode == "NAF"  
         replace countryname = "Namibia"  if countrycode == "NAM"  
         replace countryname = "New Caledonia"  if countrycode == "NCL"  
         replace countryname = "Niger"  if countrycode == "NER"  
         replace countryname = "Nigeria"  if countrycode == "NGA"  
         replace countryname = "Nicaragua"  if countrycode == "NIC"  
         replace countryname = "Netherlands"  if countrycode == "NLD"  
         replace countryname = "Non-resource rich Sub-Saharan Africa countries, of which landlocked"  if countrycode == "NLS"  
         replace countryname = "Norway"  if countrycode == "NOR"  
         replace countryname = "Nepal"  if countrycode == "NPL"  
         replace countryname = "Non-resource rich Sub-Saharan Africa countries"  if countrycode == "NRS"  
         replace countryname = "Nauru"  if countrycode == "NRU"  
         replace countryname = "IDA countries not classified as fragile situations, excluding Sub-Saharan Africa"  if countrycode == "NXS"  
         replace countryname = "New Zealand"  if countrycode == "NZL"  
         replace countryname = "OECD members"  if countrycode == "OED"  
         replace countryname = "Oman"  if countrycode == "OMN"  
         replace countryname = "Other small states"  if countrycode == "OSS"  
         replace countryname = "Pakistan"  if countrycode == "PAK"  
         replace countryname = "Panama"  if countrycode == "PAN"  
         replace countryname = "Peru"  if countrycode == "PER"  
         replace countryname = "Philippines"  if countrycode == "PHL"  
         replace countryname = "Palau"  if countrycode == "PLW"  
         replace countryname = "Papua New Guinea"  if countrycode == "PNG"  
         replace countryname = "Poland"  if countrycode == "POL"  
         replace countryname = "Pre-demographic dividend"  if countrycode == "PRE"  
         replace countryname = "Puerto Rico"  if countrycode == "PRI"  
         replace countryname = "Korea, Dem People’s Rep"  if countrycode == "PRK"  
         replace countryname = "Portugal"  if countrycode == "PRT"  
         replace countryname = "Paraguay"  if countrycode == "PRY"  
         replace countryname = "West Bank and Gaza"  if countrycode == "PSE"  
         replace countryname = "Pacific island small states"  if countrycode == "PSS"  
         replace countryname = "Post-demographic dividend"  if countrycode == "PST"  
         replace countryname = "French Polynesia"  if countrycode == "PYF"  
         replace countryname = "Qatar"  if countrycode == "QAT"  
         replace countryname = "Romania"  if countrycode == "ROU"  
         replace countryname = "Resource rich Sub-Saharan Africa countries"  if countrycode == "RRS"  
         replace countryname = "Resource rich Sub-Saharan Africa countries, of which oil exporters"  if countrycode == "RSO"  
         replace countryname = "Russian Federation"  if countrycode == "RUS"  
         replace countryname = "Rwanda"  if countrycode == "RWA"  
         replace countryname = "South Asia"  if countrycode == "SAS"  
         replace countryname = "Saudi Arabia"  if countrycode == "SAU"  
         replace countryname = "Southern Cone"  if countrycode == "SCE"  
         replace countryname = "Sudan"  if countrycode == "SDN"  
         replace countryname = "Senegal"  if countrycode == "SEN"  
         replace countryname = "Singapore"  if countrycode == "SGP"  
         replace countryname = "Solomon Islands"  if countrycode == "SLB"  
         replace countryname = "Sierra Leone"  if countrycode == "SLE"  
         replace countryname = "El Salvador"  if countrycode == "SLV"  
         replace countryname = "San Marino"  if countrycode == "SMR"  
         replace countryname = "Somalia"  if countrycode == "SOM"  
         replace countryname = "Serbia"  if countrycode == "SRB"  
         replace countryname = "Sub-Saharan Africa (excluding high income)"  if countrycode == "SSA"  
         replace countryname = "South Sudan"  if countrycode == "SSD"  
         replace countryname = "Sub-Saharan Africa"  if countrycode == "SSF"  
         replace countryname = "Small states"  if countrycode == "SST"  
         replace countryname = "Sao Tome and Principe"  if countrycode == "STP"  
         replace countryname = "Suriname"  if countrycode == "SUR"  
         replace countryname = "Slovak Republic"  if countrycode == "SVK"  
         replace countryname = "Slovenia"  if countrycode == "SVN"  
         replace countryname = "Sweden"  if countrycode == "SWE"  
         replace countryname = "Eswatini"  if countrycode == "SWZ"  
         replace countryname = "Sint Maarten (Dutch part)"  if countrycode == "SXM"  
         replace countryname = "Sub-Saharan Africa excluding South Africa"  if countrycode == "SXZ"  
         replace countryname = "Seychelles"  if countrycode == "SYC"  
         replace countryname = "Syrian Arab Republic"  if countrycode == "SYR"  
         replace countryname = "Turks and Caicos Islands"  if countrycode == "TCA"  
         replace countryname = "Chad"  if countrycode == "TCD"  
         replace countryname = "East Asia and Pacific (IDA and IBRD countries)"  if countrycode == "TEA"  
         replace countryname = "Europe and Central Asia (IDA and IBRD countries)"  if countrycode == "TEC"  
         replace countryname = "Togo"  if countrycode == "TGO"  
         replace countryname = "Thailand"  if countrycode == "THA"  
         replace countryname = "Tajikistan"  if countrycode == "TJK"  
         replace countryname = "Turkmenistan"  if countrycode == "TKM"  
         replace countryname = "Latin America and the Caribbean (IDA and IBRD countries)"  if countrycode == "TLA"  
         replace countryname = "Timor-Leste"  if countrycode == "TLS"  
         replace countryname = "Middle East and North Africa (IDA and IBRD countries)"  if countrycode == "TMN"  
         replace countryname = "Tonga"  if countrycode == "TON"  
         replace countryname = "South Asia (IDA and IBRD)"  if countrycode == "TSA"  
         replace countryname = "Sub-Saharan Africa (IDA and IBRD countries)"  if countrycode == "TSS"  
         replace countryname = "Trinidad and Tobago"  if countrycode == "TTO"  
         replace countryname = "Tunisia"  if countrycode == "TUN"  
         replace countryname = "Turkey"  if countrycode == "TUR"  
         replace countryname = "Tuvalu"  if countrycode == "TUV"  
         replace countryname = "Taiwan, China"  if countrycode == "TWN"  
         replace countryname = "Tanzania"  if countrycode == "TZA"  
         replace countryname = "Uganda"  if countrycode == "UGA"  
         replace countryname = "Ukraine"  if countrycode == "UKR"  
         replace countryname = "Upper middle income"  if countrycode == "UMC"  
         replace countryname = "Uruguay"  if countrycode == "URY"  
         replace countryname = "United States"  if countrycode == "USA"  
         replace countryname = "Uzbekistan"  if countrycode == "UZB"  
         replace countryname = "St Vincent and the Grenadines"  if countrycode == "VCT"  
         replace countryname = "Venezuela, RB"  if countrycode == "VEN"  
         replace countryname = "British Virgin Islands"  if countrycode == "VGB"  
         replace countryname = "Virgin Islands (US)"  if countrycode == "VIR"  
         replace countryname = "Vietnam"  if countrycode == "VNM"  
         replace countryname = "Vanuatu"  if countrycode == "VUT"  
         replace countryname = "World"  if countrycode == "WLD"  
         replace countryname = "Samoa"  if countrycode == "WSM"  
         replace countryname = "Kosovo"  if countrycode == "XKX"  
         replace countryname = "Sub-Saharan Africa excluding South Africa and Nigeria"  if countrycode == "XZN"  
         replace countryname = "Yemen, Rep"  if countrycode == "YEM"  
  
  
  end 
