*! _lendingtypename < : >                 by João Pedro Azevedo
*                 auto generated and updated using _update_countrymetadata.ado 
  
  program define _lendingtypename 
  
  
         gen lendingtypename = ""  
         replace lendingtypename = "Not classified"  if countrycode == "ABW"  
         replace lendingtypename = "IDA"  if countrycode == "AFG"  
         replace lendingtypename = "IBRD"  if countrycode == "AGO"  
         replace lendingtypename = "IBRD"  if countrycode == "ALB"  
         replace lendingtypename = "Not classified"  if countrycode == "AND"  
         replace lendingtypename = "Not classified"  if countrycode == "ARE"  
         replace lendingtypename = "IBRD"  if countrycode == "ARG"  
         replace lendingtypename = "IBRD"  if countrycode == "ARM"  
         replace lendingtypename = "Not classified"  if countrycode == "ASM"  
         replace lendingtypename = "IBRD"  if countrycode == "ATG"  
         replace lendingtypename = "Not classified"  if countrycode == "AUS"  
         replace lendingtypename = "Not classified"  if countrycode == "AUT"  
         replace lendingtypename = "IBRD"  if countrycode == "AZE"  
         replace lendingtypename = "IDA"  if countrycode == "BDI"  
         replace lendingtypename = "Not classified"  if countrycode == "BEL"  
         replace lendingtypename = "IDA"  if countrycode == "BEN"  
         replace lendingtypename = "IDA"  if countrycode == "BFA"  
         replace lendingtypename = "IDA"  if countrycode == "BGD"  
         replace lendingtypename = "IBRD"  if countrycode == "BGR"  
         replace lendingtypename = "Not classified"  if countrycode == "BHR"  
         replace lendingtypename = "Not classified"  if countrycode == "BHS"  
         replace lendingtypename = "IBRD"  if countrycode == "BIH"  
         replace lendingtypename = "IBRD"  if countrycode == "BLR"  
         replace lendingtypename = "IBRD"  if countrycode == "BLZ"  
         replace lendingtypename = "Not classified"  if countrycode == "BMU"  
         replace lendingtypename = "IBRD"  if countrycode == "BOL"  
         replace lendingtypename = "IBRD"  if countrycode == "BRA"  
         replace lendingtypename = "Not classified"  if countrycode == "BRB"  
         replace lendingtypename = "Not classified"  if countrycode == "BRN"  
         replace lendingtypename = "IDA"  if countrycode == "BTN"  
         replace lendingtypename = "IBRD"  if countrycode == "BWA"  
         replace lendingtypename = "IDA"  if countrycode == "CAF"  
         replace lendingtypename = "Not classified"  if countrycode == "CAN"  
         replace lendingtypename = "Not classified"  if countrycode == "CHE"  
         replace lendingtypename = "Not classified"  if countrycode == "CHI"  
         replace lendingtypename = "IBRD"  if countrycode == "CHL"  
         replace lendingtypename = "IBRD"  if countrycode == "CHN"  
         replace lendingtypename = "IDA"  if countrycode == "CIV"  
         replace lendingtypename = "Blend"  if countrycode == "CMR"  
         replace lendingtypename = "IDA"  if countrycode == "COD"  
         replace lendingtypename = "Blend"  if countrycode == "COG"  
         replace lendingtypename = "IBRD"  if countrycode == "COL"  
         replace lendingtypename = "IDA"  if countrycode == "COM"  
         replace lendingtypename = "Blend"  if countrycode == "CPV"  
         replace lendingtypename = "IBRD"  if countrycode == "CRI"  
         replace lendingtypename = "Not classified"  if countrycode == "CUB"  
         replace lendingtypename = "Not classified"  if countrycode == "CUW"  
         replace lendingtypename = "Not classified"  if countrycode == "CYM"  
         replace lendingtypename = "Not classified"  if countrycode == "CYP"  
         replace lendingtypename = "Not classified"  if countrycode == "CZE"  
         replace lendingtypename = "Not classified"  if countrycode == "DEU"  
         replace lendingtypename = "IDA"  if countrycode == "DJI"  
         replace lendingtypename = "Blend"  if countrycode == "DMA"  
         replace lendingtypename = "Not classified"  if countrycode == "DNK"  
         replace lendingtypename = "IBRD"  if countrycode == "DOM"  
         replace lendingtypename = "IBRD"  if countrycode == "DZA"  
         replace lendingtypename = "IBRD"  if countrycode == "ECU"  
         replace lendingtypename = "IBRD"  if countrycode == "EGY"  
         replace lendingtypename = "IDA"  if countrycode == "ERI"  
         replace lendingtypename = "Not classified"  if countrycode == "ESP"  
         replace lendingtypename = "Not classified"  if countrycode == "EST"  
         replace lendingtypename = "IDA"  if countrycode == "ETH"  
         replace lendingtypename = "Not classified"  if countrycode == "FIN"  
         replace lendingtypename = "IBRD"  if countrycode == "FJI"  
         replace lendingtypename = "Not classified"  if countrycode == "FRA"  
         replace lendingtypename = "Not classified"  if countrycode == "FRO"  
         replace lendingtypename = "IDA"  if countrycode == "FSM"  
         replace lendingtypename = "IBRD"  if countrycode == "GAB"  
         replace lendingtypename = "Not classified"  if countrycode == "GBR"  
         replace lendingtypename = "IBRD"  if countrycode == "GEO"  
         replace lendingtypename = "IDA"  if countrycode == "GHA"  
         replace lendingtypename = "Not classified"  if countrycode == "GIB"  
         replace lendingtypename = "IDA"  if countrycode == "GIN"  
         replace lendingtypename = "IDA"  if countrycode == "GMB"  
         replace lendingtypename = "IDA"  if countrycode == "GNB"  
         replace lendingtypename = "IBRD"  if countrycode == "GNQ"  
         replace lendingtypename = "Not classified"  if countrycode == "GRC"  
         replace lendingtypename = "Blend"  if countrycode == "GRD"  
         replace lendingtypename = "Not classified"  if countrycode == "GRL"  
         replace lendingtypename = "IBRD"  if countrycode == "GTM"  
         replace lendingtypename = "Not classified"  if countrycode == "GUM"  
         replace lendingtypename = "IDA"  if countrycode == "GUY"  
         replace lendingtypename = "Not classified"  if countrycode == "HKG"  
         replace lendingtypename = "IDA"  if countrycode == "HND"  
         replace lendingtypename = "IBRD"  if countrycode == "HRV"  
         replace lendingtypename = "IDA"  if countrycode == "HTI"  
         replace lendingtypename = "Not classified"  if countrycode == "HUN"  
         replace lendingtypename = "IBRD"  if countrycode == "IDN"  
         replace lendingtypename = "Not classified"  if countrycode == "IMN"  
         replace lendingtypename = "IBRD"  if countrycode == "IND"  
         replace lendingtypename = "Not classified"  if countrycode == "IRL"  
         replace lendingtypename = "IBRD"  if countrycode == "IRN"  
         replace lendingtypename = "IBRD"  if countrycode == "IRQ"  
         replace lendingtypename = "Not classified"  if countrycode == "ISL"  
         replace lendingtypename = "Not classified"  if countrycode == "ISR"  
         replace lendingtypename = "Not classified"  if countrycode == "ITA"  
         replace lendingtypename = "IBRD"  if countrycode == "JAM"  
         replace lendingtypename = "IBRD"  if countrycode == "JOR"  
         replace lendingtypename = "Not classified"  if countrycode == "JPN"  
         replace lendingtypename = "IBRD"  if countrycode == "KAZ"  
         replace lendingtypename = "Blend"  if countrycode == "KEN"  
         replace lendingtypename = "IDA"  if countrycode == "KGZ"  
         replace lendingtypename = "IDA"  if countrycode == "KHM"  
         replace lendingtypename = "IDA"  if countrycode == "KIR"  
         replace lendingtypename = "IBRD"  if countrycode == "KNA"  
         replace lendingtypename = "Not classified"  if countrycode == "KOR"  
         replace lendingtypename = "Not classified"  if countrycode == "KWT"  
         replace lendingtypename = "IDA"  if countrycode == "LAO"  
         replace lendingtypename = "IBRD"  if countrycode == "LBN"  
         replace lendingtypename = "IDA"  if countrycode == "LBR"  
         replace lendingtypename = "IBRD"  if countrycode == "LBY"  
         replace lendingtypename = "Blend"  if countrycode == "LCA"  
         replace lendingtypename = "Not classified"  if countrycode == "LIE"  
         replace lendingtypename = "IBRD"  if countrycode == "LKA"  
         replace lendingtypename = "IDA"  if countrycode == "LSO"  
         replace lendingtypename = "Not classified"  if countrycode == "LTU"  
         replace lendingtypename = "Not classified"  if countrycode == "LUX"  
         replace lendingtypename = "Not classified"  if countrycode == "LVA"  
         replace lendingtypename = "Not classified"  if countrycode == "MAC"  
         replace lendingtypename = "Not classified"  if countrycode == "MAF"  
         replace lendingtypename = "IBRD"  if countrycode == "MAR"  
         replace lendingtypename = "Not classified"  if countrycode == "MCO"  
         replace lendingtypename = "Blend"  if countrycode == "MDA"  
         replace lendingtypename = "IDA"  if countrycode == "MDG"  
         replace lendingtypename = "IDA"  if countrycode == "MDV"  
         replace lendingtypename = "IBRD"  if countrycode == "MEX"  
         replace lendingtypename = "IDA"  if countrycode == "MHL"  
         replace lendingtypename = "IBRD"  if countrycode == "MKD"  
         replace lendingtypename = "IDA"  if countrycode == "MLI"  
         replace lendingtypename = "Not classified"  if countrycode == "MLT"  
         replace lendingtypename = "IDA"  if countrycode == "MMR"  
         replace lendingtypename = "IBRD"  if countrycode == "MNE"  
         replace lendingtypename = "Blend"  if countrycode == "MNG"  
         replace lendingtypename = "Not classified"  if countrycode == "MNP"  
         replace lendingtypename = "IDA"  if countrycode == "MOZ"  
         replace lendingtypename = "IDA"  if countrycode == "MRT"  
         replace lendingtypename = "IBRD"  if countrycode == "MUS"  
         replace lendingtypename = "IDA"  if countrycode == "MWI"  
         replace lendingtypename = "IBRD"  if countrycode == "MYS"  
         replace lendingtypename = "IBRD"  if countrycode == "NAM"  
         replace lendingtypename = "Not classified"  if countrycode == "NCL"  
         replace lendingtypename = "IDA"  if countrycode == "NER"  
         replace lendingtypename = "Blend"  if countrycode == "NGA"  
         replace lendingtypename = "IDA"  if countrycode == "NIC"  
         replace lendingtypename = "Not classified"  if countrycode == "NLD"  
         replace lendingtypename = "Not classified"  if countrycode == "NOR"  
         replace lendingtypename = "IDA"  if countrycode == "NPL"  
         replace lendingtypename = "IBRD"  if countrycode == "NRU"  
         replace lendingtypename = "Not classified"  if countrycode == "NZL"  
         replace lendingtypename = "Not classified"  if countrycode == "OMN"  
         replace lendingtypename = "Blend"  if countrycode == "PAK"  
         replace lendingtypename = "IBRD"  if countrycode == "PAN"  
         replace lendingtypename = "IBRD"  if countrycode == "PER"  
         replace lendingtypename = "IBRD"  if countrycode == "PHL"  
         replace lendingtypename = "IBRD"  if countrycode == "PLW"  
         replace lendingtypename = "Blend"  if countrycode == "PNG"  
         replace lendingtypename = "IBRD"  if countrycode == "POL"  
         replace lendingtypename = "Not classified"  if countrycode == "PRI"  
         replace lendingtypename = "Not classified"  if countrycode == "PRK"  
         replace lendingtypename = "Not classified"  if countrycode == "PRT"  
         replace lendingtypename = "IBRD"  if countrycode == "PRY"  
         replace lendingtypename = "Not classified"  if countrycode == "PSE"  
         replace lendingtypename = "Not classified"  if countrycode == "PYF"  
         replace lendingtypename = "Not classified"  if countrycode == "QAT"  
         replace lendingtypename = "IBRD"  if countrycode == "ROU"  
         replace lendingtypename = "IBRD"  if countrycode == "RUS"  
         replace lendingtypename = "IDA"  if countrycode == "RWA"  
         replace lendingtypename = "Not classified"  if countrycode == "SAU"  
         replace lendingtypename = "IDA"  if countrycode == "SDN"  
         replace lendingtypename = "IDA"  if countrycode == "SEN"  
         replace lendingtypename = "Not classified"  if countrycode == "SGP"  
         replace lendingtypename = "IDA"  if countrycode == "SLB"  
         replace lendingtypename = "IDA"  if countrycode == "SLE"  
         replace lendingtypename = "IBRD"  if countrycode == "SLV"  
         replace lendingtypename = "Not classified"  if countrycode == "SMR"  
         replace lendingtypename = "IDA"  if countrycode == "SOM"  
         replace lendingtypename = "IBRD"  if countrycode == "SRB"  
         replace lendingtypename = "IDA"  if countrycode == "SSD"  
         replace lendingtypename = "IDA"  if countrycode == "STP"  
         replace lendingtypename = "IBRD"  if countrycode == "SUR"  
         replace lendingtypename = "Not classified"  if countrycode == "SVK"  
         replace lendingtypename = "Not classified"  if countrycode == "SVN"  
         replace lendingtypename = "Not classified"  if countrycode == "SWE"  
         replace lendingtypename = "IBRD"  if countrycode == "SWZ"  
         replace lendingtypename = "Not classified"  if countrycode == "SXM"  
         replace lendingtypename = "IBRD"  if countrycode == "SYC"  
         replace lendingtypename = "IDA"  if countrycode == "SYR"  
         replace lendingtypename = "Not classified"  if countrycode == "TCA"  
         replace lendingtypename = "IDA"  if countrycode == "TCD"  
         replace lendingtypename = "IDA"  if countrycode == "TGO"  
         replace lendingtypename = "IBRD"  if countrycode == "THA"  
         replace lendingtypename = "IDA"  if countrycode == "TJK"  
         replace lendingtypename = "IBRD"  if countrycode == "TKM"  
         replace lendingtypename = "Blend"  if countrycode == "TLS"  
         replace lendingtypename = "IDA"  if countrycode == "TON"  
         replace lendingtypename = "IBRD"  if countrycode == "TTO"  
         replace lendingtypename = "IBRD"  if countrycode == "TUN"  
         replace lendingtypename = "IBRD"  if countrycode == "TUR"  
         replace lendingtypename = "IDA"  if countrycode == "TUV"  
         replace lendingtypename = "Not classified"  if countrycode == "TWN"  
         replace lendingtypename = "IDA"  if countrycode == "TZA"  
         replace lendingtypename = "IDA"  if countrycode == "UGA"  
         replace lendingtypename = "IBRD"  if countrycode == "UKR"  
         replace lendingtypename = "IBRD"  if countrycode == "URY"  
         replace lendingtypename = "Not classified"  if countrycode == "USA"  
         replace lendingtypename = "Blend"  if countrycode == "UZB"  
         replace lendingtypename = "Blend"  if countrycode == "VCT"  
         replace lendingtypename = "IBRD"  if countrycode == "VEN"  
         replace lendingtypename = "Not classified"  if countrycode == "VGB"  
         replace lendingtypename = "Not classified"  if countrycode == "VIR"  
         replace lendingtypename = "IBRD"  if countrycode == "VNM"  
         replace lendingtypename = "IDA"  if countrycode == "VUT"  
         replace lendingtypename = "IDA"  if countrycode == "WSM"  
         replace lendingtypename = "IDA"  if countrycode == "XKX"  
         replace lendingtypename = "IDA"  if countrycode == "YEM"  
  
  
  end 
