*! _wbod_tmpfile2 <27 Oct 2019 : 20:24:57>                 by João Pedro Azevedo
*                 auto generated and updated using _update_countrymetadata.ado 
  
 program define _wbod_tmpfile2 
  
     syntax , match(varname) [  adminregion adminregion_iso2 adminregionname incomelevel incomelevel_iso2 incomelevelname  ] 
  
 ******************  Values: adminregion ****************** 
  
 qui if ("`adminregion'" == "adminregion") {      
  
         gen adminregion = ""  
         replace adminregion = "SAS"  if `match' == "AFG"  
         replace adminregion = "SSA"  if `match' == "AGO"  
         replace adminregion = "ECA"  if `match' == "ALB"  
         replace adminregion = "LAC"  if `match' == "ARG"  
         replace adminregion = "ECA"  if `match' == "ARM"  
         replace adminregion = "EAP"  if `match' == "ASM"  
         replace adminregion = "ECA"  if `match' == "AZE"  
         replace adminregion = "SSA"  if `match' == "BDI"  
         replace adminregion = "SSA"  if `match' == "BEN"  
         replace adminregion = "SSA"  if `match' == "BFA"  
         replace adminregion = "SAS"  if `match' == "BGD"  
         replace adminregion = "ECA"  if `match' == "BGR"  
         replace adminregion = "ECA"  if `match' == "BIH"  
         replace adminregion = "ECA"  if `match' == "BLR"  
         replace adminregion = "LAC"  if `match' == "BLZ"  
         replace adminregion = "LAC"  if `match' == "BOL"  
         replace adminregion = "LAC"  if `match' == "BRA"  
         replace adminregion = "SAS"  if `match' == "BTN"  
         replace adminregion = "SSA"  if `match' == "BWA"  
         replace adminregion = "SSA"  if `match' == "CAF"  
         replace adminregion = "EAP"  if `match' == "CHN"  
         replace adminregion = "SSA"  if `match' == "CIV"  
         replace adminregion = "SSA"  if `match' == "CMR"  
         replace adminregion = "SSA"  if `match' == "COD"  
         replace adminregion = "SSA"  if `match' == "COG"  
         replace adminregion = "LAC"  if `match' == "COL"  
         replace adminregion = "SSA"  if `match' == "COM"  
         replace adminregion = "SSA"  if `match' == "CPV"  
         replace adminregion = "LAC"  if `match' == "CRI"  
         replace adminregion = "LAC"  if `match' == "CUB"  
         replace adminregion = "MNA"  if `match' == "DJI"  
         replace adminregion = "LAC"  if `match' == "DMA"  
         replace adminregion = "LAC"  if `match' == "DOM"  
         replace adminregion = "MNA"  if `match' == "DZA"  
         replace adminregion = "LAC"  if `match' == "ECU"  
         replace adminregion = "MNA"  if `match' == "EGY"  
         replace adminregion = "SSA"  if `match' == "ERI"  
         replace adminregion = "SSA"  if `match' == "ETH"  
         replace adminregion = "EAP"  if `match' == "FJI"  
         replace adminregion = "EAP"  if `match' == "FSM"  
         replace adminregion = "SSA"  if `match' == "GAB"  
         replace adminregion = "ECA"  if `match' == "GEO"  
         replace adminregion = "SSA"  if `match' == "GHA"  
         replace adminregion = "SSA"  if `match' == "GIN"  
         replace adminregion = "SSA"  if `match' == "GMB"  
         replace adminregion = "SSA"  if `match' == "GNB"  
         replace adminregion = "SSA"  if `match' == "GNQ"  
         replace adminregion = "LAC"  if `match' == "GRD"  
         replace adminregion = "LAC"  if `match' == "GTM"  
         replace adminregion = "LAC"  if `match' == "GUY"  
         replace adminregion = "LAC"  if `match' == "HND"  
         replace adminregion = "LAC"  if `match' == "HTI"  
         replace adminregion = "EAP"  if `match' == "IDN"  
         replace adminregion = "SAS"  if `match' == "IND"  
         replace adminregion = "MNA"  if `match' == "IRN"  
         replace adminregion = "MNA"  if `match' == "IRQ"  
         replace adminregion = "LAC"  if `match' == "JAM"  
         replace adminregion = "MNA"  if `match' == "JOR"  
         replace adminregion = "ECA"  if `match' == "KAZ"  
         replace adminregion = "SSA"  if `match' == "KEN"  
         replace adminregion = "ECA"  if `match' == "KGZ"  
         replace adminregion = "EAP"  if `match' == "KHM"  
         replace adminregion = "EAP"  if `match' == "KIR"  
         replace adminregion = "EAP"  if `match' == "LAO"  
         replace adminregion = "MNA"  if `match' == "LBN"  
         replace adminregion = "SSA"  if `match' == "LBR"  
         replace adminregion = "MNA"  if `match' == "LBY"  
         replace adminregion = "LAC"  if `match' == "LCA"  
         replace adminregion = "SAS"  if `match' == "LKA"  
         replace adminregion = "SSA"  if `match' == "LSO"  
         replace adminregion = "MNA"  if `match' == "MAR"  
         replace adminregion = "ECA"  if `match' == "MDA"  
         replace adminregion = "SSA"  if `match' == "MDG"  
         replace adminregion = "SAS"  if `match' == "MDV"  
         replace adminregion = "LAC"  if `match' == "MEX"  
         replace adminregion = "EAP"  if `match' == "MHL"  
         replace adminregion = "ECA"  if `match' == "MKD"  
         replace adminregion = "SSA"  if `match' == "MLI"  
         replace adminregion = "EAP"  if `match' == "MMR"  
         replace adminregion = "ECA"  if `match' == "MNE"  
         replace adminregion = "EAP"  if `match' == "MNG"  
         replace adminregion = "SSA"  if `match' == "MOZ"  
         replace adminregion = "SSA"  if `match' == "MRT"  
         replace adminregion = "SSA"  if `match' == "MUS"  
         replace adminregion = "SSA"  if `match' == "MWI"  
         replace adminregion = "EAP"  if `match' == "MYS"  
         replace adminregion = "SSA"  if `match' == "NAM"  
         replace adminregion = "SSA"  if `match' == "NER"  
         replace adminregion = "SSA"  if `match' == "NGA"  
         replace adminregion = "LAC"  if `match' == "NIC"  
         replace adminregion = "SAS"  if `match' == "NPL"  
         replace adminregion = "EAP"  if `match' == "NRU"  
         replace adminregion = "SAS"  if `match' == "PAK"  
         replace adminregion = "LAC"  if `match' == "PER"  
         replace adminregion = "EAP"  if `match' == "PHL"  
         replace adminregion = "EAP"  if `match' == "PNG"  
         replace adminregion = "EAP"  if `match' == "PRK"  
         replace adminregion = "LAC"  if `match' == "PRY"  
         replace adminregion = "MNA"  if `match' == "PSE"  
         replace adminregion = "ECA"  if `match' == "ROU"  
         replace adminregion = "ECA"  if `match' == "RUS"  
         replace adminregion = "SSA"  if `match' == "RWA"  
         replace adminregion = "SSA"  if `match' == "SDN"  
         replace adminregion = "SSA"  if `match' == "SEN"  
         replace adminregion = "EAP"  if `match' == "SLB"  
         replace adminregion = "SSA"  if `match' == "SLE"  
         replace adminregion = "LAC"  if `match' == "SLV"  
         replace adminregion = "SSA"  if `match' == "SOM"  
         replace adminregion = "ECA"  if `match' == "SRB"  
         replace adminregion = "SSA"  if `match' == "SSD"  
         replace adminregion = "SSA"  if `match' == "STP"  
         replace adminregion = "LAC"  if `match' == "SUR"  
         replace adminregion = "SSA"  if `match' == "SWZ"  
         replace adminregion = "MNA"  if `match' == "SYR"  
         replace adminregion = "SSA"  if `match' == "TCD"  
         replace adminregion = "SSA"  if `match' == "TGO"  
         replace adminregion = "EAP"  if `match' == "THA"  
         replace adminregion = "ECA"  if `match' == "TJK"  
         replace adminregion = "ECA"  if `match' == "TKM"  
         replace adminregion = "EAP"  if `match' == "TLS"  
         replace adminregion = "EAP"  if `match' == "TON"  
         replace adminregion = "MNA"  if `match' == "TUN"  
         replace adminregion = "ECA"  if `match' == "TUR"  
         replace adminregion = "EAP"  if `match' == "TUV"  
         replace adminregion = "SSA"  if `match' == "TZA"  
         replace adminregion = "SSA"  if `match' == "UGA"  
         replace adminregion = "ECA"  if `match' == "UKR"  
         replace adminregion = "ECA"  if `match' == "UZB"  
         replace adminregion = "LAC"  if `match' == "VCT"  
         replace adminregion = "LAC"  if `match' == "VEN"  
         replace adminregion = "EAP"  if `match' == "VNM"  
         replace adminregion = "EAP"  if `match' == "VUT"  
         replace adminregion = "EAP"  if `match' == "WSM"  
         replace adminregion = "ECA"  if `match' == "XKX"  
         replace adminregion = "MNA"  if `match' == "YEM"  
         replace adminregion = "SSA"  if `match' == "ZAF"  
         replace adminregion = "SSA"  if `match' == "ZMB"  
  
******************  Lable: adminregion ******************
  
     lab var adminregion                 "Administrative Region Code" 
 }        
  
 ****************************************************** 
  
 ******************  Values: adminregion_iso2 ****************** 
  
 qui if ("`adminregion_iso2'" == "adminregion_iso2") {      
  
         gen adminregion_iso2 = ""  
         replace adminregion_iso2 = "8S"  if `match' == "AFG"  
         replace adminregion_iso2 = "ZF"  if `match' == "AGO"  
         replace adminregion_iso2 = "7E"  if `match' == "ALB"  
         replace adminregion_iso2 = "XJ"  if `match' == "ARG"  
         replace adminregion_iso2 = "7E"  if `match' == "ARM"  
         replace adminregion_iso2 = "4E"  if `match' == "ASM"  
         replace adminregion_iso2 = "7E"  if `match' == "AZE"  
         replace adminregion_iso2 = "ZF"  if `match' == "BDI"  
         replace adminregion_iso2 = "ZF"  if `match' == "BEN"  
         replace adminregion_iso2 = "ZF"  if `match' == "BFA"  
         replace adminregion_iso2 = "8S"  if `match' == "BGD"  
         replace adminregion_iso2 = "7E"  if `match' == "BGR"  
         replace adminregion_iso2 = "7E"  if `match' == "BIH"  
         replace adminregion_iso2 = "7E"  if `match' == "BLR"  
         replace adminregion_iso2 = "XJ"  if `match' == "BLZ"  
         replace adminregion_iso2 = "XJ"  if `match' == "BOL"  
         replace adminregion_iso2 = "XJ"  if `match' == "BRA"  
         replace adminregion_iso2 = "8S"  if `match' == "BTN"  
         replace adminregion_iso2 = "ZF"  if `match' == "BWA"  
         replace adminregion_iso2 = "ZF"  if `match' == "CAF"  
         replace adminregion_iso2 = "4E"  if `match' == "CHN"  
         replace adminregion_iso2 = "ZF"  if `match' == "CIV"  
         replace adminregion_iso2 = "ZF"  if `match' == "CMR"  
         replace adminregion_iso2 = "ZF"  if `match' == "COD"  
         replace adminregion_iso2 = "ZF"  if `match' == "COG"  
         replace adminregion_iso2 = "XJ"  if `match' == "COL"  
         replace adminregion_iso2 = "ZF"  if `match' == "COM"  
         replace adminregion_iso2 = "ZF"  if `match' == "CPV"  
         replace adminregion_iso2 = "XJ"  if `match' == "CRI"  
         replace adminregion_iso2 = "XJ"  if `match' == "CUB"  
         replace adminregion_iso2 = "XQ"  if `match' == "DJI"  
         replace adminregion_iso2 = "XJ"  if `match' == "DMA"  
         replace adminregion_iso2 = "XJ"  if `match' == "DOM"  
         replace adminregion_iso2 = "XQ"  if `match' == "DZA"  
         replace adminregion_iso2 = "XJ"  if `match' == "ECU"  
         replace adminregion_iso2 = "XQ"  if `match' == "EGY"  
         replace adminregion_iso2 = "ZF"  if `match' == "ERI"  
         replace adminregion_iso2 = "ZF"  if `match' == "ETH"  
         replace adminregion_iso2 = "4E"  if `match' == "FJI"  
         replace adminregion_iso2 = "4E"  if `match' == "FSM"  
         replace adminregion_iso2 = "ZF"  if `match' == "GAB"  
         replace adminregion_iso2 = "7E"  if `match' == "GEO"  
         replace adminregion_iso2 = "ZF"  if `match' == "GHA"  
         replace adminregion_iso2 = "ZF"  if `match' == "GIN"  
         replace adminregion_iso2 = "ZF"  if `match' == "GMB"  
         replace adminregion_iso2 = "ZF"  if `match' == "GNB"  
         replace adminregion_iso2 = "ZF"  if `match' == "GNQ"  
         replace adminregion_iso2 = "XJ"  if `match' == "GRD"  
         replace adminregion_iso2 = "XJ"  if `match' == "GTM"  
         replace adminregion_iso2 = "XJ"  if `match' == "GUY"  
         replace adminregion_iso2 = "XJ"  if `match' == "HND"  
         replace adminregion_iso2 = "XJ"  if `match' == "HTI"  
         replace adminregion_iso2 = "4E"  if `match' == "IDN"  
         replace adminregion_iso2 = "8S"  if `match' == "IND"  
         replace adminregion_iso2 = "XQ"  if `match' == "IRN"  
         replace adminregion_iso2 = "XQ"  if `match' == "IRQ"  
         replace adminregion_iso2 = "XJ"  if `match' == "JAM"  
         replace adminregion_iso2 = "XQ"  if `match' == "JOR"  
         replace adminregion_iso2 = "7E"  if `match' == "KAZ"  
         replace adminregion_iso2 = "ZF"  if `match' == "KEN"  
         replace adminregion_iso2 = "7E"  if `match' == "KGZ"  
         replace adminregion_iso2 = "4E"  if `match' == "KHM"  
         replace adminregion_iso2 = "4E"  if `match' == "KIR"  
         replace adminregion_iso2 = "4E"  if `match' == "LAO"  
         replace adminregion_iso2 = "XQ"  if `match' == "LBN"  
         replace adminregion_iso2 = "ZF"  if `match' == "LBR"  
         replace adminregion_iso2 = "XQ"  if `match' == "LBY"  
         replace adminregion_iso2 = "XJ"  if `match' == "LCA"  
         replace adminregion_iso2 = "8S"  if `match' == "LKA"  
         replace adminregion_iso2 = "ZF"  if `match' == "LSO"  
         replace adminregion_iso2 = "XQ"  if `match' == "MAR"  
         replace adminregion_iso2 = "7E"  if `match' == "MDA"  
         replace adminregion_iso2 = "ZF"  if `match' == "MDG"  
         replace adminregion_iso2 = "8S"  if `match' == "MDV"  
         replace adminregion_iso2 = "XJ"  if `match' == "MEX"  
         replace adminregion_iso2 = "4E"  if `match' == "MHL"  
         replace adminregion_iso2 = "7E"  if `match' == "MKD"  
         replace adminregion_iso2 = "ZF"  if `match' == "MLI"  
         replace adminregion_iso2 = "4E"  if `match' == "MMR"  
         replace adminregion_iso2 = "7E"  if `match' == "MNE"  
         replace adminregion_iso2 = "4E"  if `match' == "MNG"  
         replace adminregion_iso2 = "ZF"  if `match' == "MOZ"  
         replace adminregion_iso2 = "ZF"  if `match' == "MRT"  
         replace adminregion_iso2 = "ZF"  if `match' == "MUS"  
         replace adminregion_iso2 = "ZF"  if `match' == "MWI"  
         replace adminregion_iso2 = "4E"  if `match' == "MYS"  
         replace adminregion_iso2 = "ZF"  if `match' == "NAM"  
         replace adminregion_iso2 = "ZF"  if `match' == "NER"  
         replace adminregion_iso2 = "ZF"  if `match' == "NGA"  
         replace adminregion_iso2 = "XJ"  if `match' == "NIC"  
         replace adminregion_iso2 = "8S"  if `match' == "NPL"  
         replace adminregion_iso2 = "4E"  if `match' == "NRU"  
         replace adminregion_iso2 = "8S"  if `match' == "PAK"  
         replace adminregion_iso2 = "XJ"  if `match' == "PER"  
         replace adminregion_iso2 = "4E"  if `match' == "PHL"  
         replace adminregion_iso2 = "4E"  if `match' == "PNG"  
         replace adminregion_iso2 = "4E"  if `match' == "PRK"  
         replace adminregion_iso2 = "XJ"  if `match' == "PRY"  
         replace adminregion_iso2 = "XQ"  if `match' == "PSE"  
         replace adminregion_iso2 = "7E"  if `match' == "ROU"  
         replace adminregion_iso2 = "7E"  if `match' == "RUS"  
         replace adminregion_iso2 = "ZF"  if `match' == "RWA"  
         replace adminregion_iso2 = "ZF"  if `match' == "SDN"  
         replace adminregion_iso2 = "ZF"  if `match' == "SEN"  
         replace adminregion_iso2 = "4E"  if `match' == "SLB"  
         replace adminregion_iso2 = "ZF"  if `match' == "SLE"  
         replace adminregion_iso2 = "XJ"  if `match' == "SLV"  
         replace adminregion_iso2 = "ZF"  if `match' == "SOM"  
         replace adminregion_iso2 = "7E"  if `match' == "SRB"  
         replace adminregion_iso2 = "ZF"  if `match' == "SSD"  
         replace adminregion_iso2 = "ZF"  if `match' == "STP"  
         replace adminregion_iso2 = "XJ"  if `match' == "SUR"  
         replace adminregion_iso2 = "ZF"  if `match' == "SWZ"  
         replace adminregion_iso2 = "XQ"  if `match' == "SYR"  
         replace adminregion_iso2 = "ZF"  if `match' == "TCD"  
         replace adminregion_iso2 = "ZF"  if `match' == "TGO"  
         replace adminregion_iso2 = "4E"  if `match' == "THA"  
         replace adminregion_iso2 = "7E"  if `match' == "TJK"  
         replace adminregion_iso2 = "7E"  if `match' == "TKM"  
         replace adminregion_iso2 = "4E"  if `match' == "TLS"  
         replace adminregion_iso2 = "4E"  if `match' == "TON"  
         replace adminregion_iso2 = "XQ"  if `match' == "TUN"  
         replace adminregion_iso2 = "7E"  if `match' == "TUR"  
         replace adminregion_iso2 = "4E"  if `match' == "TUV"  
         replace adminregion_iso2 = "ZF"  if `match' == "TZA"  
         replace adminregion_iso2 = "ZF"  if `match' == "UGA"  
         replace adminregion_iso2 = "7E"  if `match' == "UKR"  
         replace adminregion_iso2 = "7E"  if `match' == "UZB"  
         replace adminregion_iso2 = "XJ"  if `match' == "VCT"  
         replace adminregion_iso2 = "XJ"  if `match' == "VEN"  
         replace adminregion_iso2 = "4E"  if `match' == "VNM"  
         replace adminregion_iso2 = "4E"  if `match' == "VUT"  
         replace adminregion_iso2 = "4E"  if `match' == "WSM"  
         replace adminregion_iso2 = "7E"  if `match' == "XKX"  
         replace adminregion_iso2 = "XQ"  if `match' == "YEM"  
         replace adminregion_iso2 = "ZF"  if `match' == "ZAF"  
         replace adminregion_iso2 = "ZF"  if `match' == "ZMB"  
  
******************  Lable: adminregion_iso2 ******************
  
     lab var adminregion_iso2    "Administrative Region Code (ISO 2 digits)" 
 }        
  
 ****************************************************** 
  
 ******************  Values: adminregionname ****************** 
  
 qui if ("`adminregionname'" == "adminregionname") {      
  
         gen adminregionname = ""  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "AFG"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "AGO"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "ALB"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "ARG"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "ARM"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "ASM"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "AZE"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "BDI"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "BEN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "BFA"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "BGD"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "BGR"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "BIH"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "BLR"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "BLZ"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "BOL"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "BRA"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "BTN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "BWA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "CAF"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "CHN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "CIV"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "CMR"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "COD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "COG"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "COL"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "COM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "CPV"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "CRI"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "CUB"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "DJI"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "DMA"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "DOM"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "DZA"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "ECU"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "EGY"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "ERI"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "ETH"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "FJI"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "FSM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "GAB"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "GEO"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "GHA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "GIN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "GMB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "GNB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "GNQ"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "GRD"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "GTM"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "GUY"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "HND"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "HTI"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "IDN"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "IND"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "IRN"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "IRQ"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "JAM"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "JOR"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "KAZ"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "KEN"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "KGZ"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "KHM"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "KIR"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "LAO"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "LBN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "LBR"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "LBY"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "LCA"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "LKA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "LSO"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "MAR"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "MDA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "MDG"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "MDV"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "MEX"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "MHL"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "MKD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "MLI"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "MMR"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "MNE"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "MNG"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "MOZ"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "MRT"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "MUS"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "MWI"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "MYS"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "NAM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "NER"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "NGA"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "NIC"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "NPL"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "NRU"  
         replace adminregionname = "South Asia (excluding high income)"  if `match' == "PAK"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "PER"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "PHL"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "PNG"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "PRK"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "PRY"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "PSE"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "ROU"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "RUS"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "RWA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "SDN"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "SEN"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "SLB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "SLE"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "SLV"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "SOM"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "SRB"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "SSD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "STP"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "SUR"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "SWZ"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "SYR"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "TCD"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "TGO"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "THA"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "TJK"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "TKM"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "TLS"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "TON"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "TUN"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "TUR"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "TUV"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "TZA"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "UGA"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "UKR"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "UZB"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "VCT"  
         replace adminregionname = "Latin America and Caribbean (excluding high income)"  if `match' == "VEN"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "VNM"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "VUT"  
         replace adminregionname = "East Asia and Pacific (excluding high income)"  if `match' == "WSM"  
         replace adminregionname = "Europe and Central Asia (excluding high income)"  if `match' == "XKX"  
         replace adminregionname = "Middle East and North Africa (excluding high income)"  if `match' == "YEM"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "ZAF"  
         replace adminregionname = "Sub-Saharan Africa (excluding high income)"  if `match' == "ZMB"  
  
******************  Lable: adminregionname ******************
  
     lab var adminregionname         "Administrative Region Name" 
 }        
  
 ****************************************************** 
  
 ******************  Values: incomelevel ****************** 
  
 qui if ("`incomelevel'" == "incomelevel") {      
  
         gen incomelevel = ""  
         replace incomelevel = "HIC"  if `match' == "ABW"  
         replace incomelevel = "LIC"  if `match' == "AFG"  
         replace incomelevel = "NA"  if `match' == "AFR"  
         replace incomelevel = "LMC"  if `match' == "AGO"  
         replace incomelevel = "UMC"  if `match' == "ALB"  
         replace incomelevel = "HIC"  if `match' == "AND"  
         replace incomelevel = "NA"  if `match' == "ANR"  
         replace incomelevel = "NA"  if `match' == "ARB"  
         replace incomelevel = "HIC"  if `match' == "ARE"  
         replace incomelevel = "UMC"  if `match' == "ARG"  
         replace incomelevel = "UMC"  if `match' == "ARM"  
         replace incomelevel = "UMC"  if `match' == "ASM"  
         replace incomelevel = "HIC"  if `match' == "ATG"  
         replace incomelevel = "HIC"  if `match' == "AUS"  
         replace incomelevel = "HIC"  if `match' == "AUT"  
         replace incomelevel = "UMC"  if `match' == "AZE"  
         replace incomelevel = "LIC"  if `match' == "BDI"  
         replace incomelevel = "NA"  if `match' == "BEA"  
         replace incomelevel = "NA"  if `match' == "BEC"  
         replace incomelevel = "HIC"  if `match' == "BEL"  
         replace incomelevel = "LIC"  if `match' == "BEN"  
         replace incomelevel = "LIC"  if `match' == "BFA"  
         replace incomelevel = "LMC"  if `match' == "BGD"  
         replace incomelevel = "UMC"  if `match' == "BGR"  
         replace incomelevel = "NA"  if `match' == "BHI"  
         replace incomelevel = "HIC"  if `match' == "BHR"  
         replace incomelevel = "HIC"  if `match' == "BHS"  
         replace incomelevel = "UMC"  if `match' == "BIH"  
         replace incomelevel = "NA"  if `match' == "BLA"  
         replace incomelevel = "UMC"  if `match' == "BLR"  
         replace incomelevel = "UMC"  if `match' == "BLZ"  
         replace incomelevel = "NA"  if `match' == "BMN"  
         replace incomelevel = "HIC"  if `match' == "BMU"  
         replace incomelevel = "LMC"  if `match' == "BOL"  
         replace incomelevel = "UMC"  if `match' == "BRA"  
         replace incomelevel = "HIC"  if `match' == "BRB"  
         replace incomelevel = "HIC"  if `match' == "BRN"  
         replace incomelevel = "NA"  if `match' == "BSS"  
         replace incomelevel = "LMC"  if `match' == "BTN"  
         replace incomelevel = "UMC"  if `match' == "BWA"  
         replace incomelevel = "NA"  if `match' == "CAA"  
         replace incomelevel = "LIC"  if `match' == "CAF"  
         replace incomelevel = "HIC"  if `match' == "CAN"  
         replace incomelevel = "NA"  if `match' == "CEA"  
         replace incomelevel = "NA"  if `match' == "CEB"  
         replace incomelevel = "NA"  if `match' == "CEU"  
         replace incomelevel = "HIC"  if `match' == "CHE"  
         replace incomelevel = "HIC"  if `match' == "CHI"  
         replace incomelevel = "HIC"  if `match' == "CHL"  
         replace incomelevel = "UMC"  if `match' == "CHN"  
         replace incomelevel = "LMC"  if `match' == "CIV"  
         replace incomelevel = "NA"  if `match' == "CLA"  
         replace incomelevel = "NA"  if `match' == "CME"  
         replace incomelevel = "LMC"  if `match' == "CMR"  
         replace incomelevel = "LIC"  if `match' == "COD"  
         replace incomelevel = "LMC"  if `match' == "COG"  
         replace incomelevel = "UMC"  if `match' == "COL"  
         replace incomelevel = "LMC"  if `match' == "COM"  
         replace incomelevel = "LMC"  if `match' == "CPV"  
         replace incomelevel = "UMC"  if `match' == "CRI"  
         replace incomelevel = "NA"  if `match' == "CSA"  
         replace incomelevel = "NA"  if `match' == "CSS"  
         replace incomelevel = "UMC"  if `match' == "CUB"  
         replace incomelevel = "HIC"  if `match' == "CUW"  
         replace incomelevel = "HIC"  if `match' == "CYM"  
         replace incomelevel = "HIC"  if `match' == "CYP"  
         replace incomelevel = "HIC"  if `match' == "CZE"  
         replace incomelevel = "NA"  if `match' == "DEA"  
         replace incomelevel = "NA"  if `match' == "DEC"  
         replace incomelevel = "HIC"  if `match' == "DEU"  
         replace incomelevel = "NA"  if `match' == "DFS"  
         replace incomelevel = "LMC"  if `match' == "DJI"  
         replace incomelevel = "NA"  if `match' == "DLA"  
         replace incomelevel = "UMC"  if `match' == "DMA"  
         replace incomelevel = "NA"  if `match' == "DMN"  
         replace incomelevel = "NA"  if `match' == "DNF"  
         replace incomelevel = "HIC"  if `match' == "DNK"  
         replace incomelevel = "NA"  if `match' == "DNS"  
         replace incomelevel = "UMC"  if `match' == "DOM"  
         replace incomelevel = "NA"  if `match' == "DSA"  
         replace incomelevel = "NA"  if `match' == "DSF"  
         replace incomelevel = "NA"  if `match' == "DSS"  
         replace incomelevel = "NA"  if `match' == "DXS"  
         replace incomelevel = "UMC"  if `match' == "DZA"  
         replace incomelevel = "NA"  if `match' == "EAP"  
         replace incomelevel = "NA"  if `match' == "EAR"  
         replace incomelevel = "NA"  if `match' == "EAS"  
         replace incomelevel = "NA"  if `match' == "ECA"  
         replace incomelevel = "NA"  if `match' == "ECS"  
         replace incomelevel = "UMC"  if `match' == "ECU"  
         replace incomelevel = "LMC"  if `match' == "EGY"  
         replace incomelevel = "NA"  if `match' == "EMU"  
         replace incomelevel = "LIC"  if `match' == "ERI"  
         replace incomelevel = "HIC"  if `match' == "ESP"  
         replace incomelevel = "HIC"  if `match' == "EST"  
         replace incomelevel = "LIC"  if `match' == "ETH"  
         replace incomelevel = "NA"  if `match' == "EUU"  
         replace incomelevel = "NA"  if `match' == "FCS"  
         replace incomelevel = "HIC"  if `match' == "FIN"  
         replace incomelevel = "UMC"  if `match' == "FJI"  
         replace incomelevel = "HIC"  if `match' == "FRA"  
         replace incomelevel = "HIC"  if `match' == "FRO"  
         replace incomelevel = "LMC"  if `match' == "FSM"  
         replace incomelevel = "NA"  if `match' == "FXS"  
         replace incomelevel = "UMC"  if `match' == "GAB"  
         replace incomelevel = "HIC"  if `match' == "GBR"  
         replace incomelevel = "UMC"  if `match' == "GEO"  
         replace incomelevel = "LMC"  if `match' == "GHA"  
         replace incomelevel = "HIC"  if `match' == "GIB"  
         replace incomelevel = "LIC"  if `match' == "GIN"  
         replace incomelevel = "LIC"  if `match' == "GMB"  
         replace incomelevel = "LIC"  if `match' == "GNB"  
         replace incomelevel = "UMC"  if `match' == "GNQ"  
         replace incomelevel = "HIC"  if `match' == "GRC"  
         replace incomelevel = "UMC"  if `match' == "GRD"  
         replace incomelevel = "HIC"  if `match' == "GRL"  
         replace incomelevel = "UMC"  if `match' == "GTM"  
         replace incomelevel = "HIC"  if `match' == "GUM"  
         replace incomelevel = "UMC"  if `match' == "GUY"  
         replace incomelevel = "NA"  if `match' == "HIC"  
         replace incomelevel = "HIC"  if `match' == "HKG"  
         replace incomelevel = "LMC"  if `match' == "HND"  
         replace incomelevel = "NA"  if `match' == "HPC"  
         replace incomelevel = "HIC"  if `match' == "HRV"  
         replace incomelevel = "LIC"  if `match' == "HTI"  
         replace incomelevel = "HIC"  if `match' == "HUN"  
         replace incomelevel = "NA"  if `match' == "IBB"  
         replace incomelevel = "NA"  if `match' == "IBD"  
         replace incomelevel = "NA"  if `match' == "IBT"  
         replace incomelevel = "NA"  if `match' == "IDA"  
         replace incomelevel = "NA"  if `match' == "IDB"  
         replace incomelevel = "LMC"  if `match' == "IDN"  
         replace incomelevel = "NA"  if `match' == "IDX"  
         replace incomelevel = "HIC"  if `match' == "IMN"  
         replace incomelevel = "LMC"  if `match' == "IND"  
         replace incomelevel = "NA"  if `match' == "INX"  
         replace incomelevel = "HIC"  if `match' == "IRL"  
         replace incomelevel = "UMC"  if `match' == "IRN"  
         replace incomelevel = "UMC"  if `match' == "IRQ"  
         replace incomelevel = "HIC"  if `match' == "ISL"  
         replace incomelevel = "HIC"  if `match' == "ISR"  
         replace incomelevel = "HIC"  if `match' == "ITA"  
         replace incomelevel = "UMC"  if `match' == "JAM"  
         replace incomelevel = "UMC"  if `match' == "JOR"  
         replace incomelevel = "HIC"  if `match' == "JPN"  
         replace incomelevel = "UMC"  if `match' == "KAZ"  
         replace incomelevel = "LMC"  if `match' == "KEN"  
         replace incomelevel = "LMC"  if `match' == "KGZ"  
         replace incomelevel = "LMC"  if `match' == "KHM"  
         replace incomelevel = "LMC"  if `match' == "KIR"  
         replace incomelevel = "HIC"  if `match' == "KNA"  
         replace incomelevel = "HIC"  if `match' == "KOR"  
         replace incomelevel = "HIC"  if `match' == "KWT"  
         replace incomelevel = "NA"  if `match' == "LAC"  
         replace incomelevel = "LMC"  if `match' == "LAO"  
         replace incomelevel = "UMC"  if `match' == "LBN"  
         replace incomelevel = "LIC"  if `match' == "LBR"  
         replace incomelevel = "UMC"  if `match' == "LBY"  
         replace incomelevel = "UMC"  if `match' == "LCA"  
         replace incomelevel = "NA"  if `match' == "LCN"  
         replace incomelevel = "NA"  if `match' == "LCR"  
         replace incomelevel = "NA"  if `match' == "LDC"  
         replace incomelevel = "NA"  if `match' == "LIC"  
         replace incomelevel = "HIC"  if `match' == "LIE"  
         replace incomelevel = "UMC"  if `match' == "LKA"  
         replace incomelevel = "NA"  if `match' == "LMC"  
         replace incomelevel = "NA"  if `match' == "LMY"  
         replace incomelevel = "LMC"  if `match' == "LSO"  
         replace incomelevel = "NA"  if `match' == "LTE"  
         replace incomelevel = "HIC"  if `match' == "LTU"  
         replace incomelevel = "HIC"  if `match' == "LUX"  
         replace incomelevel = "HIC"  if `match' == "LVA"  
         replace incomelevel = "HIC"  if `match' == "MAC"  
         replace incomelevel = "HIC"  if `match' == "MAF"  
         replace incomelevel = "LMC"  if `match' == "MAR"  
         replace incomelevel = "NA"  if `match' == "MCA"  
         replace incomelevel = "HIC"  if `match' == "MCO"  
         replace incomelevel = "LMC"  if `match' == "MDA"  
         replace incomelevel = "NA"  if `match' == "MDE"  
         replace incomelevel = "LIC"  if `match' == "MDG"  
         replace incomelevel = "UMC"  if `match' == "MDV"  
         replace incomelevel = "NA"  if `match' == "MEA"  
         replace incomelevel = "UMC"  if `match' == "MEX"  
         replace incomelevel = "UMC"  if `match' == "MHL"  
         replace incomelevel = "NA"  if `match' == "MIC"  
         replace incomelevel = "UMC"  if `match' == "MKD"  
         replace incomelevel = "LIC"  if `match' == "MLI"  
         replace incomelevel = "HIC"  if `match' == "MLT"  
         replace incomelevel = "LMC"  if `match' == "MMR"  
         replace incomelevel = "NA"  if `match' == "MNA"  
         replace incomelevel = "UMC"  if `match' == "MNE"  
         replace incomelevel = "LMC"  if `match' == "MNG"  
         replace incomelevel = "HIC"  if `match' == "MNP"  
         replace incomelevel = "LIC"  if `match' == "MOZ"  
         replace incomelevel = "LMC"  if `match' == "MRT"  
         replace incomelevel = "UMC"  if `match' == "MUS"  
         replace incomelevel = "LIC"  if `match' == "MWI"  
         replace incomelevel = "UMC"  if `match' == "MYS"  
         replace incomelevel = "NA"  if `match' == "NAC"  
         replace incomelevel = "NA"  if `match' == "NAF"  
         replace incomelevel = "UMC"  if `match' == "NAM"  
         replace incomelevel = "HIC"  if `match' == "NCL"  
         replace incomelevel = "LIC"  if `match' == "NER"  
         replace incomelevel = "LMC"  if `match' == "NGA"  
         replace incomelevel = "LMC"  if `match' == "NIC"  
         replace incomelevel = "HIC"  if `match' == "NLD"  
         replace incomelevel = "NA"  if `match' == "NLS"  
         replace incomelevel = "HIC"  if `match' == "NOR"  
         replace incomelevel = "LIC"  if `match' == "NPL"  
         replace incomelevel = "NA"  if `match' == "NRS"  
         replace incomelevel = "UMC"  if `match' == "NRU"  
         replace incomelevel = "NA"  if `match' == "NXS"  
         replace incomelevel = "HIC"  if `match' == "NZL"  
         replace incomelevel = "NA"  if `match' == "OED"  
         replace incomelevel = "HIC"  if `match' == "OMN"  
         replace incomelevel = "NA"  if `match' == "OSS"  
         replace incomelevel = "LMC"  if `match' == "PAK"  
         replace incomelevel = "HIC"  if `match' == "PAN"  
         replace incomelevel = "UMC"  if `match' == "PER"  
         replace incomelevel = "LMC"  if `match' == "PHL"  
         replace incomelevel = "HIC"  if `match' == "PLW"  
         replace incomelevel = "LMC"  if `match' == "PNG"  
         replace incomelevel = "HIC"  if `match' == "POL"  
         replace incomelevel = "NA"  if `match' == "PRE"  
         replace incomelevel = "HIC"  if `match' == "PRI"  
         replace incomelevel = "LIC"  if `match' == "PRK"  
         replace incomelevel = "HIC"  if `match' == "PRT"  
         replace incomelevel = "UMC"  if `match' == "PRY"  
         replace incomelevel = "LMC"  if `match' == "PSE"  
         replace incomelevel = "NA"  if `match' == "PSS"  
         replace incomelevel = "NA"  if `match' == "PST"  
         replace incomelevel = "HIC"  if `match' == "PYF"  
         replace incomelevel = "HIC"  if `match' == "QAT"  
         replace incomelevel = "UMC"  if `match' == "ROU"  
         replace incomelevel = "NA"  if `match' == "RRS"  
         replace incomelevel = "NA"  if `match' == "RSO"  
         replace incomelevel = "UMC"  if `match' == "RUS"  
         replace incomelevel = "LIC"  if `match' == "RWA"  
         replace incomelevel = "NA"  if `match' == "SAS"  
         replace incomelevel = "HIC"  if `match' == "SAU"  
         replace incomelevel = "NA"  if `match' == "SCE"  
         replace incomelevel = "LMC"  if `match' == "SDN"  
         replace incomelevel = "LMC"  if `match' == "SEN"  
         replace incomelevel = "HIC"  if `match' == "SGP"  
         replace incomelevel = "LMC"  if `match' == "SLB"  
         replace incomelevel = "LIC"  if `match' == "SLE"  
         replace incomelevel = "LMC"  if `match' == "SLV"  
         replace incomelevel = "HIC"  if `match' == "SMR"  
         replace incomelevel = "LIC"  if `match' == "SOM"  
         replace incomelevel = "UMC"  if `match' == "SRB"  
         replace incomelevel = "NA"  if `match' == "SSA"  
         replace incomelevel = "LIC"  if `match' == "SSD"  
         replace incomelevel = "NA"  if `match' == "SSF"  
         replace incomelevel = "NA"  if `match' == "SST"  
         replace incomelevel = "LMC"  if `match' == "STP"  
         replace incomelevel = "UMC"  if `match' == "SUR"  
         replace incomelevel = "HIC"  if `match' == "SVK"  
         replace incomelevel = "HIC"  if `match' == "SVN"  
         replace incomelevel = "HIC"  if `match' == "SWE"  
         replace incomelevel = "LMC"  if `match' == "SWZ"  
         replace incomelevel = "HIC"  if `match' == "SXM"  
         replace incomelevel = "NA"  if `match' == "SXZ"  
         replace incomelevel = "HIC"  if `match' == "SYC"  
         replace incomelevel = "LIC"  if `match' == "SYR"  
         replace incomelevel = "HIC"  if `match' == "TCA"  
         replace incomelevel = "LIC"  if `match' == "TCD"  
         replace incomelevel = "NA"  if `match' == "TEA"  
         replace incomelevel = "NA"  if `match' == "TEC"  
         replace incomelevel = "LIC"  if `match' == "TGO"  
         replace incomelevel = "UMC"  if `match' == "THA"  
         replace incomelevel = "LIC"  if `match' == "TJK"  
         replace incomelevel = "UMC"  if `match' == "TKM"  
         replace incomelevel = "NA"  if `match' == "TLA"  
         replace incomelevel = "LMC"  if `match' == "TLS"  
         replace incomelevel = "NA"  if `match' == "TMN"  
         replace incomelevel = "UMC"  if `match' == "TON"  
         replace incomelevel = "NA"  if `match' == "TSA"  
         replace incomelevel = "NA"  if `match' == "TSS"  
         replace incomelevel = "HIC"  if `match' == "TTO"  
         replace incomelevel = "LMC"  if `match' == "TUN"  
         replace incomelevel = "UMC"  if `match' == "TUR"  
         replace incomelevel = "UMC"  if `match' == "TUV"  
         replace incomelevel = "HIC"  if `match' == "TWN"  
         replace incomelevel = "LIC"  if `match' == "TZA"  
         replace incomelevel = "LIC"  if `match' == "UGA"  
         replace incomelevel = "LMC"  if `match' == "UKR"  
         replace incomelevel = "NA"  if `match' == "UMC"  
         replace incomelevel = "HIC"  if `match' == "URY"  
         replace incomelevel = "HIC"  if `match' == "USA"  
         replace incomelevel = "LMC"  if `match' == "UZB"  
         replace incomelevel = "UMC"  if `match' == "VCT"  
         replace incomelevel = "UMC"  if `match' == "VEN"  
         replace incomelevel = "HIC"  if `match' == "VGB"  
         replace incomelevel = "HIC"  if `match' == "VIR"  
         replace incomelevel = "LMC"  if `match' == "VNM"  
         replace incomelevel = "LMC"  if `match' == "VUT"  
         replace incomelevel = "NA"  if `match' == "WLD"  
         replace incomelevel = "UMC"  if `match' == "WSM"  
         replace incomelevel = "UMC"  if `match' == "XKX"  
         replace incomelevel = "NA"  if `match' == "XZN"  
         replace incomelevel = "LIC"  if `match' == "YEM"  
         replace incomelevel = "UMC"  if `match' == "ZAF"  
         replace incomelevel = "LMC"  if `match' == "ZMB"  
  
******************  Lable: incomelevel ******************
  
     lab var incomelevel                 "Income Level Code" 
 }        
  
 ****************************************************** 
  
 ******************  Values: incomelevel_iso2 ****************** 
  
 qui if ("`incomelevel_iso2'" == "incomelevel_iso2") {      
  
         gen incomelevel_iso2 = ""  
         replace incomelevel_iso2 = "XD"  if `match' == "ABW"  
         replace incomelevel_iso2 = "XM"  if `match' == "AFG"  
         replace incomelevel_iso2 = "NA"  if `match' == "AFR"  
         replace incomelevel_iso2 = "XN"  if `match' == "AGO"  
         replace incomelevel_iso2 = "XT"  if `match' == "ALB"  
         replace incomelevel_iso2 = "XD"  if `match' == "AND"  
         replace incomelevel_iso2 = "NA"  if `match' == "ANR"  
         replace incomelevel_iso2 = "NA"  if `match' == "ARB"  
         replace incomelevel_iso2 = "XD"  if `match' == "ARE"  
         replace incomelevel_iso2 = "XT"  if `match' == "ARG"  
         replace incomelevel_iso2 = "XT"  if `match' == "ARM"  
         replace incomelevel_iso2 = "XT"  if `match' == "ASM"  
         replace incomelevel_iso2 = "XD"  if `match' == "ATG"  
         replace incomelevel_iso2 = "XD"  if `match' == "AUS"  
         replace incomelevel_iso2 = "XD"  if `match' == "AUT"  
         replace incomelevel_iso2 = "XT"  if `match' == "AZE"  
         replace incomelevel_iso2 = "XM"  if `match' == "BDI"  
         replace incomelevel_iso2 = "NA"  if `match' == "BEA"  
         replace incomelevel_iso2 = "NA"  if `match' == "BEC"  
         replace incomelevel_iso2 = "XD"  if `match' == "BEL"  
         replace incomelevel_iso2 = "XM"  if `match' == "BEN"  
         replace incomelevel_iso2 = "XM"  if `match' == "BFA"  
         replace incomelevel_iso2 = "XN"  if `match' == "BGD"  
         replace incomelevel_iso2 = "XT"  if `match' == "BGR"  
         replace incomelevel_iso2 = "NA"  if `match' == "BHI"  
         replace incomelevel_iso2 = "XD"  if `match' == "BHR"  
         replace incomelevel_iso2 = "XD"  if `match' == "BHS"  
         replace incomelevel_iso2 = "XT"  if `match' == "BIH"  
         replace incomelevel_iso2 = "NA"  if `match' == "BLA"  
         replace incomelevel_iso2 = "XT"  if `match' == "BLR"  
         replace incomelevel_iso2 = "XT"  if `match' == "BLZ"  
         replace incomelevel_iso2 = "NA"  if `match' == "BMN"  
         replace incomelevel_iso2 = "XD"  if `match' == "BMU"  
         replace incomelevel_iso2 = "XN"  if `match' == "BOL"  
         replace incomelevel_iso2 = "XT"  if `match' == "BRA"  
         replace incomelevel_iso2 = "XD"  if `match' == "BRB"  
         replace incomelevel_iso2 = "XD"  if `match' == "BRN"  
         replace incomelevel_iso2 = "NA"  if `match' == "BSS"  
         replace incomelevel_iso2 = "XN"  if `match' == "BTN"  
         replace incomelevel_iso2 = "XT"  if `match' == "BWA"  
         replace incomelevel_iso2 = "NA"  if `match' == "CAA"  
         replace incomelevel_iso2 = "XM"  if `match' == "CAF"  
         replace incomelevel_iso2 = "XD"  if `match' == "CAN"  
         replace incomelevel_iso2 = "NA"  if `match' == "CEA"  
         replace incomelevel_iso2 = "NA"  if `match' == "CEB"  
         replace incomelevel_iso2 = "NA"  if `match' == "CEU"  
         replace incomelevel_iso2 = "XD"  if `match' == "CHE"  
         replace incomelevel_iso2 = "XD"  if `match' == "CHI"  
         replace incomelevel_iso2 = "XD"  if `match' == "CHL"  
         replace incomelevel_iso2 = "XT"  if `match' == "CHN"  
         replace incomelevel_iso2 = "XN"  if `match' == "CIV"  
         replace incomelevel_iso2 = "NA"  if `match' == "CLA"  
         replace incomelevel_iso2 = "NA"  if `match' == "CME"  
         replace incomelevel_iso2 = "XN"  if `match' == "CMR"  
         replace incomelevel_iso2 = "XM"  if `match' == "COD"  
         replace incomelevel_iso2 = "XN"  if `match' == "COG"  
         replace incomelevel_iso2 = "XT"  if `match' == "COL"  
         replace incomelevel_iso2 = "XN"  if `match' == "COM"  
         replace incomelevel_iso2 = "XN"  if `match' == "CPV"  
         replace incomelevel_iso2 = "XT"  if `match' == "CRI"  
         replace incomelevel_iso2 = "NA"  if `match' == "CSA"  
         replace incomelevel_iso2 = "NA"  if `match' == "CSS"  
         replace incomelevel_iso2 = "XT"  if `match' == "CUB"  
         replace incomelevel_iso2 = "XD"  if `match' == "CUW"  
         replace incomelevel_iso2 = "XD"  if `match' == "CYM"  
         replace incomelevel_iso2 = "XD"  if `match' == "CYP"  
         replace incomelevel_iso2 = "XD"  if `match' == "CZE"  
         replace incomelevel_iso2 = "NA"  if `match' == "DEA"  
         replace incomelevel_iso2 = "NA"  if `match' == "DEC"  
         replace incomelevel_iso2 = "XD"  if `match' == "DEU"  
         replace incomelevel_iso2 = "NA"  if `match' == "DFS"  
         replace incomelevel_iso2 = "XN"  if `match' == "DJI"  
         replace incomelevel_iso2 = "NA"  if `match' == "DLA"  
         replace incomelevel_iso2 = "XT"  if `match' == "DMA"  
         replace incomelevel_iso2 = "NA"  if `match' == "DMN"  
         replace incomelevel_iso2 = "NA"  if `match' == "DNF"  
         replace incomelevel_iso2 = "XD"  if `match' == "DNK"  
         replace incomelevel_iso2 = "NA"  if `match' == "DNS"  
         replace incomelevel_iso2 = "XT"  if `match' == "DOM"  
         replace incomelevel_iso2 = "NA"  if `match' == "DSA"  
         replace incomelevel_iso2 = "NA"  if `match' == "DSF"  
         replace incomelevel_iso2 = "NA"  if `match' == "DSS"  
         replace incomelevel_iso2 = "NA"  if `match' == "DXS"  
         replace incomelevel_iso2 = "XT"  if `match' == "DZA"  
         replace incomelevel_iso2 = "NA"  if `match' == "EAP"  
         replace incomelevel_iso2 = "NA"  if `match' == "EAR"  
         replace incomelevel_iso2 = "NA"  if `match' == "EAS"  
         replace incomelevel_iso2 = "NA"  if `match' == "ECA"  
         replace incomelevel_iso2 = "NA"  if `match' == "ECS"  
         replace incomelevel_iso2 = "XT"  if `match' == "ECU"  
         replace incomelevel_iso2 = "XN"  if `match' == "EGY"  
         replace incomelevel_iso2 = "NA"  if `match' == "EMU"  
         replace incomelevel_iso2 = "XM"  if `match' == "ERI"  
         replace incomelevel_iso2 = "XD"  if `match' == "ESP"  
         replace incomelevel_iso2 = "XD"  if `match' == "EST"  
         replace incomelevel_iso2 = "XM"  if `match' == "ETH"  
         replace incomelevel_iso2 = "NA"  if `match' == "EUU"  
         replace incomelevel_iso2 = "NA"  if `match' == "FCS"  
         replace incomelevel_iso2 = "XD"  if `match' == "FIN"  
         replace incomelevel_iso2 = "XT"  if `match' == "FJI"  
         replace incomelevel_iso2 = "XD"  if `match' == "FRA"  
         replace incomelevel_iso2 = "XD"  if `match' == "FRO"  
         replace incomelevel_iso2 = "XN"  if `match' == "FSM"  
         replace incomelevel_iso2 = "NA"  if `match' == "FXS"  
         replace incomelevel_iso2 = "XT"  if `match' == "GAB"  
         replace incomelevel_iso2 = "XD"  if `match' == "GBR"  
         replace incomelevel_iso2 = "XT"  if `match' == "GEO"  
         replace incomelevel_iso2 = "XN"  if `match' == "GHA"  
         replace incomelevel_iso2 = "XD"  if `match' == "GIB"  
         replace incomelevel_iso2 = "XM"  if `match' == "GIN"  
         replace incomelevel_iso2 = "XM"  if `match' == "GMB"  
         replace incomelevel_iso2 = "XM"  if `match' == "GNB"  
         replace incomelevel_iso2 = "XT"  if `match' == "GNQ"  
         replace incomelevel_iso2 = "XD"  if `match' == "GRC"  
         replace incomelevel_iso2 = "XT"  if `match' == "GRD"  
         replace incomelevel_iso2 = "XD"  if `match' == "GRL"  
         replace incomelevel_iso2 = "XT"  if `match' == "GTM"  
         replace incomelevel_iso2 = "XD"  if `match' == "GUM"  
         replace incomelevel_iso2 = "XT"  if `match' == "GUY"  
         replace incomelevel_iso2 = "NA"  if `match' == "HIC"  
         replace incomelevel_iso2 = "XD"  if `match' == "HKG"  
         replace incomelevel_iso2 = "XN"  if `match' == "HND"  
         replace incomelevel_iso2 = "NA"  if `match' == "HPC"  
         replace incomelevel_iso2 = "XD"  if `match' == "HRV"  
         replace incomelevel_iso2 = "XM"  if `match' == "HTI"  
         replace incomelevel_iso2 = "XD"  if `match' == "HUN"  
         replace incomelevel_iso2 = "NA"  if `match' == "IBB"  
         replace incomelevel_iso2 = "NA"  if `match' == "IBD"  
         replace incomelevel_iso2 = "NA"  if `match' == "IBT"  
         replace incomelevel_iso2 = "NA"  if `match' == "IDA"  
         replace incomelevel_iso2 = "NA"  if `match' == "IDB"  
         replace incomelevel_iso2 = "XN"  if `match' == "IDN"  
         replace incomelevel_iso2 = "NA"  if `match' == "IDX"  
         replace incomelevel_iso2 = "XD"  if `match' == "IMN"  
         replace incomelevel_iso2 = "XN"  if `match' == "IND"  
         replace incomelevel_iso2 = "NA"  if `match' == "INX"  
         replace incomelevel_iso2 = "XD"  if `match' == "IRL"  
         replace incomelevel_iso2 = "XT"  if `match' == "IRN"  
         replace incomelevel_iso2 = "XT"  if `match' == "IRQ"  
         replace incomelevel_iso2 = "XD"  if `match' == "ISL"  
         replace incomelevel_iso2 = "XD"  if `match' == "ISR"  
         replace incomelevel_iso2 = "XD"  if `match' == "ITA"  
         replace incomelevel_iso2 = "XT"  if `match' == "JAM"  
         replace incomelevel_iso2 = "XT"  if `match' == "JOR"  
         replace incomelevel_iso2 = "XD"  if `match' == "JPN"  
         replace incomelevel_iso2 = "XT"  if `match' == "KAZ"  
         replace incomelevel_iso2 = "XN"  if `match' == "KEN"  
         replace incomelevel_iso2 = "XN"  if `match' == "KGZ"  
         replace incomelevel_iso2 = "XN"  if `match' == "KHM"  
         replace incomelevel_iso2 = "XN"  if `match' == "KIR"  
         replace incomelevel_iso2 = "XD"  if `match' == "KNA"  
         replace incomelevel_iso2 = "XD"  if `match' == "KOR"  
         replace incomelevel_iso2 = "XD"  if `match' == "KWT"  
         replace incomelevel_iso2 = "NA"  if `match' == "LAC"  
         replace incomelevel_iso2 = "XN"  if `match' == "LAO"  
         replace incomelevel_iso2 = "XT"  if `match' == "LBN"  
         replace incomelevel_iso2 = "XM"  if `match' == "LBR"  
         replace incomelevel_iso2 = "XT"  if `match' == "LBY"  
         replace incomelevel_iso2 = "XT"  if `match' == "LCA"  
         replace incomelevel_iso2 = "NA"  if `match' == "LCN"  
         replace incomelevel_iso2 = "NA"  if `match' == "LCR"  
         replace incomelevel_iso2 = "NA"  if `match' == "LDC"  
         replace incomelevel_iso2 = "NA"  if `match' == "LIC"  
         replace incomelevel_iso2 = "XD"  if `match' == "LIE"  
         replace incomelevel_iso2 = "XT"  if `match' == "LKA"  
         replace incomelevel_iso2 = "NA"  if `match' == "LMC"  
         replace incomelevel_iso2 = "NA"  if `match' == "LMY"  
         replace incomelevel_iso2 = "XN"  if `match' == "LSO"  
         replace incomelevel_iso2 = "NA"  if `match' == "LTE"  
         replace incomelevel_iso2 = "XD"  if `match' == "LTU"  
         replace incomelevel_iso2 = "XD"  if `match' == "LUX"  
         replace incomelevel_iso2 = "XD"  if `match' == "LVA"  
         replace incomelevel_iso2 = "XD"  if `match' == "MAC"  
         replace incomelevel_iso2 = "XD"  if `match' == "MAF"  
         replace incomelevel_iso2 = "XN"  if `match' == "MAR"  
         replace incomelevel_iso2 = "NA"  if `match' == "MCA"  
         replace incomelevel_iso2 = "XD"  if `match' == "MCO"  
         replace incomelevel_iso2 = "XN"  if `match' == "MDA"  
         replace incomelevel_iso2 = "NA"  if `match' == "MDE"  
         replace incomelevel_iso2 = "XM"  if `match' == "MDG"  
         replace incomelevel_iso2 = "XT"  if `match' == "MDV"  
         replace incomelevel_iso2 = "NA"  if `match' == "MEA"  
         replace incomelevel_iso2 = "XT"  if `match' == "MEX"  
         replace incomelevel_iso2 = "XT"  if `match' == "MHL"  
         replace incomelevel_iso2 = "NA"  if `match' == "MIC"  
         replace incomelevel_iso2 = "XT"  if `match' == "MKD"  
         replace incomelevel_iso2 = "XM"  if `match' == "MLI"  
         replace incomelevel_iso2 = "XD"  if `match' == "MLT"  
         replace incomelevel_iso2 = "XN"  if `match' == "MMR"  
         replace incomelevel_iso2 = "NA"  if `match' == "MNA"  
         replace incomelevel_iso2 = "XT"  if `match' == "MNE"  
         replace incomelevel_iso2 = "XN"  if `match' == "MNG"  
         replace incomelevel_iso2 = "XD"  if `match' == "MNP"  
         replace incomelevel_iso2 = "XM"  if `match' == "MOZ"  
         replace incomelevel_iso2 = "XN"  if `match' == "MRT"  
         replace incomelevel_iso2 = "XT"  if `match' == "MUS"  
         replace incomelevel_iso2 = "XM"  if `match' == "MWI"  
         replace incomelevel_iso2 = "XT"  if `match' == "MYS"  
         replace incomelevel_iso2 = "NA"  if `match' == "NAC"  
         replace incomelevel_iso2 = "NA"  if `match' == "NAF"  
         replace incomelevel_iso2 = "XT"  if `match' == "NAM"  
         replace incomelevel_iso2 = "XD"  if `match' == "NCL"  
         replace incomelevel_iso2 = "XM"  if `match' == "NER"  
         replace incomelevel_iso2 = "XN"  if `match' == "NGA"  
         replace incomelevel_iso2 = "XN"  if `match' == "NIC"  
         replace incomelevel_iso2 = "XD"  if `match' == "NLD"  
         replace incomelevel_iso2 = "NA"  if `match' == "NLS"  
         replace incomelevel_iso2 = "XD"  if `match' == "NOR"  
         replace incomelevel_iso2 = "XM"  if `match' == "NPL"  
         replace incomelevel_iso2 = "NA"  if `match' == "NRS"  
         replace incomelevel_iso2 = "XT"  if `match' == "NRU"  
         replace incomelevel_iso2 = "NA"  if `match' == "NXS"  
         replace incomelevel_iso2 = "XD"  if `match' == "NZL"  
         replace incomelevel_iso2 = "NA"  if `match' == "OED"  
         replace incomelevel_iso2 = "XD"  if `match' == "OMN"  
         replace incomelevel_iso2 = "NA"  if `match' == "OSS"  
         replace incomelevel_iso2 = "XN"  if `match' == "PAK"  
         replace incomelevel_iso2 = "XD"  if `match' == "PAN"  
         replace incomelevel_iso2 = "XT"  if `match' == "PER"  
         replace incomelevel_iso2 = "XN"  if `match' == "PHL"  
         replace incomelevel_iso2 = "XD"  if `match' == "PLW"  
         replace incomelevel_iso2 = "XN"  if `match' == "PNG"  
         replace incomelevel_iso2 = "XD"  if `match' == "POL"  
         replace incomelevel_iso2 = "NA"  if `match' == "PRE"  
         replace incomelevel_iso2 = "XD"  if `match' == "PRI"  
         replace incomelevel_iso2 = "XM"  if `match' == "PRK"  
         replace incomelevel_iso2 = "XD"  if `match' == "PRT"  
         replace incomelevel_iso2 = "XT"  if `match' == "PRY"  
         replace incomelevel_iso2 = "XN"  if `match' == "PSE"  
         replace incomelevel_iso2 = "NA"  if `match' == "PSS"  
         replace incomelevel_iso2 = "NA"  if `match' == "PST"  
         replace incomelevel_iso2 = "XD"  if `match' == "PYF"  
         replace incomelevel_iso2 = "XD"  if `match' == "QAT"  
         replace incomelevel_iso2 = "XT"  if `match' == "ROU"  
         replace incomelevel_iso2 = "NA"  if `match' == "RRS"  
         replace incomelevel_iso2 = "NA"  if `match' == "RSO"  
         replace incomelevel_iso2 = "XT"  if `match' == "RUS"  
         replace incomelevel_iso2 = "XM"  if `match' == "RWA"  
         replace incomelevel_iso2 = "NA"  if `match' == "SAS"  
         replace incomelevel_iso2 = "XD"  if `match' == "SAU"  
         replace incomelevel_iso2 = "NA"  if `match' == "SCE"  
         replace incomelevel_iso2 = "XN"  if `match' == "SDN"  
         replace incomelevel_iso2 = "XN"  if `match' == "SEN"  
         replace incomelevel_iso2 = "XD"  if `match' == "SGP"  
         replace incomelevel_iso2 = "XN"  if `match' == "SLB"  
         replace incomelevel_iso2 = "XM"  if `match' == "SLE"  
         replace incomelevel_iso2 = "XN"  if `match' == "SLV"  
         replace incomelevel_iso2 = "XD"  if `match' == "SMR"  
         replace incomelevel_iso2 = "XM"  if `match' == "SOM"  
         replace incomelevel_iso2 = "XT"  if `match' == "SRB"  
         replace incomelevel_iso2 = "NA"  if `match' == "SSA"  
         replace incomelevel_iso2 = "XM"  if `match' == "SSD"  
         replace incomelevel_iso2 = "NA"  if `match' == "SSF"  
         replace incomelevel_iso2 = "NA"  if `match' == "SST"  
         replace incomelevel_iso2 = "XN"  if `match' == "STP"  
         replace incomelevel_iso2 = "XT"  if `match' == "SUR"  
         replace incomelevel_iso2 = "XD"  if `match' == "SVK"  
         replace incomelevel_iso2 = "XD"  if `match' == "SVN"  
         replace incomelevel_iso2 = "XD"  if `match' == "SWE"  
         replace incomelevel_iso2 = "XN"  if `match' == "SWZ"  
         replace incomelevel_iso2 = "XD"  if `match' == "SXM"  
         replace incomelevel_iso2 = "NA"  if `match' == "SXZ"  
         replace incomelevel_iso2 = "XD"  if `match' == "SYC"  
         replace incomelevel_iso2 = "XM"  if `match' == "SYR"  
         replace incomelevel_iso2 = "XD"  if `match' == "TCA"  
         replace incomelevel_iso2 = "XM"  if `match' == "TCD"  
         replace incomelevel_iso2 = "NA"  if `match' == "TEA"  
         replace incomelevel_iso2 = "NA"  if `match' == "TEC"  
         replace incomelevel_iso2 = "XM"  if `match' == "TGO"  
         replace incomelevel_iso2 = "XT"  if `match' == "THA"  
         replace incomelevel_iso2 = "XM"  if `match' == "TJK"  
         replace incomelevel_iso2 = "XT"  if `match' == "TKM"  
         replace incomelevel_iso2 = "NA"  if `match' == "TLA"  
         replace incomelevel_iso2 = "XN"  if `match' == "TLS"  
         replace incomelevel_iso2 = "NA"  if `match' == "TMN"  
         replace incomelevel_iso2 = "XT"  if `match' == "TON"  
         replace incomelevel_iso2 = "NA"  if `match' == "TSA"  
         replace incomelevel_iso2 = "NA"  if `match' == "TSS"  
         replace incomelevel_iso2 = "XD"  if `match' == "TTO"  
         replace incomelevel_iso2 = "XN"  if `match' == "TUN"  
         replace incomelevel_iso2 = "XT"  if `match' == "TUR"  
         replace incomelevel_iso2 = "XT"  if `match' == "TUV"  
         replace incomelevel_iso2 = "XD"  if `match' == "TWN"  
         replace incomelevel_iso2 = "XM"  if `match' == "TZA"  
         replace incomelevel_iso2 = "XM"  if `match' == "UGA"  
         replace incomelevel_iso2 = "XN"  if `match' == "UKR"  
         replace incomelevel_iso2 = "NA"  if `match' == "UMC"  
         replace incomelevel_iso2 = "XD"  if `match' == "URY"  
         replace incomelevel_iso2 = "XD"  if `match' == "USA"  
         replace incomelevel_iso2 = "XN"  if `match' == "UZB"  
         replace incomelevel_iso2 = "XT"  if `match' == "VCT"  
         replace incomelevel_iso2 = "XT"  if `match' == "VEN"  
         replace incomelevel_iso2 = "XD"  if `match' == "VGB"  
         replace incomelevel_iso2 = "XD"  if `match' == "VIR"  
         replace incomelevel_iso2 = "XN"  if `match' == "VNM"  
         replace incomelevel_iso2 = "XN"  if `match' == "VUT"  
         replace incomelevel_iso2 = "NA"  if `match' == "WLD"  
         replace incomelevel_iso2 = "XT"  if `match' == "WSM"  
         replace incomelevel_iso2 = "XT"  if `match' == "XKX"  
         replace incomelevel_iso2 = "NA"  if `match' == "XZN"  
         replace incomelevel_iso2 = "XM"  if `match' == "YEM"  
         replace incomelevel_iso2 = "XT"  if `match' == "ZAF"  
         replace incomelevel_iso2 = "XN"  if `match' == "ZMB"  
  
******************  Lable: incomelevel_iso2 ******************
  
     lab var incomelevel_iso2    "Income Level Code (ISO 2 digits)" 
 }        
  
 ****************************************************** 
  
 ******************  Values: incomelevelname ****************** 
  
 qui if ("`incomelevelname'" == "incomelevelname") {      
  
         gen incomelevelname = ""  
         replace incomelevelname = "High income"  if `match' == "ABW"  
         replace incomelevelname = "Low income"  if `match' == "AFG"  
         replace incomelevelname = "Aggregates"  if `match' == "AFR"  
         replace incomelevelname = "Lower middle income"  if `match' == "AGO"  
         replace incomelevelname = "Upper middle income"  if `match' == "ALB"  
         replace incomelevelname = "High income"  if `match' == "AND"  
         replace incomelevelname = "Aggregates"  if `match' == "ANR"  
         replace incomelevelname = "Aggregates"  if `match' == "ARB"  
         replace incomelevelname = "High income"  if `match' == "ARE"  
         replace incomelevelname = "Upper middle income"  if `match' == "ARG"  
         replace incomelevelname = "Upper middle income"  if `match' == "ARM"  
         replace incomelevelname = "Upper middle income"  if `match' == "ASM"  
         replace incomelevelname = "High income"  if `match' == "ATG"  
         replace incomelevelname = "High income"  if `match' == "AUS"  
         replace incomelevelname = "High income"  if `match' == "AUT"  
         replace incomelevelname = "Upper middle income"  if `match' == "AZE"  
         replace incomelevelname = "Low income"  if `match' == "BDI"  
         replace incomelevelname = "Aggregates"  if `match' == "BEA"  
         replace incomelevelname = "Aggregates"  if `match' == "BEC"  
         replace incomelevelname = "High income"  if `match' == "BEL"  
         replace incomelevelname = "Low income"  if `match' == "BEN"  
         replace incomelevelname = "Low income"  if `match' == "BFA"  
         replace incomelevelname = "Lower middle income"  if `match' == "BGD"  
         replace incomelevelname = "Upper middle income"  if `match' == "BGR"  
         replace incomelevelname = "Aggregates"  if `match' == "BHI"  
         replace incomelevelname = "High income"  if `match' == "BHR"  
         replace incomelevelname = "High income"  if `match' == "BHS"  
         replace incomelevelname = "Upper middle income"  if `match' == "BIH"  
         replace incomelevelname = "Aggregates"  if `match' == "BLA"  
         replace incomelevelname = "Upper middle income"  if `match' == "BLR"  
         replace incomelevelname = "Upper middle income"  if `match' == "BLZ"  
         replace incomelevelname = "Aggregates"  if `match' == "BMN"  
         replace incomelevelname = "High income"  if `match' == "BMU"  
         replace incomelevelname = "Lower middle income"  if `match' == "BOL"  
         replace incomelevelname = "Upper middle income"  if `match' == "BRA"  
         replace incomelevelname = "High income"  if `match' == "BRB"  
         replace incomelevelname = "High income"  if `match' == "BRN"  
         replace incomelevelname = "Aggregates"  if `match' == "BSS"  
         replace incomelevelname = "Lower middle income"  if `match' == "BTN"  
         replace incomelevelname = "Upper middle income"  if `match' == "BWA"  
         replace incomelevelname = "Aggregates"  if `match' == "CAA"  
         replace incomelevelname = "Low income"  if `match' == "CAF"  
         replace incomelevelname = "High income"  if `match' == "CAN"  
         replace incomelevelname = "Aggregates"  if `match' == "CEA"  
         replace incomelevelname = "Aggregates"  if `match' == "CEB"  
         replace incomelevelname = "Aggregates"  if `match' == "CEU"  
         replace incomelevelname = "High income"  if `match' == "CHE"  
         replace incomelevelname = "High income"  if `match' == "CHI"  
         replace incomelevelname = "High income"  if `match' == "CHL"  
         replace incomelevelname = "Upper middle income"  if `match' == "CHN"  
         replace incomelevelname = "Lower middle income"  if `match' == "CIV"  
         replace incomelevelname = "Aggregates"  if `match' == "CLA"  
         replace incomelevelname = "Aggregates"  if `match' == "CME"  
         replace incomelevelname = "Lower middle income"  if `match' == "CMR"  
         replace incomelevelname = "Low income"  if `match' == "COD"  
         replace incomelevelname = "Lower middle income"  if `match' == "COG"  
         replace incomelevelname = "Upper middle income"  if `match' == "COL"  
         replace incomelevelname = "Lower middle income"  if `match' == "COM"  
         replace incomelevelname = "Lower middle income"  if `match' == "CPV"  
         replace incomelevelname = "Upper middle income"  if `match' == "CRI"  
         replace incomelevelname = "Aggregates"  if `match' == "CSA"  
         replace incomelevelname = "Aggregates"  if `match' == "CSS"  
         replace incomelevelname = "Upper middle income"  if `match' == "CUB"  
         replace incomelevelname = "High income"  if `match' == "CUW"  
         replace incomelevelname = "High income"  if `match' == "CYM"  
         replace incomelevelname = "High income"  if `match' == "CYP"  
         replace incomelevelname = "High income"  if `match' == "CZE"  
         replace incomelevelname = "Aggregates"  if `match' == "DEA"  
         replace incomelevelname = "Aggregates"  if `match' == "DEC"  
         replace incomelevelname = "High income"  if `match' == "DEU"  
         replace incomelevelname = "Aggregates"  if `match' == "DFS"  
         replace incomelevelname = "Lower middle income"  if `match' == "DJI"  
         replace incomelevelname = "Aggregates"  if `match' == "DLA"  
         replace incomelevelname = "Upper middle income"  if `match' == "DMA"  
         replace incomelevelname = "Aggregates"  if `match' == "DMN"  
         replace incomelevelname = "Aggregates"  if `match' == "DNF"  
         replace incomelevelname = "High income"  if `match' == "DNK"  
         replace incomelevelname = "Aggregates"  if `match' == "DNS"  
         replace incomelevelname = "Upper middle income"  if `match' == "DOM"  
         replace incomelevelname = "Aggregates"  if `match' == "DSA"  
         replace incomelevelname = "Aggregates"  if `match' == "DSF"  
         replace incomelevelname = "Aggregates"  if `match' == "DSS"  
         replace incomelevelname = "Aggregates"  if `match' == "DXS"  
         replace incomelevelname = "Upper middle income"  if `match' == "DZA"  
         replace incomelevelname = "Aggregates"  if `match' == "EAP"  
         replace incomelevelname = "Aggregates"  if `match' == "EAR"  
         replace incomelevelname = "Aggregates"  if `match' == "EAS"  
         replace incomelevelname = "Aggregates"  if `match' == "ECA"  
         replace incomelevelname = "Aggregates"  if `match' == "ECS"  
         replace incomelevelname = "Upper middle income"  if `match' == "ECU"  
         replace incomelevelname = "Lower middle income"  if `match' == "EGY"  
         replace incomelevelname = "Aggregates"  if `match' == "EMU"  
         replace incomelevelname = "Low income"  if `match' == "ERI"  
         replace incomelevelname = "High income"  if `match' == "ESP"  
         replace incomelevelname = "High income"  if `match' == "EST"  
         replace incomelevelname = "Low income"  if `match' == "ETH"  
         replace incomelevelname = "Aggregates"  if `match' == "EUU"  
         replace incomelevelname = "Aggregates"  if `match' == "FCS"  
         replace incomelevelname = "High income"  if `match' == "FIN"  
         replace incomelevelname = "Upper middle income"  if `match' == "FJI"  
         replace incomelevelname = "High income"  if `match' == "FRA"  
         replace incomelevelname = "High income"  if `match' == "FRO"  
         replace incomelevelname = "Lower middle income"  if `match' == "FSM"  
         replace incomelevelname = "Aggregates"  if `match' == "FXS"  
         replace incomelevelname = "Upper middle income"  if `match' == "GAB"  
         replace incomelevelname = "High income"  if `match' == "GBR"  
         replace incomelevelname = "Upper middle income"  if `match' == "GEO"  
         replace incomelevelname = "Lower middle income"  if `match' == "GHA"  
         replace incomelevelname = "High income"  if `match' == "GIB"  
         replace incomelevelname = "Low income"  if `match' == "GIN"  
         replace incomelevelname = "Low income"  if `match' == "GMB"  
         replace incomelevelname = "Low income"  if `match' == "GNB"  
         replace incomelevelname = "Upper middle income"  if `match' == "GNQ"  
         replace incomelevelname = "High income"  if `match' == "GRC"  
         replace incomelevelname = "Upper middle income"  if `match' == "GRD"  
         replace incomelevelname = "High income"  if `match' == "GRL"  
         replace incomelevelname = "Upper middle income"  if `match' == "GTM"  
         replace incomelevelname = "High income"  if `match' == "GUM"  
         replace incomelevelname = "Upper middle income"  if `match' == "GUY"  
         replace incomelevelname = "Aggregates"  if `match' == "HIC"  
         replace incomelevelname = "High income"  if `match' == "HKG"  
         replace incomelevelname = "Lower middle income"  if `match' == "HND"  
         replace incomelevelname = "Aggregates"  if `match' == "HPC"  
         replace incomelevelname = "High income"  if `match' == "HRV"  
         replace incomelevelname = "Low income"  if `match' == "HTI"  
         replace incomelevelname = "High income"  if `match' == "HUN"  
         replace incomelevelname = "Aggregates"  if `match' == "IBB"  
         replace incomelevelname = "Aggregates"  if `match' == "IBD"  
         replace incomelevelname = "Aggregates"  if `match' == "IBT"  
         replace incomelevelname = "Aggregates"  if `match' == "IDA"  
         replace incomelevelname = "Aggregates"  if `match' == "IDB"  
         replace incomelevelname = "Lower middle income"  if `match' == "IDN"  
         replace incomelevelname = "Aggregates"  if `match' == "IDX"  
         replace incomelevelname = "High income"  if `match' == "IMN"  
         replace incomelevelname = "Lower middle income"  if `match' == "IND"  
         replace incomelevelname = "Aggregates"  if `match' == "INX"  
         replace incomelevelname = "High income"  if `match' == "IRL"  
         replace incomelevelname = "Upper middle income"  if `match' == "IRN"  
         replace incomelevelname = "Upper middle income"  if `match' == "IRQ"  
         replace incomelevelname = "High income"  if `match' == "ISL"  
         replace incomelevelname = "High income"  if `match' == "ISR"  
         replace incomelevelname = "High income"  if `match' == "ITA"  
         replace incomelevelname = "Upper middle income"  if `match' == "JAM"  
         replace incomelevelname = "Upper middle income"  if `match' == "JOR"  
         replace incomelevelname = "High income"  if `match' == "JPN"  
         replace incomelevelname = "Upper middle income"  if `match' == "KAZ"  
         replace incomelevelname = "Lower middle income"  if `match' == "KEN"  
         replace incomelevelname = "Lower middle income"  if `match' == "KGZ"  
         replace incomelevelname = "Lower middle income"  if `match' == "KHM"  
         replace incomelevelname = "Lower middle income"  if `match' == "KIR"  
         replace incomelevelname = "High income"  if `match' == "KNA"  
         replace incomelevelname = "High income"  if `match' == "KOR"  
         replace incomelevelname = "High income"  if `match' == "KWT"  
         replace incomelevelname = "Aggregates"  if `match' == "LAC"  
         replace incomelevelname = "Lower middle income"  if `match' == "LAO"  
         replace incomelevelname = "Upper middle income"  if `match' == "LBN"  
         replace incomelevelname = "Low income"  if `match' == "LBR"  
         replace incomelevelname = "Upper middle income"  if `match' == "LBY"  
         replace incomelevelname = "Upper middle income"  if `match' == "LCA"  
         replace incomelevelname = "Aggregates"  if `match' == "LCN"  
         replace incomelevelname = "Aggregates"  if `match' == "LCR"  
         replace incomelevelname = "Aggregates"  if `match' == "LDC"  
         replace incomelevelname = "Aggregates"  if `match' == "LIC"  
         replace incomelevelname = "High income"  if `match' == "LIE"  
         replace incomelevelname = "Upper middle income"  if `match' == "LKA"  
         replace incomelevelname = "Aggregates"  if `match' == "LMC"  
         replace incomelevelname = "Aggregates"  if `match' == "LMY"  
         replace incomelevelname = "Lower middle income"  if `match' == "LSO"  
         replace incomelevelname = "Aggregates"  if `match' == "LTE"  
         replace incomelevelname = "High income"  if `match' == "LTU"  
         replace incomelevelname = "High income"  if `match' == "LUX"  
         replace incomelevelname = "High income"  if `match' == "LVA"  
         replace incomelevelname = "High income"  if `match' == "MAC"  
         replace incomelevelname = "High income"  if `match' == "MAF"  
         replace incomelevelname = "Lower middle income"  if `match' == "MAR"  
         replace incomelevelname = "Aggregates"  if `match' == "MCA"  
         replace incomelevelname = "High income"  if `match' == "MCO"  
         replace incomelevelname = "Lower middle income"  if `match' == "MDA"  
         replace incomelevelname = "Aggregates"  if `match' == "MDE"  
         replace incomelevelname = "Low income"  if `match' == "MDG"  
         replace incomelevelname = "Upper middle income"  if `match' == "MDV"  
         replace incomelevelname = "Aggregates"  if `match' == "MEA"  
         replace incomelevelname = "Upper middle income"  if `match' == "MEX"  
         replace incomelevelname = "Upper middle income"  if `match' == "MHL"  
         replace incomelevelname = "Aggregates"  if `match' == "MIC"  
         replace incomelevelname = "Upper middle income"  if `match' == "MKD"  
         replace incomelevelname = "Low income"  if `match' == "MLI"  
         replace incomelevelname = "High income"  if `match' == "MLT"  
         replace incomelevelname = "Lower middle income"  if `match' == "MMR"  
         replace incomelevelname = "Aggregates"  if `match' == "MNA"  
         replace incomelevelname = "Upper middle income"  if `match' == "MNE"  
         replace incomelevelname = "Lower middle income"  if `match' == "MNG"  
         replace incomelevelname = "High income"  if `match' == "MNP"  
         replace incomelevelname = "Low income"  if `match' == "MOZ"  
         replace incomelevelname = "Lower middle income"  if `match' == "MRT"  
         replace incomelevelname = "Upper middle income"  if `match' == "MUS"  
         replace incomelevelname = "Low income"  if `match' == "MWI"  
         replace incomelevelname = "Upper middle income"  if `match' == "MYS"  
         replace incomelevelname = "Aggregates"  if `match' == "NAC"  
         replace incomelevelname = "Aggregates"  if `match' == "NAF"  
         replace incomelevelname = "Upper middle income"  if `match' == "NAM"  
         replace incomelevelname = "High income"  if `match' == "NCL"  
         replace incomelevelname = "Low income"  if `match' == "NER"  
         replace incomelevelname = "Lower middle income"  if `match' == "NGA"  
         replace incomelevelname = "Lower middle income"  if `match' == "NIC"  
         replace incomelevelname = "High income"  if `match' == "NLD"  
         replace incomelevelname = "Aggregates"  if `match' == "NLS"  
         replace incomelevelname = "High income"  if `match' == "NOR"  
         replace incomelevelname = "Low income"  if `match' == "NPL"  
         replace incomelevelname = "Aggregates"  if `match' == "NRS"  
         replace incomelevelname = "Upper middle income"  if `match' == "NRU"  
         replace incomelevelname = "Aggregates"  if `match' == "NXS"  
         replace incomelevelname = "High income"  if `match' == "NZL"  
         replace incomelevelname = "Aggregates"  if `match' == "OED"  
         replace incomelevelname = "High income"  if `match' == "OMN"  
         replace incomelevelname = "Aggregates"  if `match' == "OSS"  
         replace incomelevelname = "Lower middle income"  if `match' == "PAK"  
         replace incomelevelname = "High income"  if `match' == "PAN"  
         replace incomelevelname = "Upper middle income"  if `match' == "PER"  
         replace incomelevelname = "Lower middle income"  if `match' == "PHL"  
         replace incomelevelname = "High income"  if `match' == "PLW"  
         replace incomelevelname = "Lower middle income"  if `match' == "PNG"  
         replace incomelevelname = "High income"  if `match' == "POL"  
         replace incomelevelname = "Aggregates"  if `match' == "PRE"  
         replace incomelevelname = "High income"  if `match' == "PRI"  
         replace incomelevelname = "Low income"  if `match' == "PRK"  
         replace incomelevelname = "High income"  if `match' == "PRT"  
         replace incomelevelname = "Upper middle income"  if `match' == "PRY"  
         replace incomelevelname = "Lower middle income"  if `match' == "PSE"  
         replace incomelevelname = "Aggregates"  if `match' == "PSS"  
         replace incomelevelname = "Aggregates"  if `match' == "PST"  
         replace incomelevelname = "High income"  if `match' == "PYF"  
         replace incomelevelname = "High income"  if `match' == "QAT"  
         replace incomelevelname = "Upper middle income"  if `match' == "ROU"  
         replace incomelevelname = "Aggregates"  if `match' == "RRS"  
         replace incomelevelname = "Aggregates"  if `match' == "RSO"  
         replace incomelevelname = "Upper middle income"  if `match' == "RUS"  
         replace incomelevelname = "Low income"  if `match' == "RWA"  
         replace incomelevelname = "Aggregates"  if `match' == "SAS"  
         replace incomelevelname = "High income"  if `match' == "SAU"  
         replace incomelevelname = "Aggregates"  if `match' == "SCE"  
         replace incomelevelname = "Lower middle income"  if `match' == "SDN"  
         replace incomelevelname = "Lower middle income"  if `match' == "SEN"  
         replace incomelevelname = "High income"  if `match' == "SGP"  
         replace incomelevelname = "Lower middle income"  if `match' == "SLB"  
         replace incomelevelname = "Low income"  if `match' == "SLE"  
         replace incomelevelname = "Lower middle income"  if `match' == "SLV"  
         replace incomelevelname = "High income"  if `match' == "SMR"  
         replace incomelevelname = "Low income"  if `match' == "SOM"  
         replace incomelevelname = "Upper middle income"  if `match' == "SRB"  
         replace incomelevelname = "Aggregates"  if `match' == "SSA"  
         replace incomelevelname = "Low income"  if `match' == "SSD"  
         replace incomelevelname = "Aggregates"  if `match' == "SSF"  
         replace incomelevelname = "Aggregates"  if `match' == "SST"  
         replace incomelevelname = "Lower middle income"  if `match' == "STP"  
         replace incomelevelname = "Upper middle income"  if `match' == "SUR"  
         replace incomelevelname = "High income"  if `match' == "SVK"  
         replace incomelevelname = "High income"  if `match' == "SVN"  
         replace incomelevelname = "High income"  if `match' == "SWE"  
         replace incomelevelname = "Lower middle income"  if `match' == "SWZ"  
         replace incomelevelname = "High income"  if `match' == "SXM"  
         replace incomelevelname = "Aggregates"  if `match' == "SXZ"  
         replace incomelevelname = "High income"  if `match' == "SYC"  
         replace incomelevelname = "Low income"  if `match' == "SYR"  
         replace incomelevelname = "High income"  if `match' == "TCA"  
         replace incomelevelname = "Low income"  if `match' == "TCD"  
         replace incomelevelname = "Aggregates"  if `match' == "TEA"  
         replace incomelevelname = "Aggregates"  if `match' == "TEC"  
         replace incomelevelname = "Low income"  if `match' == "TGO"  
         replace incomelevelname = "Upper middle income"  if `match' == "THA"  
         replace incomelevelname = "Low income"  if `match' == "TJK"  
         replace incomelevelname = "Upper middle income"  if `match' == "TKM"  
         replace incomelevelname = "Aggregates"  if `match' == "TLA"  
         replace incomelevelname = "Lower middle income"  if `match' == "TLS"  
         replace incomelevelname = "Aggregates"  if `match' == "TMN"  
         replace incomelevelname = "Upper middle income"  if `match' == "TON"  
         replace incomelevelname = "Aggregates"  if `match' == "TSA"  
         replace incomelevelname = "Aggregates"  if `match' == "TSS"  
         replace incomelevelname = "High income"  if `match' == "TTO"  
         replace incomelevelname = "Lower middle income"  if `match' == "TUN"  
         replace incomelevelname = "Upper middle income"  if `match' == "TUR"  
         replace incomelevelname = "Upper middle income"  if `match' == "TUV"  
         replace incomelevelname = "High income"  if `match' == "TWN"  
         replace incomelevelname = "Low income"  if `match' == "TZA"  
         replace incomelevelname = "Low income"  if `match' == "UGA"  
         replace incomelevelname = "Lower middle income"  if `match' == "UKR"  
         replace incomelevelname = "Aggregates"  if `match' == "UMC"  
         replace incomelevelname = "High income"  if `match' == "URY"  
         replace incomelevelname = "High income"  if `match' == "USA"  
         replace incomelevelname = "Lower middle income"  if `match' == "UZB"  
         replace incomelevelname = "Upper middle income"  if `match' == "VCT"  
         replace incomelevelname = "Upper middle income"  if `match' == "VEN"  
         replace incomelevelname = "High income"  if `match' == "VGB"  
         replace incomelevelname = "High income"  if `match' == "VIR"  
         replace incomelevelname = "Lower middle income"  if `match' == "VNM"  
         replace incomelevelname = "Lower middle income"  if `match' == "VUT"  
         replace incomelevelname = "Aggregates"  if `match' == "WLD"  
         replace incomelevelname = "Upper middle income"  if `match' == "WSM"  
         replace incomelevelname = "Upper middle income"  if `match' == "XKX"  
         replace incomelevelname = "Aggregates"  if `match' == "XZN"  
         replace incomelevelname = "Low income"  if `match' == "YEM"  
         replace incomelevelname = "Upper middle income"  if `match' == "ZAF"  
         replace incomelevelname = "Lower middle income"  if `match' == "ZMB"  
  
******************  Lable: incomelevelname ******************
  
     lab var incomelevelname     "Income Level Name" 
 }        
  
 ****************************************************** 
  
 end 
