*! _wbod_tmpfile3 <26 Oct 2019 : 16:12:43>                 by João Pedro Azevedo
*                 auto generated and updated using _update_countrymetadata.ado 
  
 program define _wbod_tmpfile3 
  
     syntax , match(varname) [  lendingtype lendingtype_iso2 lendingtypename capital longitude latitude  ] 
  
 ******************  Values: lendingtype ****************** 
  
 qui if ("`lendingtype'" == "lendingtype") {      
  
         gen lendingtype = ""  
         replace lendingtype = "LNX"  if `match' == "ABW"  
         replace lendingtype = "IDX"  if `match' == "AFG"  
         replace lendingtype = "IBD"  if `match' == "AGO"  
         replace lendingtype = "IBD"  if `match' == "ALB"  
         replace lendingtype = "LNX"  if `match' == "AND"  
         replace lendingtype = "LNX"  if `match' == "ARE"  
         replace lendingtype = "IBD"  if `match' == "ARG"  
         replace lendingtype = "IBD"  if `match' == "ARM"  
         replace lendingtype = "LNX"  if `match' == "ASM"  
         replace lendingtype = "IBD"  if `match' == "ATG"  
         replace lendingtype = "LNX"  if `match' == "AUS"  
         replace lendingtype = "LNX"  if `match' == "AUT"  
         replace lendingtype = "IBD"  if `match' == "AZE"  
         replace lendingtype = "IDX"  if `match' == "BDI"  
         replace lendingtype = "LNX"  if `match' == "BEL"  
         replace lendingtype = "IDX"  if `match' == "BEN"  
         replace lendingtype = "IDX"  if `match' == "BFA"  
         replace lendingtype = "IDX"  if `match' == "BGD"  
         replace lendingtype = "IBD"  if `match' == "BGR"  
         replace lendingtype = "LNX"  if `match' == "BHR"  
         replace lendingtype = "LNX"  if `match' == "BHS"  
         replace lendingtype = "IBD"  if `match' == "BIH"  
         replace lendingtype = "IBD"  if `match' == "BLR"  
         replace lendingtype = "IBD"  if `match' == "BLZ"  
         replace lendingtype = "LNX"  if `match' == "BMU"  
         replace lendingtype = "IBD"  if `match' == "BOL"  
         replace lendingtype = "IBD"  if `match' == "BRA"  
         replace lendingtype = "LNX"  if `match' == "BRB"  
         replace lendingtype = "LNX"  if `match' == "BRN"  
         replace lendingtype = "IDX"  if `match' == "BTN"  
         replace lendingtype = "IBD"  if `match' == "BWA"  
         replace lendingtype = "IDX"  if `match' == "CAF"  
         replace lendingtype = "LNX"  if `match' == "CAN"  
         replace lendingtype = "LNX"  if `match' == "CHE"  
         replace lendingtype = "LNX"  if `match' == "CHI"  
         replace lendingtype = "IBD"  if `match' == "CHL"  
         replace lendingtype = "IBD"  if `match' == "CHN"  
         replace lendingtype = "IDX"  if `match' == "CIV"  
         replace lendingtype = "IDB"  if `match' == "CMR"  
         replace lendingtype = "IDX"  if `match' == "COD"  
         replace lendingtype = "IDB"  if `match' == "COG"  
         replace lendingtype = "IBD"  if `match' == "COL"  
         replace lendingtype = "IDX"  if `match' == "COM"  
         replace lendingtype = "IDB"  if `match' == "CPV"  
         replace lendingtype = "IBD"  if `match' == "CRI"  
         replace lendingtype = "LNX"  if `match' == "CUB"  
         replace lendingtype = "LNX"  if `match' == "CUW"  
         replace lendingtype = "LNX"  if `match' == "CYM"  
         replace lendingtype = "LNX"  if `match' == "CYP"  
         replace lendingtype = "LNX"  if `match' == "CZE"  
         replace lendingtype = "LNX"  if `match' == "DEU"  
         replace lendingtype = "IDX"  if `match' == "DJI"  
         replace lendingtype = "IDB"  if `match' == "DMA"  
         replace lendingtype = "LNX"  if `match' == "DNK"  
         replace lendingtype = "IBD"  if `match' == "DOM"  
         replace lendingtype = "IBD"  if `match' == "DZA"  
         replace lendingtype = "IBD"  if `match' == "ECU"  
         replace lendingtype = "IBD"  if `match' == "EGY"  
         replace lendingtype = "IDX"  if `match' == "ERI"  
         replace lendingtype = "LNX"  if `match' == "ESP"  
         replace lendingtype = "LNX"  if `match' == "EST"  
         replace lendingtype = "IDX"  if `match' == "ETH"  
         replace lendingtype = "LNX"  if `match' == "FIN"  
         replace lendingtype = "IDB"  if `match' == "FJI"  
         replace lendingtype = "LNX"  if `match' == "FRA"  
         replace lendingtype = "LNX"  if `match' == "FRO"  
         replace lendingtype = "IDX"  if `match' == "FSM"  
         replace lendingtype = "IBD"  if `match' == "GAB"  
         replace lendingtype = "LNX"  if `match' == "GBR"  
         replace lendingtype = "IBD"  if `match' == "GEO"  
         replace lendingtype = "IDX"  if `match' == "GHA"  
         replace lendingtype = "LNX"  if `match' == "GIB"  
         replace lendingtype = "IDX"  if `match' == "GIN"  
         replace lendingtype = "IDX"  if `match' == "GMB"  
         replace lendingtype = "IDX"  if `match' == "GNB"  
         replace lendingtype = "IBD"  if `match' == "GNQ"  
         replace lendingtype = "LNX"  if `match' == "GRC"  
         replace lendingtype = "IDB"  if `match' == "GRD"  
         replace lendingtype = "LNX"  if `match' == "GRL"  
         replace lendingtype = "IBD"  if `match' == "GTM"  
         replace lendingtype = "LNX"  if `match' == "GUM"  
         replace lendingtype = "IDX"  if `match' == "GUY"  
         replace lendingtype = "LNX"  if `match' == "HKG"  
         replace lendingtype = "IDX"  if `match' == "HND"  
         replace lendingtype = "IBD"  if `match' == "HRV"  
         replace lendingtype = "IDX"  if `match' == "HTI"  
         replace lendingtype = "LNX"  if `match' == "HUN"  
         replace lendingtype = "IBD"  if `match' == "IDN"  
         replace lendingtype = "LNX"  if `match' == "IMN"  
         replace lendingtype = "IBD"  if `match' == "IND"  
         replace lendingtype = "LNX"  if `match' == "IRL"  
         replace lendingtype = "IBD"  if `match' == "IRN"  
         replace lendingtype = "IBD"  if `match' == "IRQ"  
         replace lendingtype = "LNX"  if `match' == "ISL"  
         replace lendingtype = "LNX"  if `match' == "ISR"  
         replace lendingtype = "LNX"  if `match' == "ITA"  
         replace lendingtype = "IBD"  if `match' == "JAM"  
         replace lendingtype = "IBD"  if `match' == "JOR"  
         replace lendingtype = "LNX"  if `match' == "JPN"  
         replace lendingtype = "IBD"  if `match' == "KAZ"  
         replace lendingtype = "IDB"  if `match' == "KEN"  
         replace lendingtype = "IDX"  if `match' == "KGZ"  
         replace lendingtype = "IDX"  if `match' == "KHM"  
         replace lendingtype = "IDX"  if `match' == "KIR"  
         replace lendingtype = "IBD"  if `match' == "KNA"  
         replace lendingtype = "LNX"  if `match' == "KOR"  
         replace lendingtype = "LNX"  if `match' == "KWT"  
         replace lendingtype = "IDX"  if `match' == "LAO"  
         replace lendingtype = "IBD"  if `match' == "LBN"  
         replace lendingtype = "IDX"  if `match' == "LBR"  
         replace lendingtype = "IBD"  if `match' == "LBY"  
         replace lendingtype = "IDB"  if `match' == "LCA"  
         replace lendingtype = "LNX"  if `match' == "LIE"  
         replace lendingtype = "IBD"  if `match' == "LKA"  
         replace lendingtype = "IDX"  if `match' == "LSO"  
         replace lendingtype = "LNX"  if `match' == "LTU"  
         replace lendingtype = "LNX"  if `match' == "LUX"  
         replace lendingtype = "LNX"  if `match' == "LVA"  
         replace lendingtype = "LNX"  if `match' == "MAC"  
         replace lendingtype = "LNX"  if `match' == "MAF"  
         replace lendingtype = "IBD"  if `match' == "MAR"  
         replace lendingtype = "LNX"  if `match' == "MCO"  
         replace lendingtype = "IDB"  if `match' == "MDA"  
         replace lendingtype = "IDX"  if `match' == "MDG"  
         replace lendingtype = "IDX"  if `match' == "MDV"  
         replace lendingtype = "IBD"  if `match' == "MEX"  
         replace lendingtype = "IDX"  if `match' == "MHL"  
         replace lendingtype = "IBD"  if `match' == "MKD"  
         replace lendingtype = "IDX"  if `match' == "MLI"  
         replace lendingtype = "LNX"  if `match' == "MLT"  
         replace lendingtype = "IDX"  if `match' == "MMR"  
         replace lendingtype = "IBD"  if `match' == "MNE"  
         replace lendingtype = "IDB"  if `match' == "MNG"  
         replace lendingtype = "LNX"  if `match' == "MNP"  
         replace lendingtype = "IDX"  if `match' == "MOZ"  
         replace lendingtype = "IDX"  if `match' == "MRT"  
         replace lendingtype = "IBD"  if `match' == "MUS"  
         replace lendingtype = "IDX"  if `match' == "MWI"  
         replace lendingtype = "IBD"  if `match' == "MYS"  
         replace lendingtype = "IBD"  if `match' == "NAM"  
         replace lendingtype = "LNX"  if `match' == "NCL"  
         replace lendingtype = "IDX"  if `match' == "NER"  
         replace lendingtype = "IDB"  if `match' == "NGA"  
         replace lendingtype = "IDX"  if `match' == "NIC"  
         replace lendingtype = "LNX"  if `match' == "NLD"  
         replace lendingtype = "LNX"  if `match' == "NOR"  
         replace lendingtype = "IDX"  if `match' == "NPL"  
         replace lendingtype = "IBD"  if `match' == "NRU"  
         replace lendingtype = "LNX"  if `match' == "NZL"  
         replace lendingtype = "LNX"  if `match' == "OMN"  
         replace lendingtype = "IDB"  if `match' == "PAK"  
         replace lendingtype = "IBD"  if `match' == "PAN"  
         replace lendingtype = "IBD"  if `match' == "PER"  
         replace lendingtype = "IBD"  if `match' == "PHL"  
         replace lendingtype = "IBD"  if `match' == "PLW"  
         replace lendingtype = "IDB"  if `match' == "PNG"  
         replace lendingtype = "IBD"  if `match' == "POL"  
         replace lendingtype = "LNX"  if `match' == "PRI"  
         replace lendingtype = "LNX"  if `match' == "PRK"  
         replace lendingtype = "LNX"  if `match' == "PRT"  
         replace lendingtype = "IBD"  if `match' == "PRY"  
         replace lendingtype = "LNX"  if `match' == "PSE"  
         replace lendingtype = "LNX"  if `match' == "PYF"  
         replace lendingtype = "LNX"  if `match' == "QAT"  
         replace lendingtype = "IBD"  if `match' == "ROU"  
         replace lendingtype = "IBD"  if `match' == "RUS"  
         replace lendingtype = "IDX"  if `match' == "RWA"  
         replace lendingtype = "LNX"  if `match' == "SAU"  
         replace lendingtype = "IDX"  if `match' == "SDN"  
         replace lendingtype = "IDX"  if `match' == "SEN"  
         replace lendingtype = "LNX"  if `match' == "SGP"  
         replace lendingtype = "IDX"  if `match' == "SLB"  
         replace lendingtype = "IDX"  if `match' == "SLE"  
         replace lendingtype = "IBD"  if `match' == "SLV"  
         replace lendingtype = "LNX"  if `match' == "SMR"  
         replace lendingtype = "IDX"  if `match' == "SOM"  
         replace lendingtype = "IBD"  if `match' == "SRB"  
         replace lendingtype = "IDX"  if `match' == "SSD"  
         replace lendingtype = "IDX"  if `match' == "STP"  
         replace lendingtype = "IBD"  if `match' == "SUR"  
         replace lendingtype = "LNX"  if `match' == "SVK"  
         replace lendingtype = "LNX"  if `match' == "SVN"  
         replace lendingtype = "LNX"  if `match' == "SWE"  
         replace lendingtype = "IBD"  if `match' == "SWZ"  
         replace lendingtype = "LNX"  if `match' == "SXM"  
         replace lendingtype = "IBD"  if `match' == "SYC"  
         replace lendingtype = "IDX"  if `match' == "SYR"  
         replace lendingtype = "LNX"  if `match' == "TCA"  
         replace lendingtype = "IDX"  if `match' == "TCD"  
         replace lendingtype = "IDX"  if `match' == "TGO"  
         replace lendingtype = "IBD"  if `match' == "THA"  
         replace lendingtype = "IDX"  if `match' == "TJK"  
         replace lendingtype = "IBD"  if `match' == "TKM"  
         replace lendingtype = "IDB"  if `match' == "TLS"  
         replace lendingtype = "IDX"  if `match' == "TON"  
         replace lendingtype = "IBD"  if `match' == "TTO"  
         replace lendingtype = "IBD"  if `match' == "TUN"  
         replace lendingtype = "IBD"  if `match' == "TUR"  
         replace lendingtype = "IDX"  if `match' == "TUV"  
         replace lendingtype = "LNX"  if `match' == "TWN"  
         replace lendingtype = "IDX"  if `match' == "TZA"  
         replace lendingtype = "IDX"  if `match' == "UGA"  
         replace lendingtype = "IBD"  if `match' == "UKR"  
         replace lendingtype = "IBD"  if `match' == "URY"  
         replace lendingtype = "LNX"  if `match' == "USA"  
         replace lendingtype = "IDB"  if `match' == "UZB"  
         replace lendingtype = "IDB"  if `match' == "VCT"  
         replace lendingtype = "IBD"  if `match' == "VEN"  
         replace lendingtype = "LNX"  if `match' == "VGB"  
         replace lendingtype = "LNX"  if `match' == "VIR"  
         replace lendingtype = "IBD"  if `match' == "VNM"  
         replace lendingtype = "IDX"  if `match' == "VUT"  
         replace lendingtype = "IDX"  if `match' == "WSM"  
         replace lendingtype = "IDX"  if `match' == "XKX"  
         replace lendingtype = "IDX"  if `match' == "YEM"  
         replace lendingtype = "IBD"  if `match' == "ZAF"  
         replace lendingtype = "IDX"  if `match' == "ZMB"  
  
******************  Lable: lendingtype ******************
  
     lab var lendingtype                 "Lending Type Code" 
 }        
  
 ****************************************************** 
  
 ******************  Values: lendingtype_iso2 ****************** 
  
 qui if ("`lendingtype_iso2'" == "lendingtype_iso2") {      
  
         gen lendingtype_iso2 = ""  
         replace lendingtype_iso2 = "XX"  if `match' == "ABW"  
         replace lendingtype_iso2 = "XI"  if `match' == "AFG"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "AFR"  
         replace lendingtype_iso2 = "XF"  if `match' == "AGO"  
         replace lendingtype_iso2 = "XF"  if `match' == "ALB"  
         replace lendingtype_iso2 = "XX"  if `match' == "AND"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "ANR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "ARB"  
         replace lendingtype_iso2 = "XX"  if `match' == "ARE"  
         replace lendingtype_iso2 = "XF"  if `match' == "ARG"  
         replace lendingtype_iso2 = "XF"  if `match' == "ARM"  
         replace lendingtype_iso2 = "XX"  if `match' == "ASM"  
         replace lendingtype_iso2 = "XF"  if `match' == "ATG"  
         replace lendingtype_iso2 = "XX"  if `match' == "AUS"  
         replace lendingtype_iso2 = "XX"  if `match' == "AUT"  
         replace lendingtype_iso2 = "XF"  if `match' == "AZE"  
         replace lendingtype_iso2 = "XI"  if `match' == "BDI"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "BEA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "BEC"  
         replace lendingtype_iso2 = "XX"  if `match' == "BEL"  
         replace lendingtype_iso2 = "XI"  if `match' == "BEN"  
         replace lendingtype_iso2 = "XI"  if `match' == "BFA"  
         replace lendingtype_iso2 = "XI"  if `match' == "BGD"  
         replace lendingtype_iso2 = "XF"  if `match' == "BGR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "BHI"  
         replace lendingtype_iso2 = "XX"  if `match' == "BHR"  
         replace lendingtype_iso2 = "XX"  if `match' == "BHS"  
         replace lendingtype_iso2 = "XF"  if `match' == "BIH"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "BLA"  
         replace lendingtype_iso2 = "XF"  if `match' == "BLR"  
         replace lendingtype_iso2 = "XF"  if `match' == "BLZ"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "BMN"  
         replace lendingtype_iso2 = "XX"  if `match' == "BMU"  
         replace lendingtype_iso2 = "XF"  if `match' == "BOL"  
         replace lendingtype_iso2 = "XF"  if `match' == "BRA"  
         replace lendingtype_iso2 = "XX"  if `match' == "BRB"  
         replace lendingtype_iso2 = "XX"  if `match' == "BRN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "BSS"  
         replace lendingtype_iso2 = "XI"  if `match' == "BTN"  
         replace lendingtype_iso2 = "XF"  if `match' == "BWA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CAA"  
         replace lendingtype_iso2 = "XI"  if `match' == "CAF"  
         replace lendingtype_iso2 = "XX"  if `match' == "CAN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CEA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CEB"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CEU"  
         replace lendingtype_iso2 = "XX"  if `match' == "CHE"  
         replace lendingtype_iso2 = "XX"  if `match' == "CHI"  
         replace lendingtype_iso2 = "XF"  if `match' == "CHL"  
         replace lendingtype_iso2 = "XF"  if `match' == "CHN"  
         replace lendingtype_iso2 = "XI"  if `match' == "CIV"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CLA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CME"  
         replace lendingtype_iso2 = "XH"  if `match' == "CMR"  
         replace lendingtype_iso2 = "XI"  if `match' == "COD"  
         replace lendingtype_iso2 = "XH"  if `match' == "COG"  
         replace lendingtype_iso2 = "XF"  if `match' == "COL"  
         replace lendingtype_iso2 = "XI"  if `match' == "COM"  
         replace lendingtype_iso2 = "XH"  if `match' == "CPV"  
         replace lendingtype_iso2 = "XF"  if `match' == "CRI"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CSA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "CSS"  
         replace lendingtype_iso2 = "XX"  if `match' == "CUB"  
         replace lendingtype_iso2 = "XX"  if `match' == "CUW"  
         replace lendingtype_iso2 = "XX"  if `match' == "CYM"  
         replace lendingtype_iso2 = "XX"  if `match' == "CYP"  
         replace lendingtype_iso2 = "XX"  if `match' == "CZE"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DEA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DEC"  
         replace lendingtype_iso2 = "XX"  if `match' == "DEU"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DFS"  
         replace lendingtype_iso2 = "XI"  if `match' == "DJI"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DLA"  
         replace lendingtype_iso2 = "XH"  if `match' == "DMA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DMN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DNF"  
         replace lendingtype_iso2 = "XX"  if `match' == "DNK"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DNS"  
         replace lendingtype_iso2 = "XF"  if `match' == "DOM"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DSA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DSF"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DSS"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "DXS"  
         replace lendingtype_iso2 = "XF"  if `match' == "DZA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "EAP"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "EAR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "EAS"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "ECA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "ECS"  
         replace lendingtype_iso2 = "XF"  if `match' == "ECU"  
         replace lendingtype_iso2 = "XF"  if `match' == "EGY"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "EMU"  
         replace lendingtype_iso2 = "XI"  if `match' == "ERI"  
         replace lendingtype_iso2 = "XX"  if `match' == "ESP"  
         replace lendingtype_iso2 = "XX"  if `match' == "EST"  
         replace lendingtype_iso2 = "XI"  if `match' == "ETH"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "EUU"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "FCS"  
         replace lendingtype_iso2 = "XX"  if `match' == "FIN"  
         replace lendingtype_iso2 = "XH"  if `match' == "FJI"  
         replace lendingtype_iso2 = "XX"  if `match' == "FRA"  
         replace lendingtype_iso2 = "XX"  if `match' == "FRO"  
         replace lendingtype_iso2 = "XI"  if `match' == "FSM"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "FXS"  
         replace lendingtype_iso2 = "XF"  if `match' == "GAB"  
         replace lendingtype_iso2 = "XX"  if `match' == "GBR"  
         replace lendingtype_iso2 = "XF"  if `match' == "GEO"  
         replace lendingtype_iso2 = "XI"  if `match' == "GHA"  
         replace lendingtype_iso2 = "XX"  if `match' == "GIB"  
         replace lendingtype_iso2 = "XI"  if `match' == "GIN"  
         replace lendingtype_iso2 = "XI"  if `match' == "GMB"  
         replace lendingtype_iso2 = "XI"  if `match' == "GNB"  
         replace lendingtype_iso2 = "XF"  if `match' == "GNQ"  
         replace lendingtype_iso2 = "XX"  if `match' == "GRC"  
         replace lendingtype_iso2 = "XH"  if `match' == "GRD"  
         replace lendingtype_iso2 = "XX"  if `match' == "GRL"  
         replace lendingtype_iso2 = "XF"  if `match' == "GTM"  
         replace lendingtype_iso2 = "XX"  if `match' == "GUM"  
         replace lendingtype_iso2 = "XI"  if `match' == "GUY"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "HIC"  
         replace lendingtype_iso2 = "XX"  if `match' == "HKG"  
         replace lendingtype_iso2 = "XI"  if `match' == "HND"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "HPC"  
         replace lendingtype_iso2 = "XF"  if `match' == "HRV"  
         replace lendingtype_iso2 = "XI"  if `match' == "HTI"  
         replace lendingtype_iso2 = "XX"  if `match' == "HUN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "IBB"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "IBD"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "IBT"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "IDA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "IDB"  
         replace lendingtype_iso2 = "XF"  if `match' == "IDN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "IDX"  
         replace lendingtype_iso2 = "XX"  if `match' == "IMN"  
         replace lendingtype_iso2 = "XF"  if `match' == "IND"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "INX"  
         replace lendingtype_iso2 = "XX"  if `match' == "IRL"  
         replace lendingtype_iso2 = "XF"  if `match' == "IRN"  
         replace lendingtype_iso2 = "XF"  if `match' == "IRQ"  
         replace lendingtype_iso2 = "XX"  if `match' == "ISL"  
         replace lendingtype_iso2 = "XX"  if `match' == "ISR"  
         replace lendingtype_iso2 = "XX"  if `match' == "ITA"  
         replace lendingtype_iso2 = "XF"  if `match' == "JAM"  
         replace lendingtype_iso2 = "XF"  if `match' == "JOR"  
         replace lendingtype_iso2 = "XX"  if `match' == "JPN"  
         replace lendingtype_iso2 = "XF"  if `match' == "KAZ"  
         replace lendingtype_iso2 = "XH"  if `match' == "KEN"  
         replace lendingtype_iso2 = "XI"  if `match' == "KGZ"  
         replace lendingtype_iso2 = "XI"  if `match' == "KHM"  
         replace lendingtype_iso2 = "XI"  if `match' == "KIR"  
         replace lendingtype_iso2 = "XF"  if `match' == "KNA"  
         replace lendingtype_iso2 = "XX"  if `match' == "KOR"  
         replace lendingtype_iso2 = "XX"  if `match' == "KWT"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LAC"  
         replace lendingtype_iso2 = "XI"  if `match' == "LAO"  
         replace lendingtype_iso2 = "XF"  if `match' == "LBN"  
         replace lendingtype_iso2 = "XI"  if `match' == "LBR"  
         replace lendingtype_iso2 = "XF"  if `match' == "LBY"  
         replace lendingtype_iso2 = "XH"  if `match' == "LCA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LCN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LCR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LDC"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LIC"  
         replace lendingtype_iso2 = "XX"  if `match' == "LIE"  
         replace lendingtype_iso2 = "XF"  if `match' == "LKA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LMC"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LMY"  
         replace lendingtype_iso2 = "XI"  if `match' == "LSO"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "LTE"  
         replace lendingtype_iso2 = "XX"  if `match' == "LTU"  
         replace lendingtype_iso2 = "XX"  if `match' == "LUX"  
         replace lendingtype_iso2 = "XX"  if `match' == "LVA"  
         replace lendingtype_iso2 = "XX"  if `match' == "MAC"  
         replace lendingtype_iso2 = "XX"  if `match' == "MAF"  
         replace lendingtype_iso2 = "XF"  if `match' == "MAR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "MCA"  
         replace lendingtype_iso2 = "XX"  if `match' == "MCO"  
         replace lendingtype_iso2 = "XH"  if `match' == "MDA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "MDE"  
         replace lendingtype_iso2 = "XI"  if `match' == "MDG"  
         replace lendingtype_iso2 = "XI"  if `match' == "MDV"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "MEA"  
         replace lendingtype_iso2 = "XF"  if `match' == "MEX"  
         replace lendingtype_iso2 = "XI"  if `match' == "MHL"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "MIC"  
         replace lendingtype_iso2 = "XF"  if `match' == "MKD"  
         replace lendingtype_iso2 = "XI"  if `match' == "MLI"  
         replace lendingtype_iso2 = "XX"  if `match' == "MLT"  
         replace lendingtype_iso2 = "XI"  if `match' == "MMR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "MNA"  
         replace lendingtype_iso2 = "XF"  if `match' == "MNE"  
         replace lendingtype_iso2 = "XH"  if `match' == "MNG"  
         replace lendingtype_iso2 = "XX"  if `match' == "MNP"  
         replace lendingtype_iso2 = "XI"  if `match' == "MOZ"  
         replace lendingtype_iso2 = "XI"  if `match' == "MRT"  
         replace lendingtype_iso2 = "XF"  if `match' == "MUS"  
         replace lendingtype_iso2 = "XI"  if `match' == "MWI"  
         replace lendingtype_iso2 = "XF"  if `match' == "MYS"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "NAC"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "NAF"  
         replace lendingtype_iso2 = "XF"  if `match' == "NAM"  
         replace lendingtype_iso2 = "XX"  if `match' == "NCL"  
         replace lendingtype_iso2 = "XI"  if `match' == "NER"  
         replace lendingtype_iso2 = "XH"  if `match' == "NGA"  
         replace lendingtype_iso2 = "XI"  if `match' == "NIC"  
         replace lendingtype_iso2 = "XX"  if `match' == "NLD"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "NLS"  
         replace lendingtype_iso2 = "XX"  if `match' == "NOR"  
         replace lendingtype_iso2 = "XI"  if `match' == "NPL"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "NRS"  
         replace lendingtype_iso2 = "XF"  if `match' == "NRU"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "NXS"  
         replace lendingtype_iso2 = "XX"  if `match' == "NZL"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "OED"  
         replace lendingtype_iso2 = "XX"  if `match' == "OMN"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "OSS"  
         replace lendingtype_iso2 = "XH"  if `match' == "PAK"  
         replace lendingtype_iso2 = "XF"  if `match' == "PAN"  
         replace lendingtype_iso2 = "XF"  if `match' == "PER"  
         replace lendingtype_iso2 = "XF"  if `match' == "PHL"  
         replace lendingtype_iso2 = "XF"  if `match' == "PLW"  
         replace lendingtype_iso2 = "XH"  if `match' == "PNG"  
         replace lendingtype_iso2 = "XF"  if `match' == "POL"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "PRE"  
         replace lendingtype_iso2 = "XX"  if `match' == "PRI"  
         replace lendingtype_iso2 = "XX"  if `match' == "PRK"  
         replace lendingtype_iso2 = "XX"  if `match' == "PRT"  
         replace lendingtype_iso2 = "XF"  if `match' == "PRY"  
         replace lendingtype_iso2 = "XX"  if `match' == "PSE"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "PSS"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "PST"  
         replace lendingtype_iso2 = "XX"  if `match' == "PYF"  
         replace lendingtype_iso2 = "XX"  if `match' == "QAT"  
         replace lendingtype_iso2 = "XF"  if `match' == "ROU"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "RRS"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "RSO"  
         replace lendingtype_iso2 = "XF"  if `match' == "RUS"  
         replace lendingtype_iso2 = "XI"  if `match' == "RWA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "SAS"  
         replace lendingtype_iso2 = "XX"  if `match' == "SAU"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "SCE"  
         replace lendingtype_iso2 = "XI"  if `match' == "SDN"  
         replace lendingtype_iso2 = "XI"  if `match' == "SEN"  
         replace lendingtype_iso2 = "XX"  if `match' == "SGP"  
         replace lendingtype_iso2 = "XI"  if `match' == "SLB"  
         replace lendingtype_iso2 = "XI"  if `match' == "SLE"  
         replace lendingtype_iso2 = "XF"  if `match' == "SLV"  
         replace lendingtype_iso2 = "XX"  if `match' == "SMR"  
         replace lendingtype_iso2 = "XI"  if `match' == "SOM"  
         replace lendingtype_iso2 = "XF"  if `match' == "SRB"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "SSA"  
         replace lendingtype_iso2 = "XI"  if `match' == "SSD"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "SSF"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "SST"  
         replace lendingtype_iso2 = "XI"  if `match' == "STP"  
         replace lendingtype_iso2 = "XF"  if `match' == "SUR"  
         replace lendingtype_iso2 = "XX"  if `match' == "SVK"  
         replace lendingtype_iso2 = "XX"  if `match' == "SVN"  
         replace lendingtype_iso2 = "XX"  if `match' == "SWE"  
         replace lendingtype_iso2 = "XF"  if `match' == "SWZ"  
         replace lendingtype_iso2 = "XX"  if `match' == "SXM"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "SXZ"  
         replace lendingtype_iso2 = "XF"  if `match' == "SYC"  
         replace lendingtype_iso2 = "XI"  if `match' == "SYR"  
         replace lendingtype_iso2 = "XX"  if `match' == "TCA"  
         replace lendingtype_iso2 = "XI"  if `match' == "TCD"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "TEA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "TEC"  
         replace lendingtype_iso2 = "XI"  if `match' == "TGO"  
         replace lendingtype_iso2 = "XF"  if `match' == "THA"  
         replace lendingtype_iso2 = "XI"  if `match' == "TJK"  
         replace lendingtype_iso2 = "XF"  if `match' == "TKM"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "TLA"  
         replace lendingtype_iso2 = "XH"  if `match' == "TLS"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "TMN"  
         replace lendingtype_iso2 = "XI"  if `match' == "TON"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "TSA"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "TSS"  
         replace lendingtype_iso2 = "XF"  if `match' == "TTO"  
         replace lendingtype_iso2 = "XF"  if `match' == "TUN"  
         replace lendingtype_iso2 = "XF"  if `match' == "TUR"  
         replace lendingtype_iso2 = "XI"  if `match' == "TUV"  
         replace lendingtype_iso2 = "XX"  if `match' == "TWN"  
         replace lendingtype_iso2 = "XI"  if `match' == "TZA"  
         replace lendingtype_iso2 = "XI"  if `match' == "UGA"  
         replace lendingtype_iso2 = "XF"  if `match' == "UKR"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "UMC"  
         replace lendingtype_iso2 = "XF"  if `match' == "URY"  
         replace lendingtype_iso2 = "XX"  if `match' == "USA"  
         replace lendingtype_iso2 = "XH"  if `match' == "UZB"  
         replace lendingtype_iso2 = "XH"  if `match' == "VCT"  
         replace lendingtype_iso2 = "XF"  if `match' == "VEN"  
         replace lendingtype_iso2 = "XX"  if `match' == "VGB"  
         replace lendingtype_iso2 = "XX"  if `match' == "VIR"  
         replace lendingtype_iso2 = "XF"  if `match' == "VNM"  
         replace lendingtype_iso2 = "XI"  if `match' == "VUT"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "WLD"  
         replace lendingtype_iso2 = "XI"  if `match' == "WSM"  
         replace lendingtype_iso2 = "XI"  if `match' == "XKX"  
         replace lendingtype_iso2 = "Aggregates"  if `match' == "XZN"  
         replace lendingtype_iso2 = "XI"  if `match' == "YEM"  
         replace lendingtype_iso2 = "XF"  if `match' == "ZAF"  
         replace lendingtype_iso2 = "XI"  if `match' == "ZMB"  
  
******************  Lable: lendingtype_iso2 ******************
  
     lab var lendingtype_iso2    "Lending Type Code (ISO 2 digits)" 
 }        
  
 ****************************************************** 
  
 ******************  Values: lendingtypename ****************** 
  
 qui if ("`lendingtypename'" == "lendingtypename") {      
  
         gen lendingtypename = ""  
         replace lendingtypename = "Not classified"  if `match' == "ABW"  
         replace lendingtypename = "IDA"  if `match' == "AFG"  
         replace lendingtypename = "IBRD"  if `match' == "AGO"  
         replace lendingtypename = "IBRD"  if `match' == "ALB"  
         replace lendingtypename = "Not classified"  if `match' == "AND"  
         replace lendingtypename = "Not classified"  if `match' == "ARE"  
         replace lendingtypename = "IBRD"  if `match' == "ARG"  
         replace lendingtypename = "IBRD"  if `match' == "ARM"  
         replace lendingtypename = "Not classified"  if `match' == "ASM"  
         replace lendingtypename = "IBRD"  if `match' == "ATG"  
         replace lendingtypename = "Not classified"  if `match' == "AUS"  
         replace lendingtypename = "Not classified"  if `match' == "AUT"  
         replace lendingtypename = "IBRD"  if `match' == "AZE"  
         replace lendingtypename = "IDA"  if `match' == "BDI"  
         replace lendingtypename = "Not classified"  if `match' == "BEL"  
         replace lendingtypename = "IDA"  if `match' == "BEN"  
         replace lendingtypename = "IDA"  if `match' == "BFA"  
         replace lendingtypename = "IDA"  if `match' == "BGD"  
         replace lendingtypename = "IBRD"  if `match' == "BGR"  
         replace lendingtypename = "Not classified"  if `match' == "BHR"  
         replace lendingtypename = "Not classified"  if `match' == "BHS"  
         replace lendingtypename = "IBRD"  if `match' == "BIH"  
         replace lendingtypename = "IBRD"  if `match' == "BLR"  
         replace lendingtypename = "IBRD"  if `match' == "BLZ"  
         replace lendingtypename = "Not classified"  if `match' == "BMU"  
         replace lendingtypename = "IBRD"  if `match' == "BOL"  
         replace lendingtypename = "IBRD"  if `match' == "BRA"  
         replace lendingtypename = "Not classified"  if `match' == "BRB"  
         replace lendingtypename = "Not classified"  if `match' == "BRN"  
         replace lendingtypename = "IDA"  if `match' == "BTN"  
         replace lendingtypename = "IBRD"  if `match' == "BWA"  
         replace lendingtypename = "IDA"  if `match' == "CAF"  
         replace lendingtypename = "Not classified"  if `match' == "CAN"  
         replace lendingtypename = "Not classified"  if `match' == "CHE"  
         replace lendingtypename = "Not classified"  if `match' == "CHI"  
         replace lendingtypename = "IBRD"  if `match' == "CHL"  
         replace lendingtypename = "IBRD"  if `match' == "CHN"  
         replace lendingtypename = "IDA"  if `match' == "CIV"  
         replace lendingtypename = "Blend"  if `match' == "CMR"  
         replace lendingtypename = "IDA"  if `match' == "COD"  
         replace lendingtypename = "Blend"  if `match' == "COG"  
         replace lendingtypename = "IBRD"  if `match' == "COL"  
         replace lendingtypename = "IDA"  if `match' == "COM"  
         replace lendingtypename = "Blend"  if `match' == "CPV"  
         replace lendingtypename = "IBRD"  if `match' == "CRI"  
         replace lendingtypename = "Not classified"  if `match' == "CUB"  
         replace lendingtypename = "Not classified"  if `match' == "CUW"  
         replace lendingtypename = "Not classified"  if `match' == "CYM"  
         replace lendingtypename = "Not classified"  if `match' == "CYP"  
         replace lendingtypename = "Not classified"  if `match' == "CZE"  
         replace lendingtypename = "Not classified"  if `match' == "DEU"  
         replace lendingtypename = "IDA"  if `match' == "DJI"  
         replace lendingtypename = "Blend"  if `match' == "DMA"  
         replace lendingtypename = "Not classified"  if `match' == "DNK"  
         replace lendingtypename = "IBRD"  if `match' == "DOM"  
         replace lendingtypename = "IBRD"  if `match' == "DZA"  
         replace lendingtypename = "IBRD"  if `match' == "ECU"  
         replace lendingtypename = "IBRD"  if `match' == "EGY"  
         replace lendingtypename = "IDA"  if `match' == "ERI"  
         replace lendingtypename = "Not classified"  if `match' == "ESP"  
         replace lendingtypename = "Not classified"  if `match' == "EST"  
         replace lendingtypename = "IDA"  if `match' == "ETH"  
         replace lendingtypename = "Not classified"  if `match' == "FIN"  
         replace lendingtypename = "Blend"  if `match' == "FJI"  
         replace lendingtypename = "Not classified"  if `match' == "FRA"  
         replace lendingtypename = "Not classified"  if `match' == "FRO"  
         replace lendingtypename = "IDA"  if `match' == "FSM"  
         replace lendingtypename = "IBRD"  if `match' == "GAB"  
         replace lendingtypename = "Not classified"  if `match' == "GBR"  
         replace lendingtypename = "IBRD"  if `match' == "GEO"  
         replace lendingtypename = "IDA"  if `match' == "GHA"  
         replace lendingtypename = "Not classified"  if `match' == "GIB"  
         replace lendingtypename = "IDA"  if `match' == "GIN"  
         replace lendingtypename = "IDA"  if `match' == "GMB"  
         replace lendingtypename = "IDA"  if `match' == "GNB"  
         replace lendingtypename = "IBRD"  if `match' == "GNQ"  
         replace lendingtypename = "Not classified"  if `match' == "GRC"  
         replace lendingtypename = "Blend"  if `match' == "GRD"  
         replace lendingtypename = "Not classified"  if `match' == "GRL"  
         replace lendingtypename = "IBRD"  if `match' == "GTM"  
         replace lendingtypename = "Not classified"  if `match' == "GUM"  
         replace lendingtypename = "IDA"  if `match' == "GUY"  
         replace lendingtypename = "Not classified"  if `match' == "HKG"  
         replace lendingtypename = "IDA"  if `match' == "HND"  
         replace lendingtypename = "IBRD"  if `match' == "HRV"  
         replace lendingtypename = "IDA"  if `match' == "HTI"  
         replace lendingtypename = "Not classified"  if `match' == "HUN"  
         replace lendingtypename = "IBRD"  if `match' == "IDN"  
         replace lendingtypename = "Not classified"  if `match' == "IMN"  
         replace lendingtypename = "IBRD"  if `match' == "IND"  
         replace lendingtypename = "Not classified"  if `match' == "IRL"  
         replace lendingtypename = "IBRD"  if `match' == "IRN"  
         replace lendingtypename = "IBRD"  if `match' == "IRQ"  
         replace lendingtypename = "Not classified"  if `match' == "ISL"  
         replace lendingtypename = "Not classified"  if `match' == "ISR"  
         replace lendingtypename = "Not classified"  if `match' == "ITA"  
         replace lendingtypename = "IBRD"  if `match' == "JAM"  
         replace lendingtypename = "IBRD"  if `match' == "JOR"  
         replace lendingtypename = "Not classified"  if `match' == "JPN"  
         replace lendingtypename = "IBRD"  if `match' == "KAZ"  
         replace lendingtypename = "Blend"  if `match' == "KEN"  
         replace lendingtypename = "IDA"  if `match' == "KGZ"  
         replace lendingtypename = "IDA"  if `match' == "KHM"  
         replace lendingtypename = "IDA"  if `match' == "KIR"  
         replace lendingtypename = "IBRD"  if `match' == "KNA"  
         replace lendingtypename = "Not classified"  if `match' == "KOR"  
         replace lendingtypename = "Not classified"  if `match' == "KWT"  
         replace lendingtypename = "IDA"  if `match' == "LAO"  
         replace lendingtypename = "IBRD"  if `match' == "LBN"  
         replace lendingtypename = "IDA"  if `match' == "LBR"  
         replace lendingtypename = "IBRD"  if `match' == "LBY"  
         replace lendingtypename = "Blend"  if `match' == "LCA"  
         replace lendingtypename = "Not classified"  if `match' == "LIE"  
         replace lendingtypename = "IBRD"  if `match' == "LKA"  
         replace lendingtypename = "IDA"  if `match' == "LSO"  
         replace lendingtypename = "Not classified"  if `match' == "LTU"  
         replace lendingtypename = "Not classified"  if `match' == "LUX"  
         replace lendingtypename = "Not classified"  if `match' == "LVA"  
         replace lendingtypename = "Not classified"  if `match' == "MAC"  
         replace lendingtypename = "Not classified"  if `match' == "MAF"  
         replace lendingtypename = "IBRD"  if `match' == "MAR"  
         replace lendingtypename = "Not classified"  if `match' == "MCO"  
         replace lendingtypename = "Blend"  if `match' == "MDA"  
         replace lendingtypename = "IDA"  if `match' == "MDG"  
         replace lendingtypename = "IDA"  if `match' == "MDV"  
         replace lendingtypename = "IBRD"  if `match' == "MEX"  
         replace lendingtypename = "IDA"  if `match' == "MHL"  
         replace lendingtypename = "IBRD"  if `match' == "MKD"  
         replace lendingtypename = "IDA"  if `match' == "MLI"  
         replace lendingtypename = "Not classified"  if `match' == "MLT"  
         replace lendingtypename = "IDA"  if `match' == "MMR"  
         replace lendingtypename = "IBRD"  if `match' == "MNE"  
         replace lendingtypename = "Blend"  if `match' == "MNG"  
         replace lendingtypename = "Not classified"  if `match' == "MNP"  
         replace lendingtypename = "IDA"  if `match' == "MOZ"  
         replace lendingtypename = "IDA"  if `match' == "MRT"  
         replace lendingtypename = "IBRD"  if `match' == "MUS"  
         replace lendingtypename = "IDA"  if `match' == "MWI"  
         replace lendingtypename = "IBRD"  if `match' == "MYS"  
         replace lendingtypename = "IBRD"  if `match' == "NAM"  
         replace lendingtypename = "Not classified"  if `match' == "NCL"  
         replace lendingtypename = "IDA"  if `match' == "NER"  
         replace lendingtypename = "Blend"  if `match' == "NGA"  
         replace lendingtypename = "IDA"  if `match' == "NIC"  
         replace lendingtypename = "Not classified"  if `match' == "NLD"  
         replace lendingtypename = "Not classified"  if `match' == "NOR"  
         replace lendingtypename = "IDA"  if `match' == "NPL"  
         replace lendingtypename = "IBRD"  if `match' == "NRU"  
         replace lendingtypename = "Not classified"  if `match' == "NZL"  
         replace lendingtypename = "Not classified"  if `match' == "OMN"  
         replace lendingtypename = "Blend"  if `match' == "PAK"  
         replace lendingtypename = "IBRD"  if `match' == "PAN"  
         replace lendingtypename = "IBRD"  if `match' == "PER"  
         replace lendingtypename = "IBRD"  if `match' == "PHL"  
         replace lendingtypename = "IBRD"  if `match' == "PLW"  
         replace lendingtypename = "Blend"  if `match' == "PNG"  
         replace lendingtypename = "IBRD"  if `match' == "POL"  
         replace lendingtypename = "Not classified"  if `match' == "PRI"  
         replace lendingtypename = "Not classified"  if `match' == "PRK"  
         replace lendingtypename = "Not classified"  if `match' == "PRT"  
         replace lendingtypename = "IBRD"  if `match' == "PRY"  
         replace lendingtypename = "Not classified"  if `match' == "PSE"  
         replace lendingtypename = "Not classified"  if `match' == "PYF"  
         replace lendingtypename = "Not classified"  if `match' == "QAT"  
         replace lendingtypename = "IBRD"  if `match' == "ROU"  
         replace lendingtypename = "IBRD"  if `match' == "RUS"  
         replace lendingtypename = "IDA"  if `match' == "RWA"  
         replace lendingtypename = "Not classified"  if `match' == "SAU"  
         replace lendingtypename = "IDA"  if `match' == "SDN"  
         replace lendingtypename = "IDA"  if `match' == "SEN"  
         replace lendingtypename = "Not classified"  if `match' == "SGP"  
         replace lendingtypename = "IDA"  if `match' == "SLB"  
         replace lendingtypename = "IDA"  if `match' == "SLE"  
         replace lendingtypename = "IBRD"  if `match' == "SLV"  
         replace lendingtypename = "Not classified"  if `match' == "SMR"  
         replace lendingtypename = "IDA"  if `match' == "SOM"  
         replace lendingtypename = "IBRD"  if `match' == "SRB"  
         replace lendingtypename = "IDA"  if `match' == "SSD"  
         replace lendingtypename = "IDA"  if `match' == "STP"  
         replace lendingtypename = "IBRD"  if `match' == "SUR"  
         replace lendingtypename = "Not classified"  if `match' == "SVK"  
         replace lendingtypename = "Not classified"  if `match' == "SVN"  
         replace lendingtypename = "Not classified"  if `match' == "SWE"  
         replace lendingtypename = "IBRD"  if `match' == "SWZ"  
         replace lendingtypename = "Not classified"  if `match' == "SXM"  
         replace lendingtypename = "IBRD"  if `match' == "SYC"  
         replace lendingtypename = "IDA"  if `match' == "SYR"  
         replace lendingtypename = "Not classified"  if `match' == "TCA"  
         replace lendingtypename = "IDA"  if `match' == "TCD"  
         replace lendingtypename = "IDA"  if `match' == "TGO"  
         replace lendingtypename = "IBRD"  if `match' == "THA"  
         replace lendingtypename = "IDA"  if `match' == "TJK"  
         replace lendingtypename = "IBRD"  if `match' == "TKM"  
         replace lendingtypename = "Blend"  if `match' == "TLS"  
         replace lendingtypename = "IDA"  if `match' == "TON"  
         replace lendingtypename = "IBRD"  if `match' == "TTO"  
         replace lendingtypename = "IBRD"  if `match' == "TUN"  
         replace lendingtypename = "IBRD"  if `match' == "TUR"  
         replace lendingtypename = "IDA"  if `match' == "TUV"  
         replace lendingtypename = "Not classified"  if `match' == "TWN"  
         replace lendingtypename = "IDA"  if `match' == "TZA"  
         replace lendingtypename = "IDA"  if `match' == "UGA"  
         replace lendingtypename = "IBRD"  if `match' == "UKR"  
         replace lendingtypename = "IBRD"  if `match' == "URY"  
         replace lendingtypename = "Not classified"  if `match' == "USA"  
         replace lendingtypename = "Blend"  if `match' == "UZB"  
         replace lendingtypename = "Blend"  if `match' == "VCT"  
         replace lendingtypename = "IBRD"  if `match' == "VEN"  
         replace lendingtypename = "Not classified"  if `match' == "VGB"  
         replace lendingtypename = "Not classified"  if `match' == "VIR"  
         replace lendingtypename = "IBRD"  if `match' == "VNM"  
         replace lendingtypename = "IDA"  if `match' == "VUT"  
         replace lendingtypename = "IDA"  if `match' == "WSM"  
         replace lendingtypename = "IDA"  if `match' == "XKX"  
         replace lendingtypename = "IDA"  if `match' == "YEM"  
         replace lendingtypename = "IBRD"  if `match' == "ZAF"  
         replace lendingtypename = "IDA"  if `match' == "ZMB"  
  
******************  Lable: lendingtypename ******************
  
     lab var lendingtypename     "Lending Type Name" 
 }        
  
 ****************************************************** 
  
 ******************  Values: capital ****************** 
  
 qui if ("`capital'" == "capital") {      
  
         gen capital = ""  
         replace capital = "Oranjestad"  if `match' == "ABW"  
         replace capital = "Kabul"  if `match' == "AFG"  
         replace capital = "Luanda"  if `match' == "AGO"  
         replace capital = "Tirane"  if `match' == "ALB"  
         replace capital = "Andorra la Vella"  if `match' == "AND"  
         replace capital = "Abu Dhabi"  if `match' == "ARE"  
         replace capital = "Buenos Aires"  if `match' == "ARG"  
         replace capital = "Yerevan"  if `match' == "ARM"  
         replace capital = "Pago Pago"  if `match' == "ASM"  
         replace capital = "Saint John's"  if `match' == "ATG"  
         replace capital = "Canberra"  if `match' == "AUS"  
         replace capital = "Vienna"  if `match' == "AUT"  
         replace capital = "Baku"  if `match' == "AZE"  
         replace capital = "Bujumbura"  if `match' == "BDI"  
         replace capital = "Brussels"  if `match' == "BEL"  
         replace capital = "Porto-Novo"  if `match' == "BEN"  
         replace capital = "Ouagadougou"  if `match' == "BFA"  
         replace capital = "Dhaka"  if `match' == "BGD"  
         replace capital = "Sofia"  if `match' == "BGR"  
         replace capital = "Manama"  if `match' == "BHR"  
         replace capital = "Nassau"  if `match' == "BHS"  
         replace capital = "Sarajevo"  if `match' == "BIH"  
         replace capital = "Minsk"  if `match' == "BLR"  
         replace capital = "Belmopan"  if `match' == "BLZ"  
         replace capital = "Hamilton"  if `match' == "BMU"  
         replace capital = "La Paz"  if `match' == "BOL"  
         replace capital = "Brasilia"  if `match' == "BRA"  
         replace capital = "Bridgetown"  if `match' == "BRB"  
         replace capital = "Bandar Seri Begawan"  if `match' == "BRN"  
         replace capital = "Thimphu"  if `match' == "BTN"  
         replace capital = "Gaborone"  if `match' == "BWA"  
         replace capital = "Bangui"  if `match' == "CAF"  
         replace capital = "Ottawa"  if `match' == "CAN"  
         replace capital = "Bern"  if `match' == "CHE"  
         replace capital = "<wb:capitalCity"  if `match' == "CHI"  
         replace capital = "Santiago"  if `match' == "CHL"  
         replace capital = "Beijing"  if `match' == "CHN"  
         replace capital = "Yamoussoukro"  if `match' == "CIV"  
         replace capital = "Yaounde"  if `match' == "CMR"  
         replace capital = "Kinshasa"  if `match' == "COD"  
         replace capital = "Brazzaville"  if `match' == "COG"  
         replace capital = "Bogota"  if `match' == "COL"  
         replace capital = "Moroni"  if `match' == "COM"  
         replace capital = "Praia"  if `match' == "CPV"  
         replace capital = "San Jose"  if `match' == "CRI"  
         replace capital = "Havana"  if `match' == "CUB"  
         replace capital = "Willemstad"  if `match' == "CUW"  
         replace capital = "George Town"  if `match' == "CYM"  
         replace capital = "Nicosia"  if `match' == "CYP"  
         replace capital = "Prague"  if `match' == "CZE"  
         replace capital = "Berlin"  if `match' == "DEU"  
         replace capital = "Djibouti"  if `match' == "DJI"  
         replace capital = "Roseau"  if `match' == "DMA"  
         replace capital = "Copenhagen"  if `match' == "DNK"  
         replace capital = "Santo Domingo"  if `match' == "DOM"  
         replace capital = "Algiers"  if `match' == "DZA"  
         replace capital = "Quito"  if `match' == "ECU"  
         replace capital = "Cairo"  if `match' == "EGY"  
         replace capital = "Asmara"  if `match' == "ERI"  
         replace capital = "Madrid"  if `match' == "ESP"  
         replace capital = "Tallinn"  if `match' == "EST"  
         replace capital = "Addis Ababa"  if `match' == "ETH"  
         replace capital = "Helsinki"  if `match' == "FIN"  
         replace capital = "Suva"  if `match' == "FJI"  
         replace capital = "Paris"  if `match' == "FRA"  
         replace capital = "Torshavn"  if `match' == "FRO"  
         replace capital = "Palikir"  if `match' == "FSM"  
         replace capital = "Libreville"  if `match' == "GAB"  
         replace capital = "London"  if `match' == "GBR"  
         replace capital = "Tbilisi"  if `match' == "GEO"  
         replace capital = "Accra"  if `match' == "GHA"  
         replace capital = "<wb:capitalCity"  if `match' == "GIB"  
         replace capital = "Conakry"  if `match' == "GIN"  
         replace capital = "Banjul"  if `match' == "GMB"  
         replace capital = "Bissau"  if `match' == "GNB"  
         replace capital = "Malabo"  if `match' == "GNQ"  
         replace capital = "Athens"  if `match' == "GRC"  
         replace capital = "Saint George's"  if `match' == "GRD"  
         replace capital = "Nuuk"  if `match' == "GRL"  
         replace capital = "Guatemala City"  if `match' == "GTM"  
         replace capital = "Agana"  if `match' == "GUM"  
         replace capital = "Georgetown"  if `match' == "GUY"  
         replace capital = "<wb:capitalCity"  if `match' == "HKG"  
         replace capital = "Tegucigalpa"  if `match' == "HND"  
         replace capital = "Zagreb"  if `match' == "HRV"  
         replace capital = "Port-au-Prince"  if `match' == "HTI"  
         replace capital = "Budapest"  if `match' == "HUN"  
         replace capital = "Jakarta"  if `match' == "IDN"  
         replace capital = "Douglas"  if `match' == "IMN"  
         replace capital = "New Delhi"  if `match' == "IND"  
         replace capital = "Dublin"  if `match' == "IRL"  
         replace capital = "Tehran"  if `match' == "IRN"  
         replace capital = "Baghdad"  if `match' == "IRQ"  
         replace capital = "Reykjavik"  if `match' == "ISL"  
         replace capital = "<wb:capitalCity"  if `match' == "ISR"  
         replace capital = "Rome"  if `match' == "ITA"  
         replace capital = "Kingston"  if `match' == "JAM"  
         replace capital = "Amman"  if `match' == "JOR"  
         replace capital = "Tokyo"  if `match' == "JPN"  
         replace capital = "Astana"  if `match' == "KAZ"  
         replace capital = "Nairobi"  if `match' == "KEN"  
         replace capital = "Bishkek"  if `match' == "KGZ"  
         replace capital = "Phnom Penh"  if `match' == "KHM"  
         replace capital = "Tarawa"  if `match' == "KIR"  
         replace capital = "Basseterre"  if `match' == "KNA"  
         replace capital = "Seoul"  if `match' == "KOR"  
         replace capital = "Kuwait City"  if `match' == "KWT"  
         replace capital = "Vientiane"  if `match' == "LAO"  
         replace capital = "Beirut"  if `match' == "LBN"  
         replace capital = "Monrovia"  if `match' == "LBR"  
         replace capital = "Tripoli"  if `match' == "LBY"  
         replace capital = "Castries"  if `match' == "LCA"  
         replace capital = "Vaduz"  if `match' == "LIE"  
         replace capital = "Colombo"  if `match' == "LKA"  
         replace capital = "Maseru"  if `match' == "LSO"  
         replace capital = "Vilnius"  if `match' == "LTU"  
         replace capital = "Luxembourg"  if `match' == "LUX"  
         replace capital = "Riga"  if `match' == "LVA"  
         replace capital = "<wb:capitalCity"  if `match' == "MAC"  
         replace capital = "Marigot"  if `match' == "MAF"  
         replace capital = "Rabat"  if `match' == "MAR"  
         replace capital = "Monaco"  if `match' == "MCO"  
         replace capital = "Chisinau"  if `match' == "MDA"  
         replace capital = "Antananarivo"  if `match' == "MDG"  
         replace capital = "Male"  if `match' == "MDV"  
         replace capital = "Mexico City"  if `match' == "MEX"  
         replace capital = "Majuro"  if `match' == "MHL"  
         replace capital = "Skopje"  if `match' == "MKD"  
         replace capital = "Bamako"  if `match' == "MLI"  
         replace capital = "Valletta"  if `match' == "MLT"  
         replace capital = "Naypyidaw"  if `match' == "MMR"  
         replace capital = "Podgorica"  if `match' == "MNE"  
         replace capital = "Ulaanbaatar"  if `match' == "MNG"  
         replace capital = "Saipan"  if `match' == "MNP"  
         replace capital = "Maputo"  if `match' == "MOZ"  
         replace capital = "Nouakchott"  if `match' == "MRT"  
         replace capital = "Port Louis"  if `match' == "MUS"  
         replace capital = "Lilongwe"  if `match' == "MWI"  
         replace capital = "Kuala Lumpur"  if `match' == "MYS"  
         replace capital = "Windhoek"  if `match' == "NAM"  
         replace capital = "Noum'ea"  if `match' == "NCL"  
         replace capital = "Niamey"  if `match' == "NER"  
         replace capital = "Abuja"  if `match' == "NGA"  
         replace capital = "Managua"  if `match' == "NIC"  
         replace capital = "Amsterdam"  if `match' == "NLD"  
         replace capital = "Oslo"  if `match' == "NOR"  
         replace capital = "Kathmandu"  if `match' == "NPL"  
         replace capital = "Yaren District"  if `match' == "NRU"  
         replace capital = "Wellington"  if `match' == "NZL"  
         replace capital = "Muscat"  if `match' == "OMN"  
         replace capital = "Islamabad"  if `match' == "PAK"  
         replace capital = "Panama City"  if `match' == "PAN"  
         replace capital = "Lima"  if `match' == "PER"  
         replace capital = "Manila"  if `match' == "PHL"  
         replace capital = "Koror"  if `match' == "PLW"  
         replace capital = "Port Moresby"  if `match' == "PNG"  
         replace capital = "Warsaw"  if `match' == "POL"  
         replace capital = "San Juan"  if `match' == "PRI"  
         replace capital = "Pyongyang"  if `match' == "PRK"  
         replace capital = "Lisbon"  if `match' == "PRT"  
         replace capital = "Asuncion"  if `match' == "PRY"  
         replace capital = "<wb:capitalCity"  if `match' == "PSE"  
         replace capital = "Papeete"  if `match' == "PYF"  
         replace capital = "Doha"  if `match' == "QAT"  
         replace capital = "Bucharest"  if `match' == "ROU"  
         replace capital = "Moscow"  if `match' == "RUS"  
         replace capital = "Kigali"  if `match' == "RWA"  
         replace capital = "Riyadh"  if `match' == "SAU"  
         replace capital = "Khartoum"  if `match' == "SDN"  
         replace capital = "Dakar"  if `match' == "SEN"  
         replace capital = "Singapore"  if `match' == "SGP"  
         replace capital = "Honiara"  if `match' == "SLB"  
         replace capital = "Freetown"  if `match' == "SLE"  
         replace capital = "San Salvador"  if `match' == "SLV"  
         replace capital = "San Marino"  if `match' == "SMR"  
         replace capital = "Mogadishu"  if `match' == "SOM"  
         replace capital = "Belgrade"  if `match' == "SRB"  
         replace capital = "Juba"  if `match' == "SSD"  
         replace capital = "Sao Tome"  if `match' == "STP"  
         replace capital = "Paramaribo"  if `match' == "SUR"  
         replace capital = "Bratislava"  if `match' == "SVK"  
         replace capital = "Ljubljana"  if `match' == "SVN"  
         replace capital = "Stockholm"  if `match' == "SWE"  
         replace capital = "Mbabane"  if `match' == "SWZ"  
         replace capital = "Philipsburg"  if `match' == "SXM"  
         replace capital = "Victoria"  if `match' == "SYC"  
         replace capital = "Damascus"  if `match' == "SYR"  
         replace capital = "Grand Turk"  if `match' == "TCA"  
         replace capital = "N'Djamena"  if `match' == "TCD"  
         replace capital = "Lome"  if `match' == "TGO"  
         replace capital = "Bangkok"  if `match' == "THA"  
         replace capital = "Dushanbe"  if `match' == "TJK"  
         replace capital = "Ashgabat"  if `match' == "TKM"  
         replace capital = "Dili"  if `match' == "TLS"  
         replace capital = "Nuku'alofa"  if `match' == "TON"  
         replace capital = "Port-of-Spain"  if `match' == "TTO"  
         replace capital = "Tunis"  if `match' == "TUN"  
         replace capital = "Ankara"  if `match' == "TUR"  
         replace capital = "Funafuti"  if `match' == "TUV"  
         replace capital = "<wb:capitalCity"  if `match' == "TWN"  
         replace capital = "Dodoma"  if `match' == "TZA"  
         replace capital = "Kampala"  if `match' == "UGA"  
         replace capital = "Kiev"  if `match' == "UKR"  
         replace capital = "Montevideo"  if `match' == "URY"  
         replace capital = "Washington DC"  if `match' == "USA"  
         replace capital = "Tashkent"  if `match' == "UZB"  
         replace capital = "Kingstown"  if `match' == "VCT"  
         replace capital = "Caracas"  if `match' == "VEN"  
         replace capital = "Road Town"  if `match' == "VGB"  
         replace capital = "Charlotte Amalie"  if `match' == "VIR"  
         replace capital = "Hanoi"  if `match' == "VNM"  
         replace capital = "Port-Vila"  if `match' == "VUT"  
         replace capital = "Apia"  if `match' == "WSM"  
         replace capital = "Pristina"  if `match' == "XKX"  
         replace capital = "Sana'a"  if `match' == "YEM"  
         replace capital = "Pretoria"  if `match' == "ZAF"  
         replace capital = "Lusaka"  if `match' == "ZMB"  
  
******************  Lable: capital ******************
  
     lab var capital                             "Capital Name" 
 }        
  
 ****************************************************** 
  
 ******************  Values: longitude ****************** 
  
 qui if ("`longitude'" == "longitude") {      
  
         gen  double longitude = .  
         replace longitude = real("-70.0167")    if `match' == "ABW"  
         replace longitude = real("69.1761")    if `match' == "AFG"  
         replace longitude = real("13.242")    if `match' == "AGO"  
         replace longitude = real("19.8172")    if `match' == "ALB"  
         replace longitude = real("1.5218")    if `match' == "AND"  
         replace longitude = real("54.3705")    if `match' == "ARE"  
         replace longitude = real("-58.4173")    if `match' == "ARG"  
         replace longitude = real("44.509")    if `match' == "ARM"  
         replace longitude = real("-170.691")    if `match' == "ASM"  
         replace longitude = real("-61.8456")    if `match' == "ATG"  
         replace longitude = real("149.129")    if `match' == "AUS"  
         replace longitude = real("16.3798")    if `match' == "AUT"  
         replace longitude = real("49.8932")    if `match' == "AZE"  
         replace longitude = real("29.3639")    if `match' == "BDI"  
         replace longitude = real("4.36761")    if `match' == "BEL"  
         replace longitude = real("2.6323")    if `match' == "BEN"  
         replace longitude = real("-1.53395")    if `match' == "BFA"  
         replace longitude = real("90.4113")    if `match' == "BGD"  
         replace longitude = real("23.3238")    if `match' == "BGR"  
         replace longitude = real("50.5354")    if `match' == "BHR"  
         replace longitude = real("-77.339")    if `match' == "BHS"  
         replace longitude = real("18.4214")    if `match' == "BIH"  
         replace longitude = real("27.5766")    if `match' == "BLR"  
         replace longitude = real("-88.7713")    if `match' == "BLZ"  
         replace longitude = real("-64.706")    if `match' == "BMU"  
         replace longitude = real("-66.1936")    if `match' == "BOL"  
         replace longitude = real("-47.9292")    if `match' == "BRA"  
         replace longitude = real("-59.6105")    if `match' == "BRB"  
         replace longitude = real("114.946")    if `match' == "BRN"  
         replace longitude = real("89.6177")    if `match' == "BTN"  
         replace longitude = real("25.9201")    if `match' == "BWA"  
         replace longitude = real("21.6407")    if `match' == "CAF"  
         replace longitude = real("-75.6919")    if `match' == "CAN"  
         replace longitude = real("7.44821")    if `match' == "CHE"  
         replace longitude = real("<wb:longitude")    if `match' == "CHI"  
         replace longitude = real("-70.6475")    if `match' == "CHL"  
         replace longitude = real("116.286")    if `match' == "CHN"  
         replace longitude = real("-4.0305")    if `match' == "CIV"  
         replace longitude = real("11.5174")    if `match' == "CMR"  
         replace longitude = real("15.3222")    if `match' == "COD"  
         replace longitude = real("15.2662")    if `match' == "COG"  
         replace longitude = real("-74.082")    if `match' == "COL"  
         replace longitude = real("43.2418")    if `match' == "COM"  
         replace longitude = real("-23.5087")    if `match' == "CPV"  
         replace longitude = real("-84.0089")    if `match' == "CRI"  
         replace longitude = real("-82.3667")    if `match' == "CUB"  
         replace longitude = real("<wb:longitude")    if `match' == "CUW"  
         replace longitude = real("-81.3857")    if `match' == "CYM"  
         replace longitude = real("33.3736")    if `match' == "CYP"  
         replace longitude = real("14.4205")    if `match' == "CZE"  
         replace longitude = real("13.4115")    if `match' == "DEU"  
         replace longitude = real("43.1425")    if `match' == "DJI"  
         replace longitude = real("-61.39")    if `match' == "DMA"  
         replace longitude = real("12.5681")    if `match' == "DNK"  
         replace longitude = real("-69.8908")    if `match' == "DOM"  
         replace longitude = real("3.05097")    if `match' == "DZA"  
         replace longitude = real("-78.5243")    if `match' == "ECU"  
         replace longitude = real("31.2461")    if `match' == "EGY"  
         replace longitude = real("38.9183")    if `match' == "ERI"  
         replace longitude = real("-3.70327")    if `match' == "ESP"  
         replace longitude = real("24.7586")    if `match' == "EST"  
         replace longitude = real("38.7468")    if `match' == "ETH"  
         replace longitude = real("24.9525")    if `match' == "FIN"  
         replace longitude = real("178.399")    if `match' == "FJI"  
         replace longitude = real("2.35097")    if `match' == "FRA"  
         replace longitude = real("-6.91181")    if `match' == "FRO"  
         replace longitude = real("158.185")    if `match' == "FSM"  
         replace longitude = real("9.45162")    if `match' == "GAB"  
         replace longitude = real("-0.126236")    if `match' == "GBR"  
         replace longitude = real("44.793")    if `match' == "GEO"  
         replace longitude = real("-0.20795")    if `match' == "GHA"  
         replace longitude = real("<wb:longitude")    if `match' == "GIB"  
         replace longitude = real("-13.7")    if `match' == "GIN"  
         replace longitude = real("-16.5885")    if `match' == "GMB"  
         replace longitude = real("-15.1804")    if `match' == "GNB"  
         replace longitude = real("8.7741")    if `match' == "GNQ"  
         replace longitude = real("23.7166")    if `match' == "GRC"  
         replace longitude = real("-61.7449")    if `match' == "GRD"  
         replace longitude = real("-51.7214")    if `match' == "GRL"  
         replace longitude = real("-90.5328")    if `match' == "GTM"  
         replace longitude = real("144.794")    if `match' == "GUM"  
         replace longitude = real("-58.1548")    if `match' == "GUY"  
         replace longitude = real("114.109")    if `match' == "HKG"  
         replace longitude = real("-87.4667")    if `match' == "HND"  
         replace longitude = real("15.9614")    if `match' == "HRV"  
         replace longitude = real("-72.3288")    if `match' == "HTI"  
         replace longitude = real("19.0408")    if `match' == "HUN"  
         replace longitude = real("106.83")    if `match' == "IDN"  
         replace longitude = real("-4.47928")    if `match' == "IMN"  
         replace longitude = real("77.225")    if `match' == "IND"  
         replace longitude = real("-6.26749")    if `match' == "IRL"  
         replace longitude = real("51.4447")    if `match' == "IRN"  
         replace longitude = real("44.394")    if `match' == "IRQ"  
         replace longitude = real("-21.8952")    if `match' == "ISL"  
         replace longitude = real("35.2035")    if `match' == "ISR"  
         replace longitude = real("12.4823")    if `match' == "ITA"  
         replace longitude = real("-76.792")    if `match' == "JAM"  
         replace longitude = real("35.9263")    if `match' == "JOR"  
         replace longitude = real("139.77")    if `match' == "JPN"  
         replace longitude = real("71.4382")    if `match' == "KAZ"  
         replace longitude = real("36.8126")    if `match' == "KEN"  
         replace longitude = real("74.6057")    if `match' == "KGZ"  
         replace longitude = real("104.874")    if `match' == "KHM"  
         replace longitude = real("172.979")    if `match' == "KIR"  
         replace longitude = real("-62.7309")    if `match' == "KNA"  
         replace longitude = real("126.957")    if `match' == "KOR"  
         replace longitude = real("47.9824")    if `match' == "KWT"  
         replace longitude = real("102.177")    if `match' == "LAO"  
         replace longitude = real("35.5134")    if `match' == "LBN"  
         replace longitude = real("-10.7957")    if `match' == "LBR"  
         replace longitude = real("13.1072")    if `match' == "LBY"  
         replace longitude = real("-60.9832")    if `match' == "LCA"  
         replace longitude = real("9.52148")    if `match' == "LIE"  
         replace longitude = real("79.8528")    if `match' == "LKA"  
         replace longitude = real("27.7167")    if `match' == "LSO"  
         replace longitude = real("25.2799")    if `match' == "LTU"  
         replace longitude = real("6.1296")    if `match' == "LUX"  
         replace longitude = real("24.1048")    if `match' == "LVA"  
         replace longitude = real("113.55")    if `match' == "MAC"  
         replace longitude = real("<wb:longitude")    if `match' == "MAF"  
         replace longitude = real("-6.8704")    if `match' == "MAR"  
         replace longitude = real("7.41891")    if `match' == "MCO"  
         replace longitude = real("28.8497")    if `match' == "MDA"  
         replace longitude = real("45.7167")    if `match' == "MDG"  
         replace longitude = real("73.5109")    if `match' == "MDV"  
         replace longitude = real("-99.1276")    if `match' == "MEX"  
         replace longitude = real("171.135")    if `match' == "MHL"  
         replace longitude = real("21.4361")    if `match' == "MKD"  
         replace longitude = real("-7.50034")    if `match' == "MLI"  
         replace longitude = real("14.5189")    if `match' == "MLT"  
         replace longitude = real("95.9562")    if `match' == "MMR"  
         replace longitude = real("19.2595")    if `match' == "MNE"  
         replace longitude = real("106.937")    if `match' == "MNG"  
         replace longitude = real("145.765")    if `match' == "MNP"  
         replace longitude = real("32.5713")    if `match' == "MOZ"  
         replace longitude = real("-15.9824")    if `match' == "MRT"  
         replace longitude = real("57.4977")    if `match' == "MUS"  
         replace longitude = real("33.7703")    if `match' == "MWI"  
         replace longitude = real("101.684")    if `match' == "MYS"  
         replace longitude = real("17.0931")    if `match' == "NAM"  
         replace longitude = real("166.464")    if `match' == "NCL"  
         replace longitude = real("2.1073")    if `match' == "NER"  
         replace longitude = real("7.48906")    if `match' == "NGA"  
         replace longitude = real("-86.2734")    if `match' == "NIC"  
         replace longitude = real("4.89095")    if `match' == "NLD"  
         replace longitude = real("10.7387")    if `match' == "NOR"  
         replace longitude = real("85.3157")    if `match' == "NPL"  
         replace longitude = real("166.920867")    if `match' == "NRU"  
         replace longitude = real("174.776")    if `match' == "NZL"  
         replace longitude = real("58.5874")    if `match' == "OMN"  
         replace longitude = real("72.8")    if `match' == "PAK"  
         replace longitude = real("-79.5188")    if `match' == "PAN"  
         replace longitude = real("-77.0465")    if `match' == "PER"  
         replace longitude = real("121.035")    if `match' == "PHL"  
         replace longitude = real("134.479")    if `match' == "PLW"  
         replace longitude = real("147.194")    if `match' == "PNG"  
         replace longitude = real("21.02")    if `match' == "POL"  
         replace longitude = real("-66")    if `match' == "PRI"  
         replace longitude = real("125.754")    if `match' == "PRK"  
         replace longitude = real("-9.13552")    if `match' == "PRT"  
         replace longitude = real("-57.6362")    if `match' == "PRY"  
         replace longitude = real("<wb:longitude")    if `match' == "PSE"  
         replace longitude = real("-149.57")    if `match' == "PYF"  
         replace longitude = real("51.5082")    if `match' == "QAT"  
         replace longitude = real("26.0979")    if `match' == "ROU"  
         replace longitude = real("37.6176")    if `match' == "RUS"  
         replace longitude = real("30.0587")    if `match' == "RWA"  
         replace longitude = real("46.6977")    if `match' == "SAU"  
         replace longitude = real("32.5363")    if `match' == "SDN"  
         replace longitude = real("-17.4734")    if `match' == "SEN"  
         replace longitude = real("103.85")    if `match' == "SGP"  
         replace longitude = real("159.949")    if `match' == "SLB"  
         replace longitude = real("-13.2134")    if `match' == "SLE"  
         replace longitude = real("-89.2073")    if `match' == "SLV"  
         replace longitude = real("12.4486")    if `match' == "SMR"  
         replace longitude = real("45.3254")    if `match' == "SOM"  
         replace longitude = real("20.4656")    if `match' == "SRB"  
         replace longitude = real("31.6")    if `match' == "SSD"  
         replace longitude = real("6.6071")    if `match' == "STP"  
         replace longitude = real("-55.1679")    if `match' == "SUR"  
         replace longitude = real("17.1073")    if `match' == "SVK"  
         replace longitude = real("14.5044")    if `match' == "SVN"  
         replace longitude = real("18.0645")    if `match' == "SWE"  
         replace longitude = real("31.4659")    if `match' == "SWZ"  
         replace longitude = real("<wb:longitude")    if `match' == "SXM"  
         replace longitude = real("55.4466")    if `match' == "SYC"  
         replace longitude = real("36.3119")    if `match' == "SYR"  
         replace longitude = real("-71.141389")    if `match' == "TCA"  
         replace longitude = real("15.0445")    if `match' == "TCD"  
         replace longitude = real("1.2255")    if `match' == "TGO"  
         replace longitude = real("100.521")    if `match' == "THA"  
         replace longitude = real("68.7864")    if `match' == "TJK"  
         replace longitude = real("58.3794")    if `match' == "TKM"  
         replace longitude = real("125.567")    if `match' == "TLS"  
         replace longitude = real("-175.216")    if `match' == "TON"  
         replace longitude = real("-61.4789")    if `match' == "TTO"  
         replace longitude = real("10.21")    if `match' == "TUN"  
         replace longitude = real("32.3606")    if `match' == "TUR"  
         replace longitude = real("179.089567")    if `match' == "TUV"  
         replace longitude = real("<wb:longitude")    if `match' == "TWN"  
         replace longitude = real("35.7382")    if `match' == "TZA"  
         replace longitude = real("32.5729")    if `match' == "UGA"  
         replace longitude = real("30.5038")    if `match' == "UKR"  
         replace longitude = real("-56.0675")    if `match' == "URY"  
         replace longitude = real("-77.032")    if `match' == "USA"  
         replace longitude = real("69.269")    if `match' == "UZB"  
         replace longitude = real("-61.2653")    if `match' == "VCT"  
         replace longitude = real("-69.8371")    if `match' == "VEN"  
         replace longitude = real("-64.623056")    if `match' == "VGB"  
         replace longitude = real("-64.8963")    if `match' == "VIR"  
         replace longitude = real("105.825")    if `match' == "VNM"  
         replace longitude = real("168.321")    if `match' == "VUT"  
         replace longitude = real("-171.752")    if `match' == "WSM"  
         replace longitude = real("20.926")    if `match' == "XKX"  
         replace longitude = real("44.2075")    if `match' == "YEM"  
         replace longitude = real("28.1871")    if `match' == "ZAF"  
         replace longitude = real("28.2937")    if `match' == "ZMB"  
  
******************  Lable: longitude ******************
  
     lab var longitude           "Capital Longitude" 
 }        
  
 ****************************************************** 
  
 ******************  Values: latitude ****************** 
  
 qui if ("`latitude'" == "latitude") {      
  
         gen  double latitude = .  
         replace latitude = real("12.5167")    if `match' == "ABW"  
         replace latitude = real("34.5228")    if `match' == "AFG"  
         replace latitude = real("-8.81155")    if `match' == "AGO"  
         replace latitude = real("41.3317")    if `match' == "ALB"  
         replace latitude = real("42.5075")    if `match' == "AND"  
         replace latitude = real("24.4764")    if `match' == "ARE"  
         replace latitude = real("-34.6118")    if `match' == "ARG"  
         replace latitude = real("40.1596")    if `match' == "ARM"  
         replace latitude = real("-14.2846")    if `match' == "ASM"  
         replace latitude = real("17.1175")    if `match' == "ATG"  
         replace latitude = real("-35.282")    if `match' == "AUS"  
         replace latitude = real("48.2201")    if `match' == "AUT"  
         replace latitude = real("40.3834")    if `match' == "AZE"  
         replace latitude = real("-3.3784")    if `match' == "BDI"  
         replace latitude = real("50.8371")    if `match' == "BEL"  
         replace latitude = real("6.4779")    if `match' == "BEN"  
         replace latitude = real("12.3605")    if `match' == "BFA"  
         replace latitude = real("23.7055")    if `match' == "BGD"  
         replace latitude = real("42.7105")    if `match' == "BGR"  
         replace latitude = real("26.1921")    if `match' == "BHR"  
         replace latitude = real("25.0661")    if `match' == "BHS"  
         replace latitude = real("43.8607")    if `match' == "BIH"  
         replace latitude = real("53.9678")    if `match' == "BLR"  
         replace latitude = real("17.2534")    if `match' == "BLZ"  
         replace latitude = real("32.3293")    if `match' == "BMU"  
         replace latitude = real("-13.9908")    if `match' == "BOL"  
         replace latitude = real("-15.7801")    if `match' == "BRA"  
         replace latitude = real("13.0935")    if `match' == "BRB"  
         replace latitude = real("4.94199")    if `match' == "BRN"  
         replace latitude = real("27.5768")    if `match' == "BTN"  
         replace latitude = real("-24.6544")    if `match' == "BWA"  
         replace latitude = real("5.63056")    if `match' == "CAF"  
         replace latitude = real("45.4215")    if `match' == "CAN"  
         replace latitude = real("46.948")    if `match' == "CHE"  
         replace latitude = real("<wb:latitude")    if `match' == "CHI"  
         replace latitude = real("-33.475")    if `match' == "CHL"  
         replace latitude = real("40.0495")    if `match' == "CHN"  
         replace latitude = real("5.332")    if `match' == "CIV"  
         replace latitude = real("3.8721")    if `match' == "CMR"  
         replace latitude = real("-4.325")    if `match' == "COD"  
         replace latitude = real("-4.2767")    if `match' == "COG"  
         replace latitude = real("4.60987")    if `match' == "COL"  
         replace latitude = real("-11.6986")    if `match' == "COM"  
         replace latitude = real("14.9218")    if `match' == "CPV"  
         replace latitude = real("9.63701")    if `match' == "CRI"  
         replace latitude = real("23.1333")    if `match' == "CUB"  
         replace latitude = real("<wb:latitude")    if `match' == "CUW"  
         replace latitude = real("19.3022")    if `match' == "CYM"  
         replace latitude = real("35.1676")    if `match' == "CYP"  
         replace latitude = real("50.0878")    if `match' == "CZE"  
         replace latitude = real("52.5235")    if `match' == "DEU"  
         replace latitude = real("11.5806")    if `match' == "DJI"  
         replace latitude = real("15.2976")    if `match' == "DMA"  
         replace latitude = real("55.6763")    if `match' == "DNK"  
         replace latitude = real("18.479")    if `match' == "DOM"  
         replace latitude = real("36.7397")    if `match' == "DZA"  
         replace latitude = real("-0.229498")    if `match' == "ECU"  
         replace latitude = real("30.0982")    if `match' == "EGY"  
         replace latitude = real("15.3315")    if `match' == "ERI"  
         replace latitude = real("40.4167")    if `match' == "ESP"  
         replace latitude = real("59.4392")    if `match' == "EST"  
         replace latitude = real("9.02274")    if `match' == "ETH"  
         replace latitude = real("60.1608")    if `match' == "FIN"  
         replace latitude = real("-18.1149")    if `match' == "FJI"  
         replace latitude = real("48.8566")    if `match' == "FRA"  
         replace latitude = real("61.8926")    if `match' == "FRO"  
         replace latitude = real("6.91771")    if `match' == "FSM"  
         replace latitude = real("0.38832")    if `match' == "GAB"  
         replace latitude = real("51.5002")    if `match' == "GBR"  
         replace latitude = real("41.71")    if `match' == "GEO"  
         replace latitude = real("5.57045")    if `match' == "GHA"  
         replace latitude = real("<wb:latitude")    if `match' == "GIB"  
         replace latitude = real("9.51667")    if `match' == "GIN"  
         replace latitude = real("13.4495")    if `match' == "GMB"  
         replace latitude = real("11.8037")    if `match' == "GNB"  
         replace latitude = real("3.7523")    if `match' == "GNQ"  
         replace latitude = real("37.9792")    if `match' == "GRC"  
         replace latitude = real("12.0653")    if `match' == "GRD"  
         replace latitude = real("64.1836")    if `match' == "GRL"  
         replace latitude = real("14.6248")    if `match' == "GTM"  
         replace latitude = real("13.4443")    if `match' == "GUM"  
         replace latitude = real("6.80461")    if `match' == "GUY"  
         replace latitude = real("22.3964")    if `match' == "HKG"  
         replace latitude = real("15.1333")    if `match' == "HND"  
         replace latitude = real("45.8069")    if `match' == "HRV"  
         replace latitude = real("18.5392")    if `match' == "HTI"  
         replace latitude = real("47.4984")    if `match' == "HUN"  
         replace latitude = real("-6.19752")    if `match' == "IDN"  
         replace latitude = real("54.1509")    if `match' == "IMN"  
         replace latitude = real("28.6353")    if `match' == "IND"  
         replace latitude = real("53.3441")    if `match' == "IRL"  
         replace latitude = real("35.6878")    if `match' == "IRN"  
         replace latitude = real("33.3302")    if `match' == "IRQ"  
         replace latitude = real("64.1353")    if `match' == "ISL"  
         replace latitude = real("31.7717")    if `match' == "ISR"  
         replace latitude = real("41.8955")    if `match' == "ITA"  
         replace latitude = real("17.9927")    if `match' == "JAM"  
         replace latitude = real("31.9497")    if `match' == "JOR"  
         replace latitude = real("35.67")    if `match' == "JPN"  
         replace latitude = real("51.1879")    if `match' == "KAZ"  
         replace latitude = real("-1.27975")    if `match' == "KEN"  
         replace latitude = real("42.8851")    if `match' == "KGZ"  
         replace latitude = real("11.5556")    if `match' == "KHM"  
         replace latitude = real("1.32905")    if `match' == "KIR"  
         replace latitude = real("17.3")    if `match' == "KNA"  
         replace latitude = real("37.5323")    if `match' == "KOR"  
         replace latitude = real("29.3721")    if `match' == "KWT"  
         replace latitude = real("18.5826")    if `match' == "LAO"  
         replace latitude = real("33.8872")    if `match' == "LBN"  
         replace latitude = real("6.30039")    if `match' == "LBR"  
         replace latitude = real("32.8578")    if `match' == "LBY"  
         replace latitude = real("14")    if `match' == "LCA"  
         replace latitude = real("47.1411")    if `match' == "LIE"  
         replace latitude = real("6.92148")    if `match' == "LKA"  
         replace latitude = real("-29.5208")    if `match' == "LSO"  
         replace latitude = real("54.6896")    if `match' == "LTU"  
         replace latitude = real("49.61")    if `match' == "LUX"  
         replace latitude = real("56.9465")    if `match' == "LVA"  
         replace latitude = real("22.1667")    if `match' == "MAC"  
         replace latitude = real("<wb:latitude")    if `match' == "MAF"  
         replace latitude = real("33.9905")    if `match' == "MAR"  
         replace latitude = real("43.7325")    if `match' == "MCO"  
         replace latitude = real("47.0167")    if `match' == "MDA"  
         replace latitude = real("-20.4667")    if `match' == "MDG"  
         replace latitude = real("4.1742")    if `match' == "MDV"  
         replace latitude = real("19.427")    if `match' == "MEX"  
         replace latitude = real("7.11046")    if `match' == "MHL"  
         replace latitude = real("42.0024")    if `match' == "MKD"  
         replace latitude = real("13.5667")    if `match' == "MLI"  
         replace latitude = real("35.9042")    if `match' == "MLT"  
         replace latitude = real("21.914")    if `match' == "MMR"  
         replace latitude = real("42.4602")    if `match' == "MNE"  
         replace latitude = real("47.9129")    if `match' == "MNG"  
         replace latitude = real("15.1935")    if `match' == "MNP"  
         replace latitude = real("-25.9664")    if `match' == "MOZ"  
         replace latitude = real("18.2367")    if `match' == "MRT"  
         replace latitude = real("-20.1605")    if `match' == "MUS"  
         replace latitude = real("-13.9899")    if `match' == "MWI"  
         replace latitude = real("3.12433")    if `match' == "MYS"  
         replace latitude = real("-22.5648")    if `match' == "NAM"  
         replace latitude = real("-22.2677")    if `match' == "NCL"  
         replace latitude = real("13.514")    if `match' == "NER"  
         replace latitude = real("9.05804")    if `match' == "NGA"  
         replace latitude = real("12.1475")    if `match' == "NIC"  
         replace latitude = real("52.3738")    if `match' == "NLD"  
         replace latitude = real("59.9138")    if `match' == "NOR"  
         replace latitude = real("27.6939")    if `match' == "NPL"  
         replace latitude = real("-0.5477")    if `match' == "NRU"  
         replace latitude = real("-41.2865")    if `match' == "NZL"  
         replace latitude = real("23.6105")    if `match' == "OMN"  
         replace latitude = real("30.5167")    if `match' == "PAK"  
         replace latitude = real("8.99427")    if `match' == "PAN"  
         replace latitude = real("-12.0931")    if `match' == "PER"  
         replace latitude = real("14.5515")    if `match' == "PHL"  
         replace latitude = real("7.34194")    if `match' == "PLW"  
         replace latitude = real("-9.47357")    if `match' == "PNG"  
         replace latitude = real("52.26")    if `match' == "POL"  
         replace latitude = real("18.23")    if `match' == "PRI"  
         replace latitude = real("39.0319")    if `match' == "PRK"  
         replace latitude = real("38.7072")    if `match' == "PRT"  
         replace latitude = real("-25.3005")    if `match' == "PRY"  
         replace latitude = real("<wb:latitude")    if `match' == "PSE"  
         replace latitude = real("-17.535")    if `match' == "PYF"  
         replace latitude = real("25.2948")    if `match' == "QAT"  
         replace latitude = real("44.4479")    if `match' == "ROU"  
         replace latitude = real("55.7558")    if `match' == "RUS"  
         replace latitude = real("-1.95325")    if `match' == "RWA"  
         replace latitude = real("24.6748")    if `match' == "SAU"  
         replace latitude = real("15.5932")    if `match' == "SDN"  
         replace latitude = real("14.7247")    if `match' == "SEN"  
         replace latitude = real("1.28941")    if `match' == "SGP"  
         replace latitude = real("-9.42676")    if `match' == "SLB"  
         replace latitude = real("8.4821")    if `match' == "SLE"  
         replace latitude = real("13.7034")    if `match' == "SLV"  
         replace latitude = real("43.9322")    if `match' == "SMR"  
         replace latitude = real("2.07515")    if `match' == "SOM"  
         replace latitude = real("44.8024")    if `match' == "SRB"  
         replace latitude = real("4.85")    if `match' == "SSD"  
         replace latitude = real("0.20618")    if `match' == "STP"  
         replace latitude = real("5.8232")    if `match' == "SUR"  
         replace latitude = real("48.1484")    if `match' == "SVK"  
         replace latitude = real("46.0546")    if `match' == "SVN"  
         replace latitude = real("59.3327")    if `match' == "SWE"  
         replace latitude = real("-26.5225")    if `match' == "SWZ"  
         replace latitude = real("<wb:latitude")    if `match' == "SXM"  
         replace latitude = real("-4.6309")    if `match' == "SYC"  
         replace latitude = real("33.5146")    if `match' == "SYR"  
         replace latitude = real("21.4602778")    if `match' == "TCA"  
         replace latitude = real("12.1048")    if `match' == "TCD"  
         replace latitude = real("6.1228")    if `match' == "TGO"  
         replace latitude = real("13.7308")    if `match' == "THA"  
         replace latitude = real("38.5878")    if `match' == "TJK"  
         replace latitude = real("37.9509")    if `match' == "TKM"  
         replace latitude = real("-8.56667")    if `match' == "TLS"  
         replace latitude = real("-21.136")    if `match' == "TON"  
         replace latitude = real("10.6596")    if `match' == "TTO"  
         replace latitude = real("36.7899")    if `match' == "TUN"  
         replace latitude = real("39.7153")    if `match' == "TUR"  
         replace latitude = real("-8.6314877")    if `match' == "TUV"  
         replace latitude = real("<wb:latitude")    if `match' == "TWN"  
         replace latitude = real("-6.17486")    if `match' == "TZA"  
         replace latitude = real("0.314269")    if `match' == "UGA"  
         replace latitude = real("50.4536")    if `match' == "UKR"  
         replace latitude = real("-34.8941")    if `match' == "URY"  
         replace latitude = real("38.8895")    if `match' == "USA"  
         replace latitude = real("41.3052")    if `match' == "UZB"  
         replace latitude = real("13.2035")    if `match' == "VCT"  
         replace latitude = real("9.08165")    if `match' == "VEN"  
         replace latitude = real("18.431389")    if `match' == "VGB"  
         replace latitude = real("18.3358")    if `match' == "VIR"  
         replace latitude = real("21.0069")    if `match' == "VNM"  
         replace latitude = real("-17.7404")    if `match' == "VUT"  
         replace latitude = real("-13.8314")    if `match' == "WSM"  
         replace latitude = real("42.565")    if `match' == "XKX"  
         replace latitude = real("15.352")    if `match' == "YEM"  
         replace latitude = real("-25.746")    if `match' == "ZAF"  
         replace latitude = real("-15.3982")    if `match' == "ZMB"  
  
******************  Lable: latitude ******************
  
     lab var latitude                    "Capital Latitude" 
 }        
  
 ****************************************************** 
  
 end 
